In [1]:
import pandas as pd 
import requests
import json
from IPython.display import display as display_DF

In [2]:
JSON_Temp = requests.get(
        "https://pdumitradome.id/dome_api/rtdc/get_company/"
    ).json()
# print(JSON_Temp)
pd.json_normalize(JSON_Temp, record_path = 'result')

  cid                         company_name
0  16                        EMP Bentu Ltd
1  20               EMP Malacca Strait S.A
2  30                              GEODIPA
3  10                           HPM-REPSOL
4   9                              KS ORKA
5   1                     Parama Data Unit
6   5  PETROCHINA INTERNATIONAL JABUNG LTD
7  79                      TIMOR RESOURCES

In [3]:
CompList = json.loads(
    requests.get(
        "https://pdumitradome.id/dome_api/rtdc/get_company/"
    ).text
)

print(CompList)
CompList_DF = pd.json_normalize(CompList, record_path = 'result')
display_DF(CompList_DF)

{'status': 200, 'result': [{'cid': '16', 'company_name': 'EMP Bentu Ltd'}, {'cid': '20', 'company_name': 'EMP Malacca Strait S.A'}, {'cid': '30', 'company_name': 'GEODIPA'}, {'cid': '10', 'company_name': 'HPM-REPSOL'}, {'cid': '9', 'company_name': 'KS ORKA'}, {'cid': '1', 'company_name': 'Parama Data Unit'}, {'cid': '5', 'company_name': 'PETROCHINA INTERNATIONAL JABUNG LTD'}, {'cid': '79', 'company_name': 'TIMOR RESOURCES'}]}

  cid                         company_name
0  16                        EMP Bentu Ltd
1  20               EMP Malacca Strait S.A
2  30                              GEODIPA
3  10                           HPM-REPSOL
4   9                              KS ORKA
5   1                     Parama Data Unit
6   5  PETROCHINA INTERNATIONAL JABUNG LTD
7  79                      TIMOR RESOURCES

In [17]:
cid = 9
getWellAPI = "https://pdumitradome.id/dome_api/rtdc/get_well?cid=" + str(cid)


WellList = json.loads(
    requests.get(
        getWellAPI
    ).text
)

# print(WellList)

WellList_DF = pd.json_normalize(WellList, record_path = 'result')
WellList_DF['active_date'] = WellList_DF['active_date'].astype('datetime64')
WellList_DF['end_date'] = WellList_DF['end_date'].astype('datetime64')
# WellList_DF['end_date']


display_DF(WellList_DF)
print(WellList_DF.dtypes)
# print(WellList_DF['time_master'].to_list())

,wid,cid,well_name,rig_name,active_date,end_date,proposed_total_measured_depth,time_master
0,144,9,SMP AAE-02,PRA#1,2021-06-03,2021-07-31,4000,"[{'time_date_start': '2021-05-31', 'time_date_..."
1,145,9,SMP AA-02ST,Kaishan 1,2021-06-17,2021-08-31,4000,"[{'time_date_start': '2021-06-14', 'time_date_..."
2,146,9,SMP AAE-05,PRA#1,2021-06-28,2021-08-31,4000,"[{'time_date_start': '2021-06-28', 'time_date_..."
3,150,9,SMP AAE-06ST3,PRA#1,2021-08-12,2022-02-05,3000,"[{'time_date_start': '2021-08-09', 'time_date_..."
4,156,9,SMP AAE-07,PRA#1,2021-09-25,2021-10-31,3000,"[{'time_date_start': '2021-09-20', 'time_date_..."
5,160,9,SMP AAE-07ST3,PRA#1,2021-10-25,2022-01-01,3000,"[{'time_date_start': '2021-10-25', 'time_date_..."
6,170,9,SMP AAE-08,PRA#1,2022-01-27,2022-03-31,2500,"[{'time_date_start': '2022-01-24', 'time_date_..."

wid                                      object
cid                                      object
well_name                                object
rig_name                                 object
active_date                      datetime64[ns]
end_date                         datetime64[ns]
proposed_total_measured_depth            object
time_master                              object
dtype: object

In [4]:
getData_params ={
	"wid" : 144,
	"start" : "2021-06-03 00:00:00",
   	"end" : "2021-06-05 00:00:00"
}
import pandas as pd 
pd.DataFrame(getData_params, columns=['wid','start','end', 'hehe'], index=[0])

   wid                start                  end hehe
0  144  2021-06-03 00:00:00  2021-06-05 00:00:00  NaN

In [42]:
getData_params ={
	"wid" : 144,
	"start" : "2021-06-03 00:00:00",
   	"end" : "2021-06-05 00:00:00"
}


WellData = (
	(
        requests.get("https://pdumitradome.id/dome_api/rtdc/get_data", data=json.dumps(getData_params))
    ).text
)
# print(json.dumps(WellData))
Data_DF = pd.json_normalize(json.loads(WellData), record_path='result')
display_DF(Data_DF)

,dt,wid,sid,recid,seqid,date,time,actcode,blockpos,bitdepth,...,spare_9,spare_10,spare_50,spare_51,spare_52,spare_53,spare_54,spare_55,spare_56,label
0,2021-06-03 10:18:40,144,0,1,16151,2021-06-03,10:18:40,1,25.13,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
1,2021-06-03 10:18:45,144,0,1,16152,2021-06-03,10:18:45,1,25.13,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
2,2021-06-03 10:18:50,144,0,1,16153,2021-06-03,10:18:50,1,25.13,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
3,2021-06-03 10:18:55,144,0,1,16154,2021-06-03,10:18:55,1,25.13,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
4,2021-06-03 10:19:00,144,0,1,16155,2021-06-03,10:19:00,1,25.13,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16734,2021-06-04 23:59:40,144,0,1,32767,2021-06-04,23:59:40,3,28.14,147.60,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
16735,2021-06-04 23:59:45,144,0,1,32767,2021-06-04,23:59:45,3,28.35,147.38,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
16736,2021-06-04 23:59:50,144,0,1,32767,2021-06-04,23:59:50,3,28.56,147.17,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
16737,2021-06-04 23:59:55,144,0,1,32767,2021-06-04,23:59:55,3,28.80,146.93,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None
16738,2021-06-05 00:00:00,144,0,1,32767,2021-06-05,00:00:00,3,29.04,146.69,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,None

In [25]:
from datetime import datetime, timedelta

# print(WellList_DF.dtypes)
oneday = timedelta(days=1)

display_DF(WellList_DF.loc[2, 'active_date'])
display_DF(WellList_DF.loc[2, 'active_date'] - oneday)
print(type((WellList_DF.loc[2, 'active_date'] - oneday).date()))

Timestamp('2021-06-28 00:00:00')

Timestamp('2021-06-27 00:00:00')

<class 'datetime.date'>

In [3]:
import pandas as pd
dt = ['21-12-2020 00:00:00']
print(pd.to_datetime(dt))
print(dt)

DatetimeIndex(['2020-12-21'], dtype='datetime64[ns]', freq=None)
['21-12-2020 00:00:00']

In [12]:
import time
time.strptime('00:00:00', '%H:%M:%S')time()

AttributeError: 'time.struct_time' object has no attribute 'time'

In [37]:
WellName_DF = WellList_DF
WellName_Select = 'SMP AAE-02'
(WellName_DF.loc[WellName_DF['well_name']==WellName_Select, 'active_date']).values

array(['2021-06-03T00:00:00.000000000'], dtype='datetime64[ns]')

In [39]:
for i in Data_DF.columns:
    print(i)

dt
wid
sid
recid
seqid
date
time
actcode
blockpos
bitdepth
deptbitv
md
tvd
logdepth
speedup
speeddown
rop
ropi
timeropi
hklda
hkldx
hkldpu
hkldso
woba
wobx
torqa
torqx
torqp
torqb
rpm
rpmm
totrpm
stppress
csgpress
mudflowine
mudflowin
mudflowoute
mudflowout
mudflowoutp
diffflow
klflow
muddensin
muddensout
mudtempin
mudtempout
mudcondin
mudcondout
mfiann
mfianne
surfrev
drillrev
reamrev
circrev
totrev
drilltime
reamtime
circtime
pumptime
rotatingtime
drilldist
stroke1
stroke2
stroke3
stroke4
totstks
totstksa
spm1
spm2
spm3
spm4
spm5
totspm
totspma
totpumpede
totpumpvol
totpumpvolan
totpumpedea
tankvoltot
tankvolact
tankvoltt
tankvolchgtot
tankvolchgact
tankvolchgtt
plbit
plstr
plann
plsurf
plmtr
plmwd
bithydpwr
bithydpwra
jif
jetvel
annveln
annvelx
ecddpt
ecdbit
ecdshoe
phydpwr
deptretm
lagstks
lagtime
dnhstroke
dnhtime
mse
doc
gas
dstrength
mseds
clcontent
in_slips
bht
scfm
airflin
airfline
airfloutp
airflout
airpress
airtemp
whp
wht
h2s1
h2s2
h2s3
h2s4
co21
co22
co23
co24
bitsize
foamrate
spare_1
spare_2
spare_3
spare_4
spare_5
spare_6
spare_7
spare_8
spare_9
spare_10
spare_50
spare_51
spare_52
spare_53
spare_54
spare_55
spare_56
label

In [1]:
import pandas as pd

In [7]:
InputActivity_DB = pd.read_csv('RealTime_Test/Temp_InputActivity.csv', index_col = False)
InputActivity_DBx = pd.read_csv('RealTime_Test/AAE-08_TEST_EDIT.csv', index_col = False)

In [13]:
InputActivity_DB.dtypes

dt                object
Date              object
Time              object
Activity          object
Hook Treshold    float64
Remarks          float64
PIC              float64
dtype: object

In [14]:
InputActivity_DBx.dtypes

dt               object
Date             object
Time             object
Activity         object
Hook Treshold     int64
Remarks          object
PIC              object
dtype: object

## Activitylog & SummaryActivity API Test
Step nya
1. check table 
2. if return 202 bisa langsung exekusi (create,update,delete) if return 404 -> create table

    -https://pdumitradome.id/dome_api/rtdc/Activitylog/cek_table

    -https://pdumitradome.id/dome_api/rtdc/Activitylog/create_table

    -https://pdumitradome.id/dome_api/rtdc/Activitylog/create
    
    -https://pdumitradome.id/dome_api/rtdc/Activitylog/update
    
    -https://pdumitradome.id/dome_api/rtdc/Activitylog/delete
    
    -https://pdumitradome.id/dome_api/rtdc/Activitylog/get_data

    -https://pdumitradome.id/dome_api/rtdc/ActivitySummary/cek_table
    
    -https://pdumitradome.id/dome_api/rtdc/ActivitySummary/create_table
    
    -https://pdumitradome.id/dome_api/rtdc/ActivitySummary/create
    
    -https://pdumitradome.id/dome_api/rtdc/ActivitySummary/update
    
    -https://pdumitradome.id/dome_api/rtdc/ActivitySummary/delete
    
    -https://pdumitradome.id/dome_api/rtdc/ActivitySummary/get_data

In [4]:
import requests
import json

### Activitylog test

In [19]:
getData_params ={
	"wid" : 170,
	# "start" : "2022-02-18 15:12:00",
   	# "end" : "2022-02-18 15:22:00"
}

list_URL = [
	"https://pdumitradome.id/dome_api/rtdc/Activitylog/cek_table?wid=",
    "https://pdumitradome.id/dome_api/rtdc/Activitylog/create_table",
    "https://pdumitradome.id/dome_api/rtdc/Activitylog/create",  
    "https://pdumitradome.id/dome_api/rtdc/Activitylog/update",
    "https://pdumitradome.id/dome_api/rtdc/Activitylog/delete",
    "https://pdumitradome.id/dome_api/rtdc/Activitylog/get_data"
]

WellData = (
	(
        requests.get(list_URL[1], data=json.dumps(getData_params))
        # requests.get(list_URL[0]+(str(144)))
    )
)
print(WellData)

<Response [200]>

In [8]:
import requests, json
cid = 140
getWellAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/cek_table"
# getWellAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/get_data"
print(getWellAPI)
json_queries = {
    "wid" : 175,
}
response = (
    requests.post(
        getWellAPI, data=json.dumps(json_queries, indent = 4) 
    )
)
print(response.status_code)
print(response.json())

https://pdumitradome.id/dome_api/rtdc/Activitylog/cek_table
200
{'status': 200}

In [ ]:
# https://pdumitradome.id/dome_api/rtdc/Activitylog/cek_table
# https://pdumitradome.id/dome_api/rtdc/Activitylog/create_table
# https://pdumitradome.id/dome_api/rtdc/Activitylog/create
# https://pdumitradome.id/dome_api/rtdc/Activitylog/update
# https://pdumitradome.id/dome_api/rtdc/Activitylog/delete
# https://pdumitradome.id/dome_api/rtdc/Activitylog/get_data


import requests, json
json_queries = {
    "wid": 
}
response = (
    requests.post(
        getWellAPI, data=json.dumps(json_queries, indent = 4) 
    )
)
print(response.status_code)
print(response.json())

In [3]:
# cek table

getWellAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/cek_table"
import requests, json
json_queries = {
    "wid": 144
}

response = (
    requests.post(
        getWellAPI, data=json.dumps(json_queries, indent = 4) 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)
print(out['table'])

200
{'status': 200, 'table': 1}
1

In [2]:
# create table
getWellAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/create_table"
import requests, json
json_queries = {
    "wid": 144
}

response = (
    requests.post(
        getWellAPI, data=json.dumps(json_queries, indent = 4) 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)
# print(out['table'])

200
{'message': 'Create Table Success', 'status': 200}

In [47]:
# add data
import requests, json
AddRowAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/create"

json_queries = json.dumps(
    {
    "wid": 144,
    "dt": "2022-04-01 23:59:59",
    "date": "2022-03-26",
    "time": "23:59:59",
    "activity": "Test",
    "in_slip_threshold": 100,
    "remarks": "test",
    "pic": "irsyad",
    "section": "12 1/4"
    },
    indent = 4
)


response = (
    requests.post(
        AddRowAPI, data=json_queries 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)

200
{'message': 'Insert Data Success', 'status': 200}

In [18]:
import requests, json
getTableAPI = "http://khansadev.xyz/dome_api/rtdc/Activitylog/get_data"

json_queries = json.dumps(
    {
    "wid": 170,
	"start" : "2000-10-17 00:00:00",
   	"end" : "2050-10-17 00:00:00"
    },
    indent = 4
)
response = (
    requests.get(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
print(response.json())
# print(response.table)
# print(out)

<Response [200]>
{'status': 200, 'result': [{'id': '102', 'dt': '2022-02-14 12:00:00', 'date': '2022-02-14', 'time': '12:00:00', 'activity': 'MAKE UP BHA', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '103', 'dt': '2022-02-14 15:00:00', 'date': '2022-02-14', 'time': '15:00:00', 'activity': 'TRIP IN', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '104', 'dt': '2022-02-14 18:28:00', 'date': '2022-02-14', 'time': '18:28:12', 'activity': 'DRILL OUT CEMENT', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '105', 'dt': '2022-02-14 23:03:00', 'date': '2022-02-14', 'time': '23:03:45', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '106', 'dt': '2022-02-15 00:38:00', 'date': '2022-02-15', 'time': '00:38:51', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '107', 'dt': '2022-02-15 02:13:00', 'date': '2022-02-15', 'time': '02:13:52', 'activity': 'WIPER TRIP', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '108', 'dt': '2022-02-15 04:20:00', 'date': '2022-02-15', 'time': '04:20:12', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '109', 'dt': '2022-02-16 05:36:00', 'date': '2022-02-16', 'time': '05:36:08', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '110', 'dt': '2022-02-16 06:49:00', 'date': '2022-02-16', 'time': '06:49:34', 'activity': 'WIPER TRIP', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '111', 'dt': '2022-02-16 08:55:00', 'date': '2022-02-16', 'time': '08:55:03', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': '61', 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}, {'id': '118', 'dt': '2022-02-10 12:00:00', 'date': '2022-02-10', 'time': '12:00:00', 'activity': 'MAKE UP BHA', 'in_slip_threshold': '61', 'remarks': 'test different section data', 'pic': 'MIH', 'section': '26"'}, {'id': '120', 'dt': '2022-02-10 18:22:00', 'date': '2022-02-10', 'time': '18:22:00', 'activity': 'TRIP IN', 'in_slip_threshold': '61', 'remarks': 'test different section data', 'pic': 'MIH', 'section': '26"'}, {'id': '122', 'dt': '2022-02-10 19:11:00', 'date': '2022-02-10', 'time': '19:11:00', 'activity': 'DRILL OUT CEMENT', 'in_slip_threshold': '61', 'remarks': 'test different section data', 'pic': 'MIH', 'section': '26"'}, {'id': '123', 'dt': '2022-02-10 20:13:00', 'date': '2022-02-10', 'time': '20:13:00', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': '61', 'remarks': 'test different section data', 'pic': 'MIH', 'section': '26"'}, {'id': '124', 'dt': '2022-02-10 21:18:00', 'date': '2022-02-10', 'time': '21:18:00', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': '61', 'remarks': 'test different section data', 'pic': 'MIH', 'section': '26"'}, {'id': '125', 'dt': '2022-02-10 22:12:00', 'date': '2022-02-10', 'time': '22:12:00', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': '61', 'remarks': 'test different section data', 'pic': 'MIH', 'section': '26"'}, {'id': '127', 'dt': '2022-02-10 23:55:00', 'date': '2022-02-10', 'time': '23:55:00', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': '61', 'remarks': 'test different section data', 'pic': 'MIH', 'section': '26"'}]}

In [31]:
# delete

import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/delete"

json_queries = json.dumps(
    {
    "wid": 144,
    "id":6
    },
    indent = 4
)
response = (
    requests.post(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
# print(response.json())
# print(response.table)
# print(out)

<Response [200]>

In [57]:
# update

import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/update"

json_queries = json.dumps(
    {
    "wid": 144,
    "dt": "2022-04-01 23:59:59",
    "date": "2022-03-26",
    "time": "23:59:59",
    "activity": "Test",
    "in_slip_threshold": 100,
    "remarks": "test",
    "pic": "irsyad after updated v2",
    "section": "12 1/4",
    "id":7
    },
    indent = 4
)
response = (
    requests.post(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
# print(response.json())
# print(response.table)
# print(out)

<Response [200]>

In [32]:
# get data
import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/get_data"

json_queries = json.dumps(
    {
    "wid": 144,
	"start" : "2022-03-26 23:59:59",
   	"end" : "2022-04-10 23:59:59"
    },
    indent = 4
)
response = (
    requests.get(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
print(response.json())
# print(response.table)
# print(out)

<Response [200]>
{'status': 200, 'result': [{'id': '1', 'dt': '2022-03-28 23:59:59', 'date': '2022-03-27', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}, {'id': '2', 'dt': '2022-03-27 23:59:59', 'date': '2022-03-27', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}, {'id': '3', 'dt': '2022-03-26 23:59:59', 'date': '2022-03-26', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}, {'id': '7', 'dt': '2022-04-01 23:59:59', 'date': '2022-03-26', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irsyad after updated v2', 'section': '12 1/4'}]}

# -----

In [1]:
# cek table

getWellAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/cek_table"
import requests, json
json_queries = {
    "wid": 170
}

response = (
    requests.post(
        getWellAPI, data=json.dumps(json_queries, indent = 4) 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)
print(out['table'])

200
{'status': 200, 'table': 1}
1

In [12]:
# create table
getWellAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/create_table"
import requests, json
json_queries = {
    "wid": 144
}

response = (
    requests.post(
        getWellAPI, data=json.dumps(json_queries, indent = 4) 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)
# print(out['table'])

200
{'message': 'Create Table Success', 'status': 200}

In [39]:
# add data
import requests, json
AddRowAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/create"

json_queries = json.dumps(
{
    "wid": 144,
    "date": "2022-03-29",
    "time_start": "2022-03-29 00:00:10",
    "time_end": "2022-03-29 00:00:16",
    "duration_minutes": 100,
    "hole_depth": 100,
    "bit_depth": 100,
    "meterage_drilling": 100,
    "rotate_drilling_time": 100,
    "slide_drilling_time": 100,
    "reaming_time": 100,
    "connection_time": 100,
    "on_bottom_hours": 100,
    "stand_duration": 100,
    "label_subactivity": 100,
    "label_activity": 100,
    "stand_meterage_drilling": 100,
    "stand_durationx": 100,
    "stand_on_bottom": 100,
    "pic": 100,
    "section": 100,
    "remark": "tessssss",
    "stand_group": 100
},
    indent = 4
)


response = (
    requests.post(
        AddRowAPI, data=json_queries 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)

200
{'message': 'Insert Data Success', 'status': 200}

In [40]:
import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/get_data"

json_queries = json.dumps(
    {
    "wid": 144,
	"start" : "2022-03-26 23:59:59",
   	"end" : "2022-04-10 23:59:59"
    },
    indent = 4
)
response = (
    requests.get(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
print(response.json())
# print(response.table)
# print(out)

<Response [200]>
{'status': 200, 'result': [{'date': '2022-03-27', 'time_start': '2022-03-27 23:59:59', 'time_end': '2022-03-27 23:59:59', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': '100', 'stand_group': '100'}, {'date': '2022-03-27', 'time_start': '2022-03-28 23:59:59', 'time_end': '2022-03-28 00:00:10', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': '100', 'stand_group': '100'}, {'date': '2022-03-29', 'time_start': '2022-03-29 00:00:10', 'time_end': '2022-03-29 00:00:16', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': 'tessssss', 'stand_group': '100'}]}

In [41]:
# delete

import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/delete"

json_queries = json.dumps(
    {
    "wid": 144,
    "time_start":"2022-03-29 00:00:10"
    },
    indent = 4
)
response = (
    requests.post(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
# print(response.json())
# print(response.table)
# print(out)

<Response [200]>

In [42]:
import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/get_data"

json_queries = json.dumps(
    {
    "wid": 144,
	"start" : "2022-03-26 23:59:59",
   	"end" : "2022-04-10 23:59:59"
    },
    indent = 4
)
response = (
    requests.get(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
print(response.json())
# print(response.table)
# print(out)

<Response [200]>
{'status': 200, 'result': [{'date': '2022-03-27', 'time_start': '2022-03-27 23:59:59', 'time_end': '2022-03-27 23:59:59', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': '100', 'stand_group': '100'}, {'date': '2022-03-27', 'time_start': '2022-03-28 23:59:59', 'time_end': '2022-03-28 00:00:10', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': '100', 'stand_group': '100'}]}

In [43]:
# add data
import requests, json
AddRowAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/create"

json_queries = json.dumps(
{
    "wid": 144,
    "date": "2022-03-29",
    "time_start": "2022-03-29 00:00:10",
    "time_end": "2022-03-29 00:00:16",
    "duration_minutes": 100,
    "hole_depth": 100,
    "bit_depth": 100,
    "meterage_drilling": 100,
    "rotate_drilling_time": 100,
    "slide_drilling_time": 100,
    "reaming_time": 100,
    "connection_time": 100,
    "on_bottom_hours": 100,
    "stand_duration": 100,
    "label_subactivity": 100,
    "label_activity": 100,
    "stand_meterage_drilling": 100,
    "stand_durationx": 100,
    "stand_on_bottom": 100,
    "pic": 100,
    "section": 100,
    "remark": "after update",
    "stand_group": 100
},
    indent = 4
)


response = (
    requests.post(
        AddRowAPI, data=json_queries 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)

200
{'message': 'Insert Data Success', 'status': 200}

In [44]:
import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/get_data"

json_queries = json.dumps(
    {
    "wid": 144,
	"start" : "2022-03-26 23:59:59",
   	"end" : "2022-04-10 23:59:59"
    },
    indent = 4
)
response = (
    requests.get(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
print(response)
print(response.json())
# print(response.table)
# print(out)

<Response [200]>
{'status': 200, 'result': [{'date': '2022-03-27', 'time_start': '2022-03-27 23:59:59', 'time_end': '2022-03-27 23:59:59', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': '100', 'stand_group': '100'}, {'date': '2022-03-27', 'time_start': '2022-03-28 23:59:59', 'time_end': '2022-03-28 00:00:10', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': '100', 'stand_group': '100'}, {'date': '2022-03-29', 'time_start': '2022-03-29 00:00:10', 'time_end': '2022-03-29 00:00:16', 'duration_minutes': '100', 'hole_depth': '100', 'bit_depth': '100', 'meterage_drilling': '100', 'rotate_drilling_time': '100', 'slide_drilling_time': '100', 'reaming_time': '100', 'connection_time': '100', 'on_bottom_hours': '100', 'stand_duration': '100', 'label_subactivity': '100', 'label_activity': '100', 'stand_meterage_drilling': '100', 'stand_durationx': '100', 'stand_on_bottom': '100', 'pic': '100', 'section': '100', 'remark': 'after update', 'stand_group': '100'}]}

## test IOData

In [2]:
from Streamlit_App import IO_Data

In [16]:
wid = 144

result = IO_Data.DomeCekTable(wid)
print(result['table'])
print(IO_Data.DomeCekTable(wid)['table'])

1
1

In [12]:
wid = 144
start_date_time = "2022-03-26 23:59:59"
end_date_time = "2022-04-10 23:59:59"
out_get = IO_Data.DomeGetData(wid, start_date_time, end_date_time)

dict_test = out_get['result']
print(dict_test)

[{'id': '1', 'dt': '2022-03-28 23:59:59', 'date': '2022-03-27', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}, {'id': '2', 'dt': '2022-03-27 23:59:59', 'date': '2022-03-27', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}, {'id': '3', 'dt': '2022-03-26 23:59:59', 'date': '2022-03-26', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}, {'id': '7', 'dt': '2022-04-01 23:59:59', 'date': '2022-03-26', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irsyad after updated v2', 'section': '12 1/4'}]

In [15]:
import pandas as pd
new = pd.DataFrame.from_dict(dict_test)
new.rename(columns = {'id':'input_id'}, inplace = True)
new

,input_id,dt,date,time,activity,in_slip_threshold,remarks,pic,section
0,1,2022-03-28 23:59:59,2022-03-27,23:59:59,Test,100,test,irfan,12 1/4
1,2,2022-03-27 23:59:59,2022-03-27,23:59:59,Test,100,test,irfan,12 1/4
2,3,2022-03-26 23:59:59,2022-03-26,23:59:59,Test,100,test,irfan,12 1/4
3,7,2022-04-01 23:59:59,2022-03-26,23:59:59,Test,100,test,irsyad after updated v2,12 1/4

In [18]:
new

,input_id,dt,date,time,activity,in_slip_threshold,remarks,pic,section
0,1,2022-03-28 23:59:59,2022-03-27,23:59:59,Test,100,test,irfan,12 1/4
1,2,2022-03-27 23:59:59,2022-03-27,23:59:59,Test,100,test,irfan,12 1/4
2,3,2022-03-26 23:59:59,2022-03-26,23:59:59,Test,100,test,irfan,12 1/4
3,7,2022-04-01 23:59:59,2022-03-26,23:59:59,Test,100,test,irsyad after updated v2,12 1/4

In [48]:
list_dict = new.to_dict("index")

In [46]:
for idx,row in new.iterrows():
    # print(row)
    # print(type(row))
    print(row.to_dict())

{'input_id': '1', 'dt': '2022-03-28 23:59:59', 'date': '2022-03-27', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}
{'input_id': '2', 'dt': '2022-03-27 23:59:59', 'date': '2022-03-27', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}
{'input_id': '3', 'dt': '2022-03-26 23:59:59', 'date': '2022-03-26', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irfan', 'section': '12 1/4'}
{'input_id': '7', 'dt': '2022-04-01 23:59:59', 'date': '2022-03-26', 'time': '23:59:59', 'activity': 'Test', 'in_slip_threshold': '100', 'remarks': 'test', 'pic': 'irsyad after updated v2', 'section': '12 1/4'}

In [72]:
input_DF['date'].map(str) + " " + input_DF['time'].map(str)

input_id
1     14-02-2022 12:00:00
2     14-02-2022 15:00:00
3     14-02-2022 18:28:12
6     14-02-2022 23:03:45
7     15-02-2022 00:38:51
8     15-02-2022 02:13:52
9     15-02-2022 04:20:12
10    16-02-2022 05:36:08
11    16-02-2022 06:49:34
12    16-02-2022 08:55:03
dtype: object

In [104]:
import pandas as pd 
from Streamlit_App import IO_Data


input_DF = pd.read_csv("ForInput2Dome\\KS ORKA_SMP AAE-08_InputActivityDB.csv", sep=";")

input_DF.rename(
    columns = {'id':'input_id', "Hook Treshold":"in_slip_threshold", "Activity":"activity"},
    inplace = True
)
input_DF = input_DF.set_index("input_id")
display(input_DF)
input_DF['wid'] = 170

input_DF["wid"] = input_DF["wid"].astype("int")
# input_DF["dt"] = input_DF["dt"].astype("string")

input_DF["activity"] = input_DF["activity"].astype("string")
input_DF["in_slip_threshold"] = input_DF["in_slip_threshold"].astype("int")
input_DF["remarks"] = input_DF["remarks"].astype("string")
input_DF["pic"] = input_DF["pic"].astype("string")
input_DF["section"] = input_DF["section"].astype("string")
input_DF["date"] = pd.to_datetime(input_DF["date"])
input_DF["time"] = pd.to_datetime(input_DF["time"])
input_DF["dt"] = pd.to_datetime(input_DF["dt"])
input_DF["date"] = input_DF["date"].map(str)
input_DF["time"] = input_DF["time"].map(str)
input_DF["dt"] = input_DF["dt"].map(str)

# input_DF['dt'] = input_DF['dt'].str.replace('/','-')

input_DF = input_DF[["wid",'dt',  "date", "time", "activity", "in_slip_threshold", "remarks", "pic", "section"]]
# df['first_set'] = df['first_set'].str.replace('_','|')
input_DF.dtypes

for idx,row in input_DF.iterrows():
    # print(row)
    # print(type(row))
    print(row.to_dict())
    print(IO_Data.DomeAddData(170,row.to_dict()))

,dt,date,time,comp,well,activity,in_slip_threshold,remarks,pic,section
input_id,,,,,,,,,,
1,14/02/2022 12:00,14/02/2022,12:00:00,KS ORKA,SMP AAE-08,MAKE UP BHA,61,Test Data,BM,17 1/2
2,14/02/2022 15:00,14/02/2022,15:00:00,KS ORKA,SMP AAE-08,TRIP IN,61,Test Data,BM,17 1/2
3,14/02/2022 18:28,14/02/2022,18:28:12,KS ORKA,SMP AAE-08,DRILL OUT CEMENT,61,Test Data,BM,17 1/2
6,14/02/2022 23:03,14/02/2022,23:03:45,KS ORKA,SMP AAE-08,DRILLING FORMATION,61,Test Data,BM,17 1/2
7,15/02/2022 00:38,15/02/2022,00:38:51,KS ORKA,SMP AAE-08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
8,15/02/2022 02:13,15/02/2022,02:13:52,KS ORKA,SMP AAE-08,WIPER TRIP,61,Test Data,BM,17 1/2
9,15/02/2022 04:20,15/02/2022,04:20:12,KS ORKA,SMP AAE-08,DRILLING FORMATION,61,Test Data,BM,17 1/2
10,16/02/2022 05:36,16/02/2022,05:36:08,KS ORKA,SMP AAE-08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
11,16/02/2022 06:49,16/02/2022,06:49:34,KS ORKA,SMP AAE-08,WIPER TRIP,61,Test Data,BM,17 1/2
12,16/02/2022 08:55,16/02/2022,08:55:03,KS ORKA,SMP AAE-08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2

{'wid': 170, 'dt': '2022-02-14 12:00:00', 'date': '2022-02-14 00:00:00', 'time': '2022-04-30 12:00:00', 'activity': 'MAKE UP BHA', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-14 15:00:00', 'date': '2022-02-14 00:00:00', 'time': '2022-04-30 15:00:00', 'activity': 'TRIP IN', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-14 18:28:00', 'date': '2022-02-14 00:00:00', 'time': '2022-04-30 18:28:12', 'activity': 'DRILL OUT CEMENT', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-14 23:03:00', 'date': '2022-02-14 00:00:00', 'time': '2022-04-30 23:03:45', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-15 00:38:00', 'date': '2022-02-15 00:00:00', 'time': '2022-04-30 00:38:51', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-15 02:13:00', 'date': '2022-02-15 00:00:00', 'time': '2022-04-30 02:13:52', 'activity': 'WIPER TRIP', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-15 04:20:00', 'date': '2022-02-15 00:00:00', 'time': '2022-04-30 04:20:12', 'activity': 'DRILLING FORMATION', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-16 05:36:00', 'date': '2022-02-16 00:00:00', 'time': '2022-04-30 05:36:08', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-16 06:49:00', 'date': '2022-02-16 00:00:00', 'time': '2022-04-30 06:49:34', 'activity': 'WIPER TRIP', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}
{'wid': 170, 'dt': '2022-02-16 08:55:00', 'date': '2022-02-16 00:00:00', 'time': '2022-04-30 08:55:03', 'activity': 'CIRCULATE HOLE CLEANING', 'in_slip_threshold': 61, 'remarks': 'Test Data', 'pic': 'BM', 'section': '17 1/2'}
{'message': 'Insert Data Success', 'status': 200}

In [46]:
input_DF.dtypes

wid                   int64
dt                   object
date                 object
time                 object
comp                 object
well                 object
activity             object
in_slip_threshold     int64
remarks              object
pic                  object
section              object
dtype: object

In [61]:
IO_Data.DomeGetData(170, "2022-02-13 00:00:00", "2022-02-17 00:00:00")

{'status': 200,
 'result': [{'id': '11',
   'dt': '2022-02-15 23:59:59',
   'date': '2022-02-15',
   'time': '23:59:59',
   'activity': 'Test',
   'in_slip_threshold': '100',
   'remarks': 'test',
   'pic': 'irsyad',
   'section': '12 1/4'}]}

In [12]:
from datetime import datetime, timedelta
tes = datetime.strptime('00:00:00', '%H:%M:%S')

In [13]:
tes.time()

datetime.time(0, 0)

In [113]:
import requests, json
getTableAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/get_data"

json_queries = json.dumps(
    {
    "wid": 170,
	"start" : "2022-02-01 23:59:59",
   	"end" : "2022-03-20 23:59:59"
    },
    indent = 4
)
response = (
    requests.get(
        getTableAPI, data=json_queries 
    )
)
# out = dict(response.json())
# print(response)
# print(response.json()['result'])
output = dict(response.json())['result']
# print(response.table)
# print(out)
pd.DataFrame(output)

,id,dt,date,time,activity,in_slip_threshold,remarks,pic,section
0,11,2022-02-15 23:59:59,2022-02-15,23:59:59,Test,100,test,irsyad,12 1/4
1,102,2022-02-14 12:00:00,2022-02-14,12:00:00,MAKE UP BHA,61,Test Data,BM,17 1/2
2,103,2022-02-14 15:00:00,2022-02-14,15:00:00,TRIP IN,61,Test Data,BM,17 1/2
3,104,2022-02-14 18:28:00,2022-02-14,18:28:12,DRILL OUT CEMENT,61,Test Data,BM,17 1/2
4,105,2022-02-14 23:03:00,2022-02-14,23:03:45,DRILLING FORMATION,61,Test Data,BM,17 1/2
5,106,2022-02-15 00:38:00,2022-02-15,00:38:51,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
6,107,2022-02-15 02:13:00,2022-02-15,02:13:52,WIPER TRIP,61,Test Data,BM,17 1/2
7,108,2022-02-15 04:20:00,2022-02-15,04:20:12,DRILLING FORMATION,61,Test Data,BM,17 1/2
8,109,2022-02-16 05:36:00,2022-02-16,05:36:08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
9,110,2022-02-16 06:49:00,2022-02-16,06:49:34,WIPER TRIP,61,Test Data,BM,17 1/2
10,111,2022-02-16 08:55:00,2022-02-16,08:55:03,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2

In [30]:
# add data
import requests, json
AddRowAPI = "https://pdumitradome.id/dome_api/rtdc/Activitylog/create"

json_queries = json.dumps(
    {
    "wid": 170,
    "dt": "2022-02-15 23:59:59",
    "date": "2022-02-15",
    "time": "23:59:59",
    "activity": "Test",
    "in_slip_threshold": 100,
    "remarks": "test",
    "pic": "irsyad",
    "section": "12 1/4"
    },
    indent = 4
)


response = (
    requests.post(
        AddRowAPI, data=json_queries 
    )
)
out = dict(response.json())
print(response.status_code)
# print(response.table)
print(out)

200
{'message': 'Insert Data Success', 'status': 200}

dict

In [109]:
dict_test =     {
    "wid": 144,
    "dt": "2022-04-01 23:59:59",
    "date": "2022-03-26",
    "time": "23:59:59",
    "activity": "Test",
    "in_slip_threshold": 100,
    "remarks": "test",
    "pic": "irsyad",
    "section": "12 1/4"
    }
dict_test

{'wid': 144,
 'dt': '2022-04-01 23:59:59',
 'date': '2022-03-26',
 'time': '23:59:59',
 'activity': 'Test',
 'in_slip_threshold': 100,
 'remarks': 'test',
 'pic': 'irsyad',
 'section': '12 1/4'}

In [114]:
{'wid': 170, 'dt': '2022-02-17 13:50:00', 'date': '2022-02-17', 'time': '13:50:00', 'activity': 'CEMENTING JOB', 'in_slip_treshold': 61.0, 'remarks': 'sad', 'pic': 'asd', 'section': '26"'}

{'wid': 170,
 'dt': '2022-02-17 13:50:00',
 'date': '2022-02-17',
 'time': '13:50:00',
 'activity': 'CEMENTING JOB',
 'in_slip_treshold': 61.0,
 'remarks': 'sad',
 'pic': 'asd',
 'section': '26"'}

In [59]:
for i in dict_test.values():
    print(i)
    print(type(i))

144
<class 'int'>
2022-04-01 23:59:59
<class 'str'>
2022-03-26
<class 'str'>
23:59:59
<class 'str'>
Test
<class 'str'>
100
<class 'int'>
test
<class 'str'>
irsyad
<class 'str'>
12 1/4
<class 'str'>

In [100]:
input_DF_2 = pd.read_csv("ForInput2Dome\\KS ORKA_SMP AAE-08_InputActivityDB.csv", sep=";")
# input_DF_2['date'] = input_DF_2['date'].str.replace('/','-')
input_DF_2["date"] = pd.to_datetime(input_DF_2["date"])
input_DF_2["time"] = pd.to_datetime(input_DF_2["time"])
input_DF_2["dt"] = pd.to_datetime(input_DF_2["dt"])
# input_DF_2["dt"] = input_DF_2["date"] + input_DF_2["time"]
# datetime.combine(StartDate, StartTime)
display(input_DF_2)
input_DF_2.dtypes

,input_id,dt,date,time,comp,well,Activity,Hook Treshold,remarks,pic,section
0,1,2022-02-14 12:00:00,2022-02-14,2022-04-30 12:00:00,KS ORKA,SMP AAE-08,MAKE UP BHA,61,Test Data,BM,17 1/2
1,2,2022-02-14 15:00:00,2022-02-14,2022-04-30 15:00:00,KS ORKA,SMP AAE-08,TRIP IN,61,Test Data,BM,17 1/2
2,3,2022-02-14 18:28:00,2022-02-14,2022-04-30 18:28:12,KS ORKA,SMP AAE-08,DRILL OUT CEMENT,61,Test Data,BM,17 1/2
3,6,2022-02-14 23:03:00,2022-02-14,2022-04-30 23:03:45,KS ORKA,SMP AAE-08,DRILLING FORMATION,61,Test Data,BM,17 1/2
4,7,2022-02-15 00:38:00,2022-02-15,2022-04-30 00:38:51,KS ORKA,SMP AAE-08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
5,8,2022-02-15 02:13:00,2022-02-15,2022-04-30 02:13:52,KS ORKA,SMP AAE-08,WIPER TRIP,61,Test Data,BM,17 1/2
6,9,2022-02-15 04:20:00,2022-02-15,2022-04-30 04:20:12,KS ORKA,SMP AAE-08,DRILLING FORMATION,61,Test Data,BM,17 1/2
7,10,2022-02-16 05:36:00,2022-02-16,2022-04-30 05:36:08,KS ORKA,SMP AAE-08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2
8,11,2022-02-16 06:49:00,2022-02-16,2022-04-30 06:49:34,KS ORKA,SMP AAE-08,WIPER TRIP,61,Test Data,BM,17 1/2
9,12,2022-02-16 08:55:00,2022-02-16,2022-04-30 08:55:03,KS ORKA,SMP AAE-08,CIRCULATE HOLE CLEANING,61,Test Data,BM,17 1/2

input_id                  int64
dt               datetime64[ns]
date             datetime64[ns]
time             datetime64[ns]
comp                     object
well                     object
Activity                 object
Hook Treshold             int64
remarks                  object
pic                      object
section                  object
dtype: object

In [115]:
pd.DataFrame(columns=['a', 'b'])

Empty DataFrame
Columns: [a, b]
Index: []

# Test IOInput Summary Data

In [2]:
from Streamlit_App import IO_Data

In [3]:
wid= 170

In [5]:
IO_Data.DomeCekTable(wid, table_type="Activity Summary")

{'status': 200, 'table': 1}

In [ ]:
IO_Data.DomeAddData(dict_row, table_type="Activity Summary")

In [6]:
start_date_time = "2022-01-01 23:59:59"
end_date_time = "2022-04-01 23:59:59"

IO_Data.DomeGetData(wid, start_date_time, end_date_time, table_type="Activity Summary")

[]

In [22]:
import pandas as pd
ActivitySummary_DF = pd.read_csv("RealTime_Test\\KS ORKA_SMP AAE-08_ActivitySummary_FinalTest.csv", sep=",")
ActivitySummary_DF

,Date,Start Time,End Time,date_time,Duration (Minutes),Hole Depth (Max),Bit Depth(mean),Drilling Meterage (m),Rotate Drilling (minutes),Slide Drilling (minutes),...,SUB-ACTIVITY,ACTIVITY,MERGE_SubActivity-Activity,PIC,Remarks,Section,Total Stand Drilling Meterage (m),Total Stand Duration (hrs),Total On Bottom Duration (hrs),Stand Group_Pred
0,2022-02-14 00:00:00,00:00:00,12:00:03,2022-02-14 00:00:00,719.97,718.02,640.800000,0.0,0.0,0.0,...,FALSE/Check,NaN,nan--FALSE/Check,NaN,NaN,NaN,0.0,0.00,0.0,NaN
1,2022-02-14 00:00:00,12:00:03,15:00:01,2022-02-14 12:00:03,179.88,747.38,732.210000,0.0,0.0,0.0,...,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA,BM,Test Data,17 1/2,0.0,0.00,0.0,NaN
2,2022-02-14 00:00:00,15:00:01,15:09:11,2022-02-14 15:00:01,9.08,749.55,748.480000,0.0,0.0,0.0,...,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,BM,Test Data,17 1/2,0.0,0.00,0.0,NaN
3,2022-02-14 00:00:00,15:09:11,15:09:21,2022-02-14 15:09:11,0.00,749.57,749.570000,0.0,0.0,0.0,...,Circulation,TRIP IN,TRIP IN--Circulation,BM,Test Data,17 1/2,0.0,0.00,0.0,NaN
4,2022-02-14 00:00:00,15:09:21,15:09:36,2022-02-14 15:09:21,0.17,749.61,749.600000,0.0,0.0,0.0,...,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,BM,Test Data,17 1/2,0.0,0.00,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,2022-02-16 00:00:00,08:55:03,08:56:33,2022-02-16 08:55:03,1.16,1129.06,1099.685000,0.0,0.0,0.0,...,Connection,CIRCULATE HOLE CLEANING,CIRCULATE HOLE CLEANING--Connection,BM,Test Data,17 1/2,0.0,1.16,0.0,NaN
447,2022-02-16 00:00:00,08:56:33,08:56:38,2022-02-16 08:56:33,0.00,1129.06,1101.030000,0.0,0.0,0.0,...,FALSE/Check,CIRCULATE HOLE CLEANING,CIRCULATE HOLE CLEANING--FALSE/Check,BM,Test Data,17 1/2,0.0,0.00,0.0,Stand Group - 53
448,2022-02-16 00:00:00,08:56:38,09:04:28,2022-02-16 08:56:38,7.75,1129.06,1116.060000,0.0,0.0,0.0,...,Wash Up/Down,CIRCULATE HOLE CLEANING,CIRCULATE HOLE CLEANING--Wash Up/Down,BM,Test Data,17 1/2,0.0,0.00,0.0,Stand Group - 53
449,2022-02-16 00:00:00,09:04:28,10:12:48,2022-02-16 09:04:28,68.17,1129.06,1107.840000,0.0,0.0,0.0,...,Reaming,CIRCULATE HOLE CLEANING,CIRCULATE HOLE CLEANING--Reaming,BM,Test Data,17 1/2,0.0,0.00,0.0,Stand Group - 53
450,2022-02-16 00:00:00,10:12:48,23:55:52,2022-02-16 10:12:48,814.84,1129.06,487.148378,0.0,0.0,0.0,...,Connection,CIRCULATE HOLE CLEANING,CIRCULATE HOLE CLEANING--Connection,BM,Test Data,17 1/2,0.0,890.76,0.0,NaN

In [23]:
for i in ActivitySummary_DF.columns:
    print(i)

Date
Start Time
End Time
date_time
Duration (Minutes)
Hole Depth (Max)
Bit Depth(mean)
Drilling Meterage (m)
Rotate Drilling (minutes)
Slide Drilling (minutes)
Reaming (minutes)
Connection (minutes)
On Bottom state (Hours)
Stand Duration
SUB-ACTIVITY
ACTIVITY
MERGE_SubActivity-Activity
PIC
Remarks
Section
Total Stand Drilling Meterage (m)
Total Stand Duration (hrs)
Total On Bottom Duration (hrs)
Stand Group_Pred

In [98]:
# add data
import requests, json
AddRowAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/create"
ActivitySummary_DF = pd.read_csv("RealTime_Test\\KS ORKA_SMP AAE-08_ActivitySummary_FinalTest.csv", sep=",")
ActivitySummary_DF['PIC'] = 'BM'
ActivitySummary_DF['Section'] = '17" 1/2'
ActivitySummary_DF['Remarks'] = 'RTDC Check'


# ActivitySummary_DF
json_queries = json.dumps(
    {
        "wid": 144,
        "date": "2022-03-29",
        "time_start": "2022-03-29 00:00:10",
        "time_end": "2022-03-29 00:00:16",
        "duration_minutes": 100,
        "hole_depth": 100,
        "bit_depth": 100,
        "meterage_drilling": 100,
        "rotate_drilling_time": 100,
        "slide_drilling_time": 100,
        "reaming_time": 100,
        "connection_time": 100,
        "on_bottom_hours": 100,
        "stand_duration": 100,
        "label_subactivity": 100,
        "label_activity": 100,
        "stand_meterage_drilling": 100,
        "stand_durationx": 100,
        "stand_on_bottom": 100,
        "pic": 100,
        "section": 100,
        "remark": "after update",
        "stand_group": 100
    }
)
list_rename_column = {
    'wid':'wid',
    'Date':'date',
    'Start Time':'time_start',
    'End Time':'time_end',
    'Duration (Minutes)':'duration_minutes',
    'Hole Depth (Max)':'hole_depth',
    'Bit Depth(mean)':'bit_depth',
    'Drilling Meterage (m)':'meterage_drilling',
    'Rotate Drilling (minutes)':'rotate_drilling_time',
    'Slide Drilling (minutes)':'slide_drilling_time',
    'Reaming (minutes)':'reaming_time',
    'Connection (minutes)':'connection_time',
    'On Bottom state (Hours)':'on_bottom_hours',
    'Stand Duration':'stand_duration',
    'SUB-ACTIVITY':'label_subactivity',
    'ACTIVITY':'label_activity',
    'Total Stand Drilling Meterage (m)':'stand_meterage_drilling',
    'Total Stand Duration (hrs)':'stand_durationx',
    'Total On Bottom Duration (hrs)':'stand_on_bottom',
    "PIC":"pic",
    "Remarks":"remark",
    "Section":"section",
    'Stand Group_Pred':'stand_group',
}

ActivitySummary_DF.rename(columns = list_rename_column, inplace = True)
ActivitySummary_DF['wid'] = wid
# ActivitySummary_DF.rename


ActivitySummary_DF['time_start'] = pd.to_datetime(ActivitySummary_DF['date'].str.split(' ', expand=True)[0] + ' ' + ActivitySummary_DF['time_start']).dt.strftime('%Y-%m-%d %H:%M:%S')
ActivitySummary_DF['time_end'] = pd.to_datetime(ActivitySummary_DF['date'].str.split(' ', expand=True)[0] + ' ' + ActivitySummary_DF['time_end']).dt.strftime('%Y-%m-%d %H:%M:%S')

ActivitySummary_DF['date'] = ActivitySummary_DF['date'].astype('datetime64').dt.strftime('%Y-%m-%d')


list_float64_col = ["duration_minutes",
"hole_depth",
"bit_depth",
"meterage_drilling",
"rotate_drilling_time",
"slide_drilling_time",
"reaming_time",
"connection_time",
"on_bottom_hours",
"stand_duration"
]

list_string_col = ["label_subactivity",
"label_activity",
"MERGE_SubActivity-Activity",
"pic",
"remark",
"section",
]

display(ActivitySummary_DF[list_string_col].head(5))
for string_col in list_string_col:
    ActivitySummary_DF[string_col] = ActivitySummary_DF[string_col].astype('string')

ActivitySummary_DF[list_string_col] = ActivitySummary_DF[list_string_col].fillna('NaN')



for idx,row in ActivitySummary_DF[list_rename_column.values()].iterrows():
    check_dict_out = row.to_dict()
    print(row.to_dict())
    break
ActivitySummary_DF.dtypes
# MUST READ!!!!!!!! 
# to do:
# - add dict/csv to Dome Activity Summary

,label_subactivity,label_activity,MERGE_SubActivity-Activity,pic,remark,section
0,FALSE/Check,NaN,nan--FALSE/Check,BM,RTDC Check,"17"" 1/2"
1,MAKE UP BHA,MAKE UP BHA,MAKE UP BHA--MAKE UP BHA,BM,RTDC Check,"17"" 1/2"
2,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,BM,RTDC Check,"17"" 1/2"
3,Circulation,TRIP IN,TRIP IN--Circulation,BM,RTDC Check,"17"" 1/2"
4,Wash Up/Down,TRIP IN,TRIP IN--Wash Up/Down,BM,RTDC Check,"17"" 1/2"

{'wid': 170, 'date': '2022-02-14', 'time_start': '2022-02-14 00:00:00', 'time_end': '2022-02-14 12:00:03', 'duration_minutes': 719.97, 'hole_depth': 718.02, 'bit_depth': 640.8, 'meterage_drilling': 0.0, 'rotate_drilling_time': 0.0, 'slide_drilling_time': 0.0, 'reaming_time': 0.0, 'connection_time': 0.0, 'on_bottom_hours': 0.0, 'stand_duration': 0.0, 'label_subactivity': 'FALSE/Check', 'label_activity': 'NaN', 'stand_meterage_drilling': 0.0, 'stand_durationx': 0.0, 'stand_on_bottom': 0.0, 'pic': 'BM', 'remark': 'RTDC Check', 'section': '17" 1/2', 'stand_group': nan}

date                           object
time_start                     object
time_end                       object
date_time                      object
duration_minutes              float64
hole_depth                    float64
bit_depth                     float64
meterage_drilling             float64
rotate_drilling_time          float64
slide_drilling_time           float64
reaming_time                  float64
connection_time               float64
on_bottom_hours               float64
stand_duration                float64
label_subactivity              string
label_activity                 string
MERGE_SubActivity-Activity     string
pic                            string
remark                         string
section                        string
stand_meterage_drilling       float64
stand_durationx               float64
stand_on_bottom               float64
stand_group                    object
wid                             int64
dtype: object

In [266]:
from importlib import reload
from Streamlit_App import Activity
reload(Activity)
def UploadActivitySummary(ActivitySummary_DF, wid):
    list_rename_column = {
    'wid':'wid',
    'Date':'date',
    'Start Time':'time_start',
    'End Time':'time_end',
    'Duration (Minutes)':'duration_minutes',
    'Hole Depth (Max)':'hole_depth',
    'Bit Depth(mean)':'bit_depth',
    'Drilling Meterage (m)':'meterage_drilling',
    'Rotate Drilling (minutes)':'rotate_drilling_time',
    'Slide Drilling (minutes)':'slide_drilling_time',
    'Reaming (minutes)':'reaming_time',
    'Connection (minutes)':'connection_time',
    'On Bottom state (Hours)':'on_bottom_hours',
    'Stand Duration':'stand_duration',
    'SUB-ACTIVITY':'label_subactivity',
    'ACTIVITY':'label_activity',
    'Total Stand Drilling Meterage (m)':'stand_meterage_drilling',
    'Total Stand Duration (hrs)':'stand_durationx',
    'Total On Bottom Duration (hrs)':'stand_on_bottom',
    "PIC":"pic",
    "Section":"section",
    "Remarks":"remark",
    'Stand Group_Pred':'stand_group',
    }

    ActivitySummary_DF.rename(columns = list_rename_column, inplace = True)
    ActivitySummary_DF['wid'] = wid



    ActivitySummary_DF['time_start'] = pd.to_datetime(ActivitySummary_DF['date'].str.split(' ', expand=True)[0] + ' ' + ActivitySummary_DF['time_start']).dt.strftime('%Y-%m-%d %H:%M:%S')
    ActivitySummary_DF['time_end'] = pd.to_datetime(ActivitySummary_DF['date'].str.split(' ', expand=True)[0] + ' ' + ActivitySummary_DF['time_end']).dt.strftime('%Y-%m-%d %H:%M:%S')

    ActivitySummary_DF['date'] = ActivitySummary_DF['date'].astype('datetime64').dt.strftime('%Y-%m-%d')


    list_float64_col = ["duration_minutes",
    "hole_depth",
    "bit_depth",
    "meterage_drilling",
    "rotate_drilling_time",
    "slide_drilling_time",
    "reaming_time",
    "connection_time",
    "on_bottom_hours",
    "stand_duration",
    "stand_durationx",

    ]

    list_string_col = ["label_subactivity",
    "label_activity",
    "MERGE_SubActivity-Activity",
    "pic",
    "remark",
    "section",
    ]


    for string_col in list_string_col:
        ActivitySummary_DF[string_col] = ActivitySummary_DF[string_col].astype('string')

    for float64_col in list_float64_col:
        ActivitySummary_DF[float64_col] = ActivitySummary_DF[float64_col].astype('float64')

    ActivitySummary_DF[['label_subactivity','label_activity']] = ActivitySummary_DF[['label_subactivity','label_activity']].fillna('NaN')
    ActivitySummary_DF['stand_group'] = ActivitySummary_DF['stand_group'].fillna(999)

    list_dict_out = []

    for idx,row in ActivitySummary_DF[list_rename_column.values()].iterrows():
        list_dict_out.append(row.to_dict())

    return list_dict_out
    

AddRowAPI = "https://pdumitradome.id/dome_api/rtdc/ActivitySummary/create"
ActivitySummary_DF = pd.read_csv("RealTime_Test\\KS ORKA_SMP AAE-08_ActivitySummary_FinalTest.csv", sep=",")
ActivitySummary_DF['PIC'] = 'BM'
ActivitySummary_DF['Section'] = '17 1/2'
ActivitySummary_DF['Remarks'] = 'test'


list_dict_out = UploadActivitySummary(ActivitySummary_DF, 170)
# IO_Data.DomeAddData(check_dict_out, table_type="Activity Summary")
for dict_out in list_dict_out:
    IO_Data.DomeAddData(dict_out, table_type="Activity Summary")

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [ ]:
{'wid': 175,
 'date': '2022-02-14',
 'time_start': '2022-02-14 00:00:00',
 'time_end': '2022-02-14 12:00:03',
 'duration_minutes': 719.97,
 'hole_depth': 718.02,
 'bit_depth': 640.8,
 'meterage_drilling': 0.0,
 'rotate_drilling_time': 0.0,
 'slide_drilling_time': 0.0,
 'reaming_time': 0.0,
 'connection_time': 0.0,
 'on_bottom_hours': 0.0,
 'stand_duration': 0.0,
 'label_subactivity': 999.0,
 'label_activity': 999.0,
 'stand_meterage_drilling': 0.0,
 'stand_durationx': 0.0,
 'stand_on_bottom': 0.0,
 'pic': 0.0,
 'section': 0.0,
 'remark': 'test',
 'stand_group': 999}

In [274]:
reload(IO_Data)
list_rename_column = {
    'wid':'wid',
    'Date':'date',
    'Start Time':'time_start',
    'End Time':'time_end',
    'Duration (Minutes)':'duration_minutes',
    'Hole Depth (Max)':'hole_depth',
    'Bit Depth(mean)':'bit_depth',
    'Drilling Meterage (m)':'meterage_drilling',
    'Rotate Drilling (minutes)':'rotate_drilling_time',
    'Slide Drilling (minutes)':'slide_drilling_time',
    'Reaming (minutes)':'reaming_time',
    'Connection (minutes)':'connection_time',
    'On Bottom state (Hours)':'on_bottom_hours',
    'Stand Duration':'stand_duration',
    'SUB-ACTIVITY':'label_subactivity',
    'ACTIVITY':'label_activity',
    'Total Stand Drilling Meterage (m)':'stand_meterage_drilling',
    'Total Stand Duration (hrs)':'stand_durationx',
    'Total On Bottom Duration (hrs)':'stand_on_bottom',
    "PIC":"pic",
    "Section":"section",
    "Remarks":"remark",
    'Stand Group_Pred':'stand_group',
    }
from Streamlit_App import IO_Data

start_date_time = "2022-01-01 23:59:59"
end_date_time = "2022-04-1 23:59:59"
wid = 170


print("Summary get Data")
# IO_Data. DomeAddData(check_dict_out, table_type="Activity Summary")
print("Summary get Data")

out_df = IO_Data.DomeGetData(wid, start_date_time, end_date_time, table_type="Activity Summary")

# out_df.rename(columns={y: x for x, y in list_rename_column.items()}, inplace=True)
out_df

Summary get Data
Summary get Data

,Date,Start Time,End Time,Duration (Minutes),Hole Depth (Max),Bit Depth(mean),Drilling Meterage (m),Rotate Drilling (minutes),Slide Drilling (minutes),Reaming (minutes),...,Stand Duration,SUB-ACTIVITY,ACTIVITY,Total Stand Drilling Meterage (m),Total Stand Duration (hrs),Total On Bottom Duration (hrs),PIC,Section,Remarks,Stand Group_Pred
0,2022-02-14,2022-02-14 00:00:00,2022-02-14 12:00:03,719.97,718.02,640.8,0,0,0,0,...,0,FALSE/Check,NaN,0,0,0,BM,17 1/2,test,999
1,2022-02-14,2022-02-14 12:00:03,2022-02-14 15:00:01,179.88,747.38,732.21,0,0,0,0,...,0,MAKE UP BHA,MAKE UP BHA,0,0,0,BM,17 1/2,test,999
2,2022-02-14,2022-02-14 15:00:01,2022-02-14 15:09:11,9.08,749.55,748.48,0,0,0,0,...,0,Wash Up/Down,TRIP IN,0,0,0,BM,17 1/2,test,999
3,2022-02-14,2022-02-14 15:09:11,2022-02-14 15:09:21,0,749.57,749.57,0,0,0,0,...,0,Circulation,TRIP IN,0,0,0,BM,17 1/2,test,999
4,2022-02-14,2022-02-14 15:09:21,2022-02-14 15:09:36,0.17,749.61,749.6,0,0,0,0,...,0,Wash Up/Down,TRIP IN,0,0,0,BM,17 1/2,test,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2022-02-15,2022-02-15 23:27:27,2022-02-15 23:31:02,3.5,1080,1072.1,0,0,0,0,...,0,Wash Up/Down,DRILLING FORMATION,0,0,0,BM,17 1/2,test,Stand Group - 31
356,2022-02-15,2022-02-15 23:31:02,2022-02-15 23:45:47,14.67,1082,1081.08,2,0,14.67,0,...,0,Slide Drilling,DRILLING FORMATION,0,0,0,BM,17 1/2,test,Stand Group - 31
357,2022-02-15,2022-02-15 23:45:47,2022-02-15 23:46:52,0.91,1082,1080.79,0,0,0,0,...,0,Wash Up/Down,DRILLING FORMATION,0,0,0,BM,17 1/2,test,Stand Group - 31
358,2022-02-15,2022-02-15 23:46:52,2022-02-15 23:48:22,1.42,1082,1081.28,0,0,0,1.42,...,0,Reaming,DRILLING FORMATION,0,0,0,BM,17 1/2,test,Stand Group - 31
359,2022-02-15,2022-02-15 23:48:22,2022-02-15 00:09:33,21.1,1085.98,1083.97,3.98,21.1,0,0,...,0,Rotary Drilling,DRILLING FORMATION,0,0,0,BM,17 1/2,test,Stand Group - 31

In [300]:
out_df.dtypes

Date                                 object
Start Time                           object
End Time                             object
Duration (Minutes)                   object
Hole Depth (Max)                     object
Bit Depth(mean)                      object
Drilling Meterage (m)                object
Rotate Drilling (minutes)            object
Slide Drilling (minutes)             object
Reaming (minutes)                    object
Connection (minutes)                 object
On Bottom state (Hours)              object
Stand Duration                       object
SUB-ACTIVITY                         object
ACTIVITY                             object
Total Stand Drilling Meterage (m)    object
Total Stand Duration (hrs)           object
Total On Bottom Duration (hrs)       object
PIC                                  object
Section                              object
Remarks                              object
Stand Group_Pred                     object
dtype: object

In [294]:
reload(IO_Data)
IO_Data.DomeDelete(170, '2022-02-15 23:48:22', table_type="Activity Summary")

https://pdumitradome.id/dome_api/rtdc/ActivitySummary/delete
delete Activity Summary data success

In [301]:
Summary_Used_Columns = {
                        "STATUS":"STATUS",
                        "date":"Date",
                        "Time_start":"Start Time",
                        "Time_end":"End Time",
                        "LABEL_Activity":"ACTIVITY",
                        "LABEL_SubActivity":"SUB-ACTIVITY",
                        "Duration(minutes)": "Duration (Minutes)",
                        "Hole Depth(max)":"Hole Depth (Max)",
                        "Bit Depth(mean)":"Bit Depth(mean)",
                        "Meterage(m)(Drilling)": "Drilling Meterage (m)",
                        "RotateDrilling":"Rotate Drilling (minutes)",
                        "Slide Drilling": "Slide Drilling (minutes)",
                        "ReamingTime": "Reaming (minutes)",
                        "ConnectionTime":"Connection (minutes)",
                        "On Bottom Hours":"On Bottom state (Hours)",
                        "Stand Group_Pred":"Stand Group_Pred", #to be check
                        "Stand Duration":"Stand Duration",
                        "Stand Meterage (m) (Drilling)":"Total Stand Drilling Meterage (m)",
                        "Stand Stand Duration (hrs)":"Total Stand Duration (hrs)",
                        "Stand On Bottom Hours": "Total On Bottom Duration (hrs)",
                        "pic":"PIC",
                        "remarks":"Remarks",
                        "section":"Section",
                    }
Summary_Used_Columns.values()

dict_values(['STATUS', 'Date', 'Start Time', 'End Time', 'ACTIVITY', 'SUB-ACTIVITY', 'Duration (Minutes)', 'Hole Depth (Max)', 'Bit Depth(mean)', 'Drilling Meterage (m)', 'Rotate Drilling (minutes)', 'Slide Drilling (minutes)', 'Reaming (minutes)', 'Connection (minutes)', 'On Bottom state (Hours)', 'Stand Group_Pred', 'Stand Duration', 'Total Stand Drilling Meterage (m)', 'Total Stand Duration (hrs)', 'Total On Bottom Duration (hrs)', 'PIC', 'Remarks', 'Section'])

In [278]:
# Index(['Date', 'Start Time', 'End Time', 'Duration (Minutes)',
#        'Hole Depth (Max)', 'Bit Depth(mean)', 'Drilling Meterage (m)',
#        'Rotate Drilling (minutes)', 'Slide Drilling (minutes)',
#        'Reaming (minutes)', 'Connection (minutes)', 'On Bottom state (Hours)',
#        'Stand Duration', 'SUB-ACTIVITY', 'ACTIVITY',
#        'Total Stand Drilling Meterage (m)', 'Total Stand Duration (hrs)',
#        'Total On Bottom Duration (hrs)', 'PIC', 'Section', 'Remarks',
#        'Stand Group_Pred'],
#       dtype='object')
# Index(['STATUS', 'Date', 'Start Time', 'End Time', 'ACTIVITY', 'SUB-ACTIVITY',
#        'Duration (Minutes)', 'Hole Depth (Max)', 'Bit Depth(mean)',
#        'Drilling Meterage (m)', 'Rotate Drilling (minutes)',
#        'Slide Drilling (minutes)', 'Reaming (minutes)', 'Connection (minutes)',
#        'On Bottom state (Hours)', 'Total Stand Drilling Meterage (m)',
#        'Total Stand Duration (hrs)', 'Total On Bottom Duration (hrs)', 'PIC',
#        'Remarks', 'Section'],
#       dtype='object')



for i in ['Date', 'Start Time', 'End Time', 'Duration (Minutes)',
       'Hole Depth (Max)', 'Bit Depth(mean)', 'Drilling Meterage (m)',
       'Rotate Drilling (minutes)', 'Slide Drilling (minutes)',
       'Reaming (minutes)', 'Connection (minutes)', 'On Bottom state (Hours)',
       'Stand Duration', 'SUB-ACTIVITY', 'ACTIVITY',
       'Total Stand Drilling Meterage (m)', 'Total Stand Duration (hrs)',
       'Total On Bottom Duration (hrs)', 'PIC', 'Section', 'Remarks',
       'Stand Group_Pred']:
       print(i)

Date
Start Time
End Time
Duration (Minutes)
Hole Depth (Max)
Bit Depth(mean)
Drilling Meterage (m)
Rotate Drilling (minutes)
Slide Drilling (minutes)
Reaming (minutes)
Connection (minutes)
On Bottom state (Hours)
Stand Duration
SUB-ACTIVITY
ACTIVITY
Total Stand Drilling Meterage (m)
Total Stand Duration (hrs)
Total On Bottom Duration (hrs)
PIC
Section
Remarks
Stand Group_Pred

In [279]:
for i in ['STATUS', 'Date', 'Start Time', 'End Time', 'ACTIVITY', 'SUB-ACTIVITY',
       'Duration (Minutes)', 'Hole Depth (Max)', 'Bit Depth(mean)',
       'Drilling Meterage (m)', 'Rotate Drilling (minutes)',
       'Slide Drilling (minutes)', 'Reaming (minutes)', 'Connection (minutes)',
       'On Bottom state (Hours)', 'Total Stand Drilling Meterage (m)',
       'Total Stand Duration (hrs)', 'Total On Bottom Duration (hrs)', 'PIC',
       'Remarks', 'Section']:
       print(i)

STATUS
Date
Start Time
End Time
ACTIVITY
SUB-ACTIVITY
Duration (Minutes)
Hole Depth (Max)
Bit Depth(mean)
Drilling Meterage (m)
Rotate Drilling (minutes)
Slide Drilling (minutes)
Reaming (minutes)
Connection (minutes)
On Bottom state (Hours)
Total Stand Drilling Meterage (m)
Total Stand Duration (hrs)
Total On Bottom Duration (hrs)
PIC
Remarks
Section

In [283]:
{
    'duration_minutes': 'Duration (Minutes)',
                        'hole_depth': 'Hole Depth (Max)',
                        'bit_depth': 'Bit Depth(mean)',
                        'meterage_drilling': 'Drilling Meterage (m)',
                        'rotate_drilling_time': 'Rotate Drilling (minutes)',
                        'slide_drilling_time': 'Slide Drilling (minutes)',
                        'reaming_time': 'Reaming (minutes)',
                        'connection_time': 'Connection (minutes)',
                        'on_bottom_hours': 'On Bottom state (Hours)',
                        'stand_duration': 'Stand Duration',
                        'stand_meterage_drilling':'Total Stand Drilling Meterage (m)',
                        'stand_durationx': 'Total Stand Duration (hrs)',
                        'stand_on_bottom': 'Total On Bottom Duration (hrs)',
}.values()

dict_values(['Duration (Minutes)', 'Hole Depth (Max)', 'Bit Depth(mean)', 'Drilling Meterage (m)', 'Rotate Drilling (minutes)', 'Slide Drilling (minutes)', 'Reaming (minutes)', 'Connection (minutes)', 'On Bottom state (Hours)', 'Stand Duration', 'Total Stand Drilling Meterage (m)', 'Total Stand Duration (hrs)', 'Total On Bottom Duration (hrs)'])

In [293]:
out_df['Start Time'].tail(5).to_list()[0]

'2022-02-15 23:27:27'

In [1]:
TranslateSubActivity = {
                    1:"Wash Up/Down",
                    2:"Reaming",
                    3:"Moving",
                    4:"Circulation",
                    5:"Connection",
                    6:"Stationary",
                    7:"Rotary Drilling",
                    8:"Slide Drilling",
                    9:"Look and define",
                    10:'CEMENTING JOB',
                    11:'CONNECTION',
                    12:'LAY DOWN BHA',
                    13:'MAKE UP BHA',
                    14:'NPT',
                    15:'N/D BOP',
                    16:'N/U BOP',
                    17:'RUNNING CASING IN',
                    18:'STATIONARY',
                    19:'STUCK PIPE',
                    20:'WAIT ON CEMENT',
                    21:'RIG REPAIR',
                    22:'nan'

    }

TranslateSubActivity

{1: 'Wash Up/Down',
 2: 'Reaming',
 3: 'Moving',
 4: 'Circulation',
 5: 'Connection',
 6: 'Stationary',
 7: 'Rotary Drilling',
 8: 'Slide Drilling',
 9: 'Look and define',
 10: 'CEMENTING JOB',
 11: 'CONNECTION',
 12: 'LAY DOWN BHA',
 13: 'MAKE UP BHA',
 14: 'NPT',
 15: 'N/D BOP',
 16: 'N/U BOP',
 17: 'RUNNING CASING IN',
 18: 'STATIONARY',
 19: 'STUCK PIPE',
 20: 'WAIT ON CEMENT',
 21: 'RIG REPAIR',
 22: 'nan'}

In [2]:
{y: x for x, y in TranslateSubActivity.items()}

{'Wash Up/Down': 1,
 'Reaming': 2,
 'Moving': 3,
 'Circulation': 4,
 'Connection': 5,
 'Stationary': 6,
 'Rotary Drilling': 7,
 'Slide Drilling': 8,
 'Look and define': 9,
 'CEMENTING JOB': 10,
 'CONNECTION': 11,
 'LAY DOWN BHA': 12,
 'MAKE UP BHA': 13,
 'NPT': 14,
 'N/D BOP': 15,
 'N/U BOP': 16,
 'RUNNING CASING IN': 17,
 'STATIONARY': 18,
 'STUCK PIPE': 19,
 'WAIT ON CEMENT': 20,
 'RIG REPAIR': 21,
 'nan': 22}

In [ ]:
{
    'Wash Up/Down': 'darkkhaki',
    'Reaming': 'darkmagenta',
    'Moving': 'darkolivegreen',
    'Circulation': 'darkorange',
    'Connection': 'darkorchid',
    'Stationary': 'darkred',
    'Rotary Drilling': 'darksalmon',
    'Slide Drilling': 'darkseagreen',
    'Look and define': 'darkslateblue',
    'CEMENTING JOB': 'darkslategray',
    'CONNECTION': 'darkturquoise',
    'LAY DOWN BHA': 'darkviolet',
    'MAKE UP BHA': 'deeppink',
    'NPT': 'deepskyblue',
    'N/D BOP': 'darkcyan',
    'N/U BOP': 'hotpink',
    'RUNNING CASING IN': 'lightblue',
    'STATIONARY': 'lightred',
    'STUCK PIPE': 'lightgreen',
    'WAIT ON CEMENT': 'lightseagreen',
    'RIG REPAIR': 'mediumpurple',
    'nan': 'orange'
}




'darkmagenta'


'darkorchid'
'darkred'

'darksalmon'

## New API

https://pdumitradome.id/dome_api/rtdc/get_Last_ActSum
#Request
{
	"wid":260,
	"section":"ALL",
	"DateTime_Before":"2023-09-19 05:19:23"
}
#Response
{
    "result": [
        {
            "date": "2023-08-04",
            "time_start": "2023-08-04 12:00:05",
            "time_end": "2023-08-04 14:07:40",
            "duration_minutes": "125.58",
            "hole_depth": "55",
            "bit_depth": "29.0914",
            "meterage_drilling": "55.99",
            "rotate_drilling_time": "0",
            "slide_drilling_time": "0",
            "reaming_time": "0",
            "connection_time": "6",
            "on_bottom_hours": "0",
            "stand_duration": "0",
            "label_subactivity": "Connection",
            "label_activity": "DRILLING FORMATION",
            "stand_meterage_drilling": "0.0",
            "stand_durationx": "58",
            "stand_on_bottom": "0",
            "pic": "Sonny",
            "section": "26\"",
            "remark": "",
            "stand_group": ""
        }
    ],
    "status": 200
}

https://pdumitradome.id/dome_api/rtdc/get_Last_ActLog
#Request
{
	"wid":260,
	"section":"ALL",
	"DateTime_Before":"ALL"
}
#Response
{
    "result": [
        {
            "id": "64",
            "dt": "2029-09-08 17:00:00",
            "date": "2029-09-08",
            "time": "17:00:00",
            "activity": "RUNNING CASING IN",
            "in_slip_threshold": "58",
            "remarks": "RUNNING CASING",
            "pic": "Adi R",
            "section": "12-1/4\""
        }
    ],
    "status": 200
}

https://pdumitradome.id/dome_api/rtdc/get_Last_LabelStand
#Request
{
	"wid":260,
	"section":"ALL",
	"DateTime_Before":"2023-09-19 05:19:23"
}
#Response
{
    "result": {
        "date": "2023-09-19",
        "time_start": "2023-09-19 00:17:03",
        "time_end": "2023-09-19 00:19:58",
        "label_subactivity": "Wash Up/Down",
        "label_activity": "DRILLING FORMATION",
        "pic": "AF",
        "section": "9-7/8\"",
        "stand_group": "Drilling Stand-2"
    },
    "status": 200
}

https://pdumitradome.id/dome_api/rtdc/get_realtime_interval/260
#Request
{
	"wid":260,
	"section":"ALL",
	"DateTime_Before":"2023-09-19 05:19:23"
}
#Response
{
    "data": {
        "Start": "2023-08-03 07:18:25",
        "End": "2023-09-19 12:30:52"
    },
    "status": 200
}

In [2]:
import pandas as pd 
import requests
import json
from IPython.display import display as display_DF

RequestDict = {
"wid":243,
"section":"26",
"DateTime_Before":'2023-04-10 05:25:35'
}

DomeGetLastStandAPI = "https://pdumitradome.id/dome_api/rtdc/get_Last_LabelStand"
# DomeGetLastStandAPI = "http://khansadev.xyz/dome_api/rtdc/ActivitySummary/create"
json_queries = json.dumps(
    RequestDict,
    indent = 4
)

response = (
    requests.post(
        DomeGetLastStandAPI, data=json_queries 
    )
)
response.json()['result']

{'result': {'date': '2023-04-09',
  'time_start': '2023-04-09 23:00:05',
  'time_end': '2023-04-09 23:04:15',
  'label_subactivity': 'Rotary Drilling',
  'label_activity': 'DRILLING FORMATION',
  'pic': 'MIH',
  'section': '26"',
  'stand_group': 'Drilling Stand-1'},
 'status': 200}

In [12]:
RequestDict = {
"wid":243,
"section":"17",
"DateTime_Before":'2020-04-10 05:25:35'
}

DomeGetLastStandAPI = "https://pdumitradome.id/dome_api/rtdc/get_Last_LabelStand"
# DomeGetLastStandAPI = "http://khansadev.xyz/dome_api/rtdc/ActivitySummary/create"
json_queries = json.dumps(
    RequestDict,
    indent = 4
)

response = (
    requests.post(
        DomeGetLastStandAPI, data=json_queries 
    )
)
response.json()['result']['stand_group'].split('-')[-1]

TypeError: 'NoneType' object is not subscriptable

In [11]:
int(response.json()['result']['stand_group'].split('-')[-1])

1

In [15]:
def DomeGetLastStandNumber(WellInfoDict, SectionSize, BeforeDate):
    RequestDict = {
	"wid":243,
	"section":SectionSize,
	"DateTime_Before":BeforeDate
    }

    DomeGetLastStandAPI = "https://pdumitradome.id/dome_api/rtdc/get_Last_LabelStand"
    # DomeGetLastStandAPI = "http://khansadev.xyz/dome_api/rtdc/ActivitySummary/create"
    json_queries = json.dumps(
        RequestDict,
        indent = 4
    )

    response = (
        requests.post(
            DomeGetLastStandAPI, data=json_queries 
        )
    )
    if response.json()['result'] != None:
        return int(response.json()['result']['stand_group'].split('-')[-1])
    else:
        return None

In [18]:
DomeGetLastStandNumber(None, "12", '2020-04-10 05:25:35')