In [6]:
import pandas as pd 
from Streamlit_App import Activity

In [166]:
def GetSubActivity_DF_v2(Activity_DF):
    logic_status = 0
    Activity_DF["SubActivity"] = "FALSE/Check"
    Activity_DF["logic_status"] = logic_status


    idx_logic_activity = Activity_DF["Activity"].isin(["DRILLING FORMATION", 
                                            'CIRCULATE HOLE CLEANING',
                                            'CONNECTION',
                                            'DRILL OUT CEMENT',
                                        ])
    # print((Activity_DF.dtypes))

    idx_logic = idx_logic_activity & ((Activity_DF['woba']>0) & (Activity_DF['rpm']>10) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
    SubActivity_Label = "Rotary Drilling"
    Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic, "logic_status"] = logic_status
    # 1

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic, "logic_status"] = logic_status

    idx_logic = idx_logic_activity &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']>0) & (Activity_DF['rpm']<10) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
    SubActivity_Label = "Slide Drilling"
    Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
    # 2

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic, "logic_status"] = logic_status
    
    idx_logic = idx_logic_activity &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']==0) & (Activity_DF['rpm']>10) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
    SubActivity_Label = "Reaming"
    Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #3

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic, "logic_status"] = logic_status

    idx_logic = idx_logic_activity &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']==0) & (Activity_DF['rpm']==0) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
    SubActivity_Label = "Wash Up/Down"
    Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #4

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic, "logic_status"] = logic_status


    idx_logic = idx_logic_activity &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']==0) & (Activity_DF['rpm']==0) & (Activity_DF['stppress']<50))
    SubActivity_Label = "Connection"
    Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #5

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic, "logic_status"] = logic_status

    # idx_logic = idx_logic_activity & ((Activity_DF["SubActivity"] == "FALSE/Check") & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
    idx_logic = idx_logic & (Activity_DF['hklda']>Activity_DF['Hookload Treshold'])
    SubActivity_Label="Look and define"
    Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #6

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic, "logic_status"] = logic_status
    #7


    # ############################
    idx_logic_activity_2 = Activity_DF["Activity"].isin([
                                            'NPT',
                                            'N/D BOP',
                                            'N/U BOP',
                                            'OTHER',
                                            'RUNNING CASING IN',
                                            'STATIONARY',
                                            'STUCK PIPE',
                                            'TRIP IN',
                                            'TRIP OUT',
                                            'WAIT ON CEMENT',
                                            'LAY DOWN BHA',
                                            'MAKE UP BHA',
                                            'WIPER TRIP'
                                        ]
                                        )
    Activity_DF['isBitDepthMoving'] = Activity_DF['bitdepth'].shift(periods=-1) != Activity_DF['bitdepth']

    # Activity_DF["LABEL_SubActivity"] = "Check"
    idx_logic_2 = idx_logic_activity_2 & ((Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['rpm']==0) & (Activity_DF['mudflowin']>10))
    SubActivity_Label = "Wash Up/Down"
    Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    # DisplayDF(Activity_DF.loc[idx_logic_2, :])
    #

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
    #8
    
    idx_logic_2 = idx_logic_activity_2 &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['rpm']>10) & (Activity_DF['stppress']>100) & (Activity_DF['mudflowin']>10))
    SubActivity_Label = "Reaming"
    Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
    #9

    idx_logic_2 = idx_logic_activity_2 &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['rpm']<10) & (Activity_DF['stppress']<100) & (Activity_DF['mudflowin']<50))
    SubActivity_Label = "Moving"
    Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
    #10

    idx_logic_2 = idx_logic_activity_2 &(Activity_DF["SubActivity"] == "FALSE/Check") & (~(Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['mudflowin']>10))
    SubActivity_Label = "Circulation"
    Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
    #11

    idx_logic_2 = idx_logic_activity_2 &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['mudflowin']<10) & (Activity_DF['rpm']<10) & (Activity_DF['hklda']<Activity_DF['Hookload Treshold']))
    SubActivity_Label = "Connection"
    Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
    #12

    idx_logic_2 = idx_logic_activity_2 &(Activity_DF["SubActivity"] == "FALSE/Check") & ((~Activity_DF['isBitDepthMoving']) & (Activity_DF['mudflowin']<10) & (Activity_DF['rpm']<10) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
    SubActivity_Label = "Stationary"
    Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
    #13

    ## force to be same as activity
    idx_logic_3 = Activity_DF["Activity"].isin([
                            'CEMENTING JOB',
                            'CONNECTION',
                            'LAY DOWN BHA',
                            'MAKE UP BHA',
                            'NPT',
                            'N/D BOP',
                            'N/U BOP',
                            'RUNNING CASING IN',
                            'STATIONARY',
                            'STUCK PIPE',
                            'WAIT ON CEMENT',
                            'RIG REPAIR',
    ])
    Activity_DF.loc[idx_logic_3, "SubActivity"] = Activity_DF.loc[idx_logic_3, "Activity"]
    #

    logic_status = logic_status + 1
    Activity_DF.loc[idx_logic_3, "logic_status"] = logic_status
    #14

    # print(Activity_DF.columns)

    return Activity_DF
# SubActivity_DF['Activity'] =

In [168]:
SubActivity_DF = pd.read_excel("BM_test\\IrsyadTest.xlsx", sheet_name='Sheet1')
SubActivity_DF.rename(columns = {'Activity_Actual':'Activity',
                                    'In Slip Value': 'Hookload Treshold'}, inplace = True)

# SubActivity_DF
Result_DF = GetSubActivity_DF_v2(SubActivity_DF)
Result_DF['IsCorrect'] = True
Result_DF.loc[Result_DF['SubActivity_Actual'] != Result_DF['SubActivity'], 'IsCorrect'] = False
num_ext = num_ext + 1
Result_DF.to_excel('BM_test\\IrsyadTest_Output' + str(num_ext) + '.xlsx')

Index(['date', 'time', 'dt', 'md', 'bitdepth', 'blockpos', 'hklda', 'rpm',
       'stppress', 'mudflowin', 'rop', 'woba', 'torqa', 'SubActivity_Actual',
       'Activity', 'Hookload Treshold', 'SubActivity', 'logic_status',
       'isBitDepthMoving'],
      dtype='object')

In [169]:
import numpy as np
Result_DF = GetSubActivity_DF_v2(SubActivity_DF)
Result_DF['IsCorrect'] = True
Result_DF.loc[Result_DF['SubActivity_Actual'] != Result_DF['SubActivity'], 'IsCorrect'] = False
DisplayDF(SubActivity_DF[Result_DF['IsCorrect'] == False])

Result_DF_x = Result_DF.copy()
Result_DF_x['out'] = Result_DF_x['SubActivity_Actual'] + Result_DF_x['Activity'] + Result_DF_x['SubActivity']

# SubActivity_DF[Result_DF['IsCorrect'] == False]
# Result_DF['out'] = Result_DF['SubActivity_Actual'] + Result_DF['Activity'] + Result_DF['SubActivity']
print(Result_DF_x.loc[Result_DF_x['IsCorrect'] == False,'out'].unique())

RANGE_ROW = np.arange(7922,7929,1).tolist()
Activity_DF = SubActivity_DF.iloc[RANGE_ROW]

DisplayDF(SubActivity_DF.iloc[RANGE_ROW,:])

DisplayDF(GetSubActivity_DF_v2(SubActivity_DF.iloc[RANGE_ROW,:]))

Index(['date', 'time', 'dt', 'md', 'bitdepth', 'blockpos', 'hklda', 'rpm',
       'stppress', 'mudflowin', 'rop', 'woba', 'torqa', 'SubActivity_Actual',
       'Activity', 'Hookload Treshold', 'SubActivity', 'logic_status',
       'isBitDepthMoving', 'IsCorrect'],
      dtype='object')

Empty DataFrame
Columns: [date, time, dt, md, bitdepth, blockpos, hklda, rpm, stppress, mudflowin, rop, woba, torqa, SubActivity_Actual, Activity, Hookload Treshold, SubActivity, logic_status, isBitDepthMoving, IsCorrect]
Index: []

[]

,date,time,dt,md,bitdepth,blockpos,hklda,rpm,stppress,mudflowin,rop,woba,torqa,SubActivity_Actual,Activity,Hookload Treshold,SubActivity,logic_status,isBitDepthMoving,IsCorrect
7922,2022-02-21,11:10:50,2022-02-21 11:10:50,489.37,489.14,1.29,93.47,0,736.96,599.09,8.63,0.80,1.07,Slide Drilling,DRILL OUT CEMENT,30.5,Slide Drilling,3,True,True
7923,2022-02-21,11:10:55,2022-02-21 11:10:55,489.37,489.33,1.10,93.93,0,457.62,489.23,8.63,4.35,1.05,Slide Drilling,DRILL OUT CEMENT,30.5,Slide Drilling,3,True,True
7924,2022-02-21,11:11:00,2022-02-21 11:11:00,489.37,489.35,1.08,93.76,0,147.47,408.04,8.63,4.51,1.05,Slide Drilling,DRILL OUT CEMENT,30.5,Slide Drilling,3,True,True
7925,2022-02-21,11:11:05,2022-02-21 11:11:05,489.37,489.36,1.07,74.92,0,8.93,131.69,8.63,23.36,1.03,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,True,True
7926,2022-02-21,11:11:10,2022-02-21 11:11:10,489.37,489.37,1.06,40.65,0,0.00,73.69,8.63,57.62,0.46,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,False,True
7927,2022-02-21,11:11:15,2022-02-21 11:11:15,489.37,489.37,1.06,31.05,0,0.00,24.56,8.63,67.22,0.36,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,False,True
7928,2022-02-21,11:11:20,2022-02-21 11:11:20,489.37,489.37,1.06,30.20,0,0.00,0.00,8.63,68.07,0.37,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,False,True

Index(['date', 'time', 'dt', 'md', 'bitdepth', 'blockpos', 'hklda', 'rpm',
       'stppress', 'mudflowin', 'rop', 'woba', 'torqa', 'SubActivity_Actual',
       'Activity', 'Hookload Treshold', 'SubActivity', 'logic_status',
       'isBitDepthMoving', 'IsCorrect'],
      dtype='object')

C:\Users\irsya\AppData\Local\Temp/ipykernel_4772/373839314.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Activity_DF["SubActivity"] = "FALSE/Check"
C:\Users\irsya\AppData\Local\Temp/ipykernel_4772/373839314.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Activity_DF["logic_status"] = logic_status
C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\irsya\AppData\Local\Temp/ipykernel_4772/373839314.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Activity_DF['isBitDepthMoving'] = Activity_DF['bitdepth'].shift(periods=-1) != Activity_DF['bitdepth']
C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

,date,time,dt,md,bitdepth,blockpos,hklda,rpm,stppress,mudflowin,rop,woba,torqa,SubActivity_Actual,Activity,Hookload Treshold,SubActivity,logic_status,isBitDepthMoving,IsCorrect
7922,2022-02-21,11:10:50,2022-02-21 11:10:50,489.37,489.14,1.29,93.47,0,736.96,599.09,8.63,0.80,1.07,Slide Drilling,DRILL OUT CEMENT,30.5,Slide Drilling,3,True,True
7923,2022-02-21,11:10:55,2022-02-21 11:10:55,489.37,489.33,1.10,93.93,0,457.62,489.23,8.63,4.35,1.05,Slide Drilling,DRILL OUT CEMENT,30.5,Slide Drilling,3,True,True
7924,2022-02-21,11:11:00,2022-02-21 11:11:00,489.37,489.35,1.08,93.76,0,147.47,408.04,8.63,4.51,1.05,Slide Drilling,DRILL OUT CEMENT,30.5,Slide Drilling,3,True,True
7925,2022-02-21,11:11:05,2022-02-21 11:11:05,489.37,489.36,1.07,74.92,0,8.93,131.69,8.63,23.36,1.03,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,True,True
7926,2022-02-21,11:11:10,2022-02-21 11:11:10,489.37,489.37,1.06,40.65,0,0.00,73.69,8.63,57.62,0.46,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,False,True
7927,2022-02-21,11:11:15,2022-02-21 11:11:15,489.37,489.37,1.06,31.05,0,0.00,24.56,8.63,67.22,0.36,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,False,True
7928,2022-02-21,11:11:20,2022-02-21 11:11:20,489.37,489.37,1.06,30.20,0,0.00,0.00,8.63,68.07,0.37,FALSE/Check,DRILL OUT CEMENT,30.5,FALSE/Check,0,True,True

In [224]:
from IPython.display import display as DisplayDF

logic_status = 0
Activity_DF["SubActivity"] = "FALSE/Check"
Activity_DF["logic_status"] = logic_status


idx_logic_Activity = Activity_DF["Activity"].isin(["DRILLING FORMATION", 
                                        'CIRCULATE HOLE CLEANING',
                                        'CONNECTION',
                                        'DRILL OUT CEMENT',
                                    ])
# print((Activity_DF.dtypes))

idx_logic = idx_logic_Activity & ((Activity_DF['woba']>0) & (Activity_DF['rpm']>10) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
SubActivity_Label = "Rotary Drilling"
Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label

#

logic_status = logic_status + 1
Activity_DF.loc[idx_logic, "logic_status"] = logic_status
DisplayDF(Activity_DF.loc[idx_logic,:])
# 1

logic_status = logic_status + 1
Activity_DF.loc[idx_logic, "logic_status"] = logic_status

idx_logic = idx_logic_Activity & (Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']>0) & (Activity_DF['rpm']<10) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
SubActivity_Label = "Slide Drilling"
Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic,:])
# 2

logic_status = logic_status + 1
Activity_DF.loc[idx_logic, "logic_status"] = logic_status

idx_logic = idx_logic_Activity &(Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']==0) & (Activity_DF['rpm']>10) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
SubActivity_Label = "Reaming"
Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic,:])
#3

logic_status = logic_status + 1
Activity_DF.loc[idx_logic, "logic_status"] = logic_status

idx_logic = idx_logic_Activity & (Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']==0) & (Activity_DF['rpm']==0) & (Activity_DF['stppress']>100) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
SubActivity_Label = "Wash Up/Down"
Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic,:])
#4

logic_status = logic_status + 1
Activity_DF.loc[idx_logic, "logic_status"] = logic_status


idx_logic = idx_logic_Activity & (Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['woba']==0) & (Activity_DF['rpm']==0) & (Activity_DF['stppress']<50))
SubActivity_Label="Look and define"
Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic,:])
#5

idx_logic = idx_logic & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
logic_status = logic_status + 1
Activity_DF.loc[idx_logic, "logic_status"] = logic_status

SubActivity_Label = "Connection"
Activity_DF.loc[idx_logic, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic,:])
#6

logic_status = logic_status + 1
Activity_DF.loc[idx_logic, "logic_status"] = logic_status
#7

SyntaxError: unmatched ')' (Temp/ipykernel_4772/1602753692.py, line 63)

In [138]:
logic_status = 7
idx_logic_2 = Activity_DF["Activity"].isin([
                                        'NPT',
                                        'N/D BOP',
                                        'N/U BOP',
                                        'OTHER',
                                        'RUNNING CASING IN',
                                        'STATIONARY',
                                        'STUCK PIPE',
                                        'TRIP IN',
                                        'TRIP OUT',
                                        'WAIT ON CEMENT',
                                        'LAY DOWN BHA',
                                        'MAKE UP BHA',
                                        'WIPER TRIP'
                                    ]
                                    )
Activity_DF['isBitDepthMoving'] = Activity_DF['bitdepth'].shift(periods=-1) != Activity_DF['bitdepth']

# Activity_DF["LABEL_SubActivity"] = "Check"
idx_logic_2 = idx_logic_2 & ((Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['rpm']==0) & (Activity_DF['mudflowin']>10))
SubActivity_Label = "Wash Up/Down"
Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic_2, :])
#

logic_status = logic_status + 1
Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
#8

idx_logic_2 = (Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['rpm']>10) & (Activity_DF['stppress']>100) & (Activity_DF['mudflowin']>10))
SubActivity_Label = "Reaming"
Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic_2, :])


logic_status = logic_status + 1
Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
#9

idx_logic_2 = (Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['rpm']<10) & (Activity_DF['stppress']<100) & (Activity_DF['mudflowin']<50))
SubActivity_Label = "Moving"
Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic_2, :])

logic_status = logic_status + 1
Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
#10

idx_logic_2 = (Activity_DF["SubActivity"] == "FALSE/Check") & (~(Activity_DF['isBitDepthMoving']) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']) & (Activity_DF['mudflowin']>10))
SubActivity_Label = "Circulation"
Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic_2, :])
#

logic_status = logic_status + 1
Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
#11

idx_logic_2 = (Activity_DF["SubActivity"] == "FALSE/Check") & ((Activity_DF['mudflowin']<10) & (Activity_DF['rpm']<10) & (Activity_DF['hklda']<Activity_DF['Hookload Treshold']))
SubActivity_Label = "Connection"
Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic_2, :])
#

logic_status = logic_status + 1
Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
#12

idx_logic_2 = (Activity_DF["SubActivity"] == "FALSE/Check") & ((~Activity_DF['isBitDepthMoving']) & (Activity_DF['mudflowin']<10) & (Activity_DF['rpm']<10) & (Activity_DF['hklda']>Activity_DF['Hookload Treshold']))
SubActivity_Label = "Stationary"
Activity_DF.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
DisplayDF(Activity_DF.loc[idx_logic_2, :])
#

logic_status = logic_status + 1
Activity_DF.loc[idx_logic_2, "logic_status"] = logic_status
    #13
# DisplayDF(Activity_DF.loc[idx_logic_2, :])

C:\Users\irsya\AppData\Local\Temp/ipykernel_4772/3457365467.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Activity_DF['isBitDepthMoving'] = Activity_DF['bitdepth'].shift(periods=-1) != Activity_DF['bitdepth']

Empty DataFrame
Columns: [date, time, dt, md, bitdepth, blockpos, hklda, rpm, stppress, mudflowin, rop, woba, torqa, SubActivity_Actual, Activity, Hookload Treshold, SubActivity, logic_status, isBitDepthMoving, IsCorrect]
Index: []

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

Empty DataFrame
Columns: [date, time, dt, md, bitdepth, blockpos, hklda, rpm, stppress, mudflowin, rop, woba, torqa, SubActivity_Actual, Activity, Hookload Treshold, SubActivity, logic_status, isBitDepthMoving, IsCorrect]
Index: []

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,date,time,dt,md,bitdepth,blockpos,hklda,rpm,stppress,mudflowin,rop,woba,torqa,SubActivity_Actual,Activity,Hookload Treshold,SubActivity,logic_status,isBitDepthMoving,IsCorrect
186,2022-02-21,00:15:30,2022-02-21 00:15:30,494.41,0.61,19.87,31.47,0,0.0,0.0,NaN,NaN,NaN,Moving,TRIP IN,30.8,Moving,0,True,False
189,2022-02-21,00:15:45,2022-02-21 00:15:45,494.41,0.00,21.55,33.21,0,0.0,0.0,NaN,NaN,NaN,Stationary,TRIP IN,30.8,Moving,0,True,False

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

Empty DataFrame
Columns: [date, time, dt, md, bitdepth, blockpos, hklda, rpm, stppress, mudflowin, rop, woba, torqa, SubActivity_Actual, Activity, Hookload Treshold, SubActivity, logic_status, isBitDepthMoving, IsCorrect]
Index: []

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,date,time,dt,md,bitdepth,blockpos,hklda,rpm,stppress,mudflowin,rop,woba,torqa,SubActivity_Actual,Activity,Hookload Treshold,SubActivity,logic_status,isBitDepthMoving,IsCorrect
168,2022-02-21,00:14:00,2022-02-21 00:14:00,494.41,1.25,19.23,30.13,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
169,2022-02-21,00:14:05,2022-02-21 00:14:05,494.41,1.25,19.23,30.37,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
170,2022-02-21,00:14:10,2022-02-21 00:14:10,494.41,1.25,19.23,30.73,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
174,2022-02-21,00:14:30,2022-02-21 00:14:30,494.41,1.25,19.23,30.59,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
175,2022-02-21,00:14:35,2022-02-21 00:14:35,494.41,1.25,19.23,29.70,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
176,2022-02-21,00:14:40,2022-02-21 00:14:40,494.41,1.25,19.23,29.73,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
177,2022-02-21,00:14:45,2022-02-21 00:14:45,494.41,1.25,19.23,29.73,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
178,2022-02-21,00:14:50,2022-02-21 00:14:50,494.41,1.25,19.23,29.98,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
179,2022-02-21,00:14:55,2022-02-21 00:14:55,494.41,1.25,19.23,30.61,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
180,2022-02-21,00:15:00,2022-02-21 00:15:00,494.41,1.25,19.23,30.41,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
181,2022-02-21,00:15:05,2022-02-21 00:15:05,494.41,1.25,19.23,29.83,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
182,2022-02-21,00:15:10,2022-02-21 00:15:10,494.41,1.25,19.23,29.77,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
183,2022-02-21,00:15:15,2022-02-21 00:15:15,494.41,1.25,19.23,29.73,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,False,True
184,2022-02-21,00:15:20,2022-02-21 00:15:20,494.41,1.25,19.23,29.67,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,True,True
185,2022-02-21,00:15:25,2022-02-21 00:15:25,494.41,1.13,19.35,29.43,0,0.0,0.0,NaN,NaN,NaN,Connection,TRIP IN,30.8,Connection,0,True,True

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,date,time,dt,md,bitdepth,blockpos,hklda,rpm,stppress,mudflowin,rop,woba,torqa,SubActivity_Actual,Activity,Hookload Treshold,SubActivity,logic_status,isBitDepthMoving,IsCorrect
171,2022-02-21,00:14:15,2022-02-21 00:14:15,494.41,1.25,19.23,30.81,0,0.0,0.0,NaN,NaN,NaN,Stationary,TRIP IN,30.8,Stationary,0,False,False
172,2022-02-21,00:14:20,2022-02-21 00:14:20,494.41,1.25,19.23,31.30,0,0.0,0.0,NaN,NaN,NaN,Stationary,TRIP IN,30.8,Stationary,0,False,False
173,2022-02-21,00:14:25,2022-02-21 00:14:25,494.41,1.25,19.23,31.55,0,0.0,0.0,NaN,NaN,NaN,Stationary,TRIP IN,30.8,Stationary,0,False,False
187,2022-02-21,00:15:35,2022-02-21 00:15:35,494.41,0.00,21.30,32.28,0,0.0,0.0,NaN,NaN,NaN,Stationary,TRIP IN,30.8,Stationary,0,False,False
188,2022-02-21,00:15:40,2022-02-21 00:15:40,494.41,0.00,21.55,33.17,0,0.0,0.0,NaN,NaN,NaN,Stationary,TRIP IN,30.8,Stationary,0,False,False

C:\Users\irsya\Miniconda3\envs\python38\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

# Summary Report Activity

In [191]:
import pandas as pd 
from IPython.display import display as DisplayDF

SubActivity_DF_new = pd.read_excel("BM_test\\IrsyadTest - Copy.xlsx")
SubActivity_DF_new.rename(columns = {'Activity_Actual':'Activity',
                                    'In Slip Value': 'Hookload Treshold', 'SubActivity_Actual': 'SubActivity'}, inplace = True)

# SubActivity_DF
# Result_DF = GetSubActivity_DF_v2(SubActivity_DF_new)
# Result_DF['IsCorrect'] = True
# Result_DF.loc[Result_DF['SubActivity_Actual'] != Result_DF['SubActivity'], 'IsCorrect'] = False

In [187]:
from IPython.display import display as DisplayDF
Final_DF = Result_DF[Result_DF['IsCorrect']==False]
DisplayDF(Final_DF)

Empty DataFrame
Columns: [date, time, dt, md, bitdepth, blockpos, hklda, rpm, stppress, mudflowin, rop, woba, torqa, SubActivity_Actual, Activity, Hookload Treshold, IsSummary, SubActivity, logic_status, isBitDepthMoving, IsCorrect]
Index: []

[0 rows x 21 columns]

In [197]:
def GenerateDuration_DF_v2(RealTime_DB):
    RealTime_DB['dt'] = pd.to_datetime(RealTime_DB['dt'])
    RealTime_DB['SubActivity'] = RealTime_DB['SubActivity'].str.upper()
    RealTime_DB['Activity'] = RealTime_DB['Activity'].str.upper()
    RealTime_DB["LABEL_All"] =RealTime_DB['SubActivity'].astype(str)+'--'+RealTime_DB['Activity'].astype(str)

    Duration_DB = pd.DataFrame(
        columns=[
            'date',
            'Time_start',
            'Time_end',
            'date_time',
            'Duration(minutes)',
            'Hole Depth(max)',
            'Bit Depth(mean)',
            "Meterage(m)(Drilling)",
            'RotateDrilling',
            'Slide Drilling',
            'ReamingTime',
            'ConnectionTime',
            'On Bottom Hours',
            'Stand Duration',
            'LABEL_SubActivity', "LABEL_Activity", "LABEL_StandGroup"
            ]
        )

    for k,DF_Temp in RealTime_DB.groupby((RealTime_DB['LABEL_All'].shift() != RealTime_DB['LABEL_All']).cumsum()):

        if not(("Hole_Depth" in locals()) or ("Hole_Depth" in globals())):
            Hole_Depth = 0

        list_temp = []

        date = DF_Temp.head(1)['date'].values[0]
        Time_start = DF_Temp.head(1)['time'].values[0]
        Time_end = DF_Temp.tail(1)['time'].values[0]
        date_time = DF_Temp.head(1)['dt'].values[0]
        # LABEL_ConnectionActivity = DF_Temp.head(1)['LABEL_ConnectionActivity'].values[0]
        LABEL_SubActivity = DF_Temp.head(1)['SubActivity'].values[0]
        LABEL_Activity = DF_Temp.head(1)['Activity'].values[0]
        # LABEL_MajorActivity = DF_Temp.head(1)['LABEL_MajorActivity'].values[0]

        Duration = np.round(((DF_Temp['dt'].max()-DF_Temp['dt'].min()).total_seconds())/60,2)
        Hole_Depth_Temp = DF_Temp['md'].max()

        if float(Hole_Depth_Temp)>= float(Hole_Depth):
            Hole_Depth = Hole_Depth_Temp
        

        Bit_Depth = DF_Temp['bitdepth'].mean()

        list_Out = [date, Time_start,Time_end, date_time, Duration, Hole_Depth, Bit_Depth, np.empty(1), np.empty(1), np.empty(1), np.empty(1), np.empty(1), np.empty(1), np.empty(1), LABEL_SubActivity, LABEL_Activity, np.nan]
        Duration_DB.loc[len(Duration_DB)] = list_Out

    Duration_DB = Duration_DB.astype(
        {
            'Duration(minutes)':'float',
            'Hole Depth(max)':'float',
            'Bit Depth(mean)':'float',
            "Meterage(m)(Drilling)":'float',
            'RotateDrilling':'float',
            'Slide Drilling':'float',
            'ReamingTime':'float',
            'ConnectionTime':'float',
            'On Bottom Hours':'float',
            'Stand Duration':'float',
            "LABEL_SubActivity":'str', "LABEL_Activity":'str',"LABEL_StandGroup":'float'
        }
    )
    Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'ROTARY DRILLING', 'RotateDrilling'] = Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'ROTARY DRILLING', 'Duration(minutes)']
    Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'SLIDE DRILLING', 'Slide Drilling'] = Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'SLIDE DRILLING', 'Duration(minutes)']
    Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'REAMING', 'ReamingTime'] = Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'REAMING', 'Duration(minutes)']
    Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'CONNECTION', 'ConnectionTime'] = Duration_DB.loc[Duration_DB['LABEL_SubActivity'] == 'CONNECTION', 'Duration(minutes)']

    DrillingOnlyDB = Duration_DB[Duration_DB["LABEL_Activity"]=="DRILLING FORMATION"]
    start_idx = DrillingOnlyDB.index.values[0]
    StandNum_Temp = 1
    # for i,row in DrillingOnlyDB[DrillingOnlyDB['SubActivity'].isin(['CONNECTION', 'REAMING'])].iterrows():
        
        # if row['LABEL_ConnectionActivity'] == 'CONNECTION' and StandNum==1:
            # end_idx = i-1
    #         Duration_DB.loc[i, "Meterage(m)(Drilling)"] = Duration_DB.loc[start_idx:end_idx, "Meterage(m)(Drilling)"].fillna(0).sum()
    #         Duration_DB.loc[i, "On Bottom Hours"] = Duration_DB.loc[start_idx:end_idx, "Slide Drilling"].fillna(0).sum() + Duration_DB.loc[start_idx:end_idx, "RotateDrilling"].fillna(0).sum()
    #         Duration_DB.loc[i, "Stand Duration"] = Duration_DB.loc[start_idx:end_idx, "ReamingTime"].fillna(0).sum() + Duration_DB.loc[i, "On Bottom Hours"] + row['ConnectionTime']
    #         Duration_DB.loc[start_idx:end_idx+1, "LABEL_StandGroup"] = StandNum_Temp
    #         StandNum_Temp = StandNum_Temp + 1
    #         start_idx = start_idx + 1
    #     elif row['LABEL_ConnectionActivity'] == "POST CONNECTION":
    #         start_idx = i

        # print(str(start_idx) + " - " + str(end_idx))

    listSetDecimals = [
            'Duration(minutes)',
            'Hole Depth(max)',
            'Bit Depth(mean)',
            "Meterage(m)(Drilling)",
            'RotateDrilling',
            'Slide Drilling',
            'ReamingTime',
            'ConnectionTime',
            'On Bottom Hours',
            'Stand Duration',
    ]
    for ColumnName in listSetDecimals:
        print(ColumnName)
        Duration_DB[ColumnName] = Duration_DB[ColumnName].round(decimals=2)

    # rounded_df = df.round(decimals=2)
    return Duration_DB

In [234]:
def GenerateDuration_DF_v3(RealTime_DB):
    RealTime_DB['dt'] = pd.to_datetime(RealTime_DB['dt'])
    RealTime_DB['SubActivity'] = RealTime_DB['SubActivity'].str.upper()
    RealTime_DB['Activity'] = RealTime_DB['Activity'].str.upper()
    RealTime_DB["LABEL_All"] =RealTime_DB['SubActivity'].astype(str)+'--'+RealTime_DB['Activity'].astype(str)

    Duration_DB = pd.DataFrame(
        columns=[
            'date',
            'Time_start',
            'Time_end',
            'date_time',
            'Duration(minutes)',
            'Hole Depth(max)',
            'Bit Depth(mean)',
            "Meterage(m)(Drilling)",
            'RotateDrilling',
            'Slide Drilling',
            'ReamingTime',
            'ConnectionTime',
            'On Bottom Hours',
            'Stand Duration',
            'SubActivity', "Activity", "LABEL_StandGroup"
            ]
        )

    for k,DF_Temp in RealTime_DB.groupby((RealTime_DB['LABEL_All'].shift() != RealTime_DB['LABEL_All']).cumsum()):

        if not(("Hole_Depth" in locals()) or ("Hole_Depth" in globals())):
            Hole_Depth = 0

        list_temp = []

        date = DF_Temp.head(1)['date'].values[0]
        Time_start = DF_Temp.head(1)['time'].values[0]
        Time_end = DF_Temp.tail(1)['time'].values[0]
        date_time = DF_Temp.head(1)['dt'].values[0]
        # LABEL_ConnectionActivity = DF_Temp.head(1)['LABEL_ConnectionActivity'].values[0]
        SubActivity = DF_Temp.head(1)['SubActivity'].values[0]
        Activity = DF_Temp.head(1)['Activity'].values[0]
        # LABEL_MajorActivity = DF_Temp.head(1)['LABEL_MajorActivity'].values[0]

        Duration = ((DF_Temp['dt'].max()-DF_Temp['dt'].min()).total_seconds())/60
        Hole_Depth_Temp = DF_Temp['md'].max()

        if float(Hole_Depth_Temp)>= float(Hole_Depth):
            Hole_Depth = Hole_Depth_Temp
        

        Bit_Depth = DF_Temp['bitdepth'].mean()

        list_Out = [date, Time_start,Time_end, date_time, Duration, Hole_Depth, Bit_Depth, np.empty(1), np.empty(1), np.empty(1), np.empty(1), np.empty(1), np.empty(1), np.empty(1), SubActivity, Activity, np.nan]
        Duration_DB.loc[len(Duration_DB)] = list_Out

    Duration_DB = Duration_DB.astype(
        {
            'Duration(minutes)':'float',
            'Hole Depth(max)':'float',
            'Bit Depth(mean)':'float',
            "Meterage(m)(Drilling)":'float',
            'RotateDrilling':'float',
            'Slide Drilling':'float',
            'ReamingTime':'float',
            'ConnectionTime':'float',
            'On Bottom Hours':'float',
            'Stand Duration':'float',
            "SubActivity":'str', "Activity":'str',"LABEL_StandGroup":'float'
        }
    )

    Duration_DB.loc[Duration_DB['SubActivity'] == 'ROTARY DRILLING', 'RotateDrilling'] = Duration_DB.loc[Duration_DB['SubActivity'] == 'ROTARY DRILLING', 'Duration(minutes)']
    Duration_DB.loc[Duration_DB['SubActivity'] == 'SLIDE DRILLING', 'Slide Drilling'] = Duration_DB.loc[Duration_DB['SubActivity'] == 'SLIDE DRILLING', 'Duration(minutes)']
    Duration_DB.loc[Duration_DB['SubActivity'] == 'REAMING', 'ReamingTime'] = Duration_DB.loc[Duration_DB['SubActivity'] == 'REAMING', 'Duration(minutes)']
    Duration_DB.loc[Duration_DB['SubActivity'] == 'CONNECTION', 'ConnectionTime'] = Duration_DB.loc[Duration_DB['SubActivity'] == 'CONNECTION', 'Duration(minutes)']

    # DrillingOnlyDB = Duration_DB[Duration_DB["Activity"]=="DRILLING FORMATION"]
    # start_idx = DrillingOnlyDB.index.values[0]
    # StandNum_Temp = 1
    # for i,row in DrillingOnlyDB[DrillingOnlyDB['SubActivity'].isin(['CONNECTION', 'REAMING'])].iterrows():
        
        # if row['LABEL_ConnectionActivity'] == 'CONNECTION' and StandNum==1:
            # end_idx = i-1
    #         Duration_DB.loc[i, "Meterage(m)(Drilling)"] = Duration_DB.loc[start_idx:end_idx, "Meterage(m)(Drilling)"].fillna(0).sum()
    #         Duration_DB.loc[i, "On Bottom Hours"] = Duration_DB.loc[start_idx:end_idx, "Slide Drilling"].fillna(0).sum() + Duration_DB.loc[start_idx:end_idx, "RotateDrilling"].fillna(0).sum()
    #         Duration_DB.loc[i, "Stand Duration"] = Duration_DB.loc[start_idx:end_idx, "ReamingTime"].fillna(0).sum() + Duration_DB.loc[i, "On Bottom Hours"] + row['ConnectionTime']
    #         Duration_DB.loc[start_idx:end_idx+1, "LABEL_StandGroup"] = StandNum_Temp
    #         StandNum_Temp = StandNum_Temp + 1
    #         start_idx = start_idx + 1
    #     elif row['LABEL_ConnectionActivity'] == "POST CONNECTION":
    #         start_idx = i

        # print(str(start_idx) + " - " + str(end_idx))

    listSetDecimals = [
            'Duration(minutes)',
            'Hole Depth(max)',
            'Bit Depth(mean)',
            "Meterage(m)(Drilling)",
            'RotateDrilling',
            'Slide Drilling',
            'ReamingTime',
            'ConnectionTime',
            'On Bottom Hours',
            'Stand Duration',
    ]
    for ColumnName in listSetDecimals:
        print(ColumnName)
        Duration_DB[ColumnName] = Duration_DB[ColumnName].round(decimals=2)

    # rounded_df = df.round(decimals=2)
    return Duration_DB

In [235]:
Ori_DF = GenerateDuration_DF_v3(SubActivity_DF_new)
Ori_DF
Ori_DF.to_excel('BM_test\\SummaryTest_' + str(ext_num_2+5)+ '.xlsx')

Duration(minutes)
Hole Depth(max)
Bit Depth(mean)
Meterage(m)(Drilling)
RotateDrilling
Slide Drilling
ReamingTime
ConnectionTime
On Bottom Hours
Stand Duration