In [2]:
import pandas as pd 
import numpy as np

In [3]:
import requests
CompName_JSON = requests.get(
        "https://pdumitradome.id/dome_api/rtdc/get_company/"
    ).json()
CompName_DF = pd.json_normalize(CompName_JSON, record_path = 'result')
selected_comp = "KS ORKA"

display(CompName_DF[CompName_DF['company_name']==selected_comp])

getWellAPI = "https://pdumitradome.id/dome_api/rtdc/get_well?cid=" + (CompName_DF.loc[CompName_DF['company_name']==selected_comp, 'cid'].values)
WellName_JSON = requests.get(
        getWellAPI[0]
    ).json()
WellName_DF = pd.json_normalize(WellName_JSON, record_path = 'result')
display(WellName_DF)

   cid company_name
19   9      KS ORKA

,wid,cid,well_name,rig_name,active_date,end_date,proposed_total_measured_depth,time_master
0,129,9,SMP T10,Kaishan-1,2020-11-13,2020-12-31,2500,"[{'time_date_start': '2021-01-04', 'time_date_..."
1,130,9,SMP - 119,PRA#1,2020-11-28,2021-01-30,2500,[]
2,135,9,SMP P-118 ST,PRA#1,2021-01-05,2021-04-30,3000,"[{'time_date_start': '2021-01-04', 'time_date_..."
3,136,9,SMP AA-01ST2,Kaishan 1,2021-01-14,2021-07-31,3000,"[{'time_date_start': '2021-01-11', 'time_date_..."
4,140,9,SMP AA-03,Kaishan 1,2021-04-15,2021-06-30,3000,"[{'time_date_start': '2021-04-12', 'time_date_..."
5,143,9,SMP AAE-03,PRA#1,2021-04-25,2021-06-30,3000,"[{'time_date_start': '2021-04-19', 'time_date_..."
6,144,9,SMP AAE-02,PRA#1,2021-06-03,2021-07-31,4000,"[{'time_date_start': '2021-05-31', 'time_date_..."
7,145,9,SMP AA-02ST,Kaishan 1,2021-06-17,2021-08-31,4000,"[{'time_date_start': '2021-06-14', 'time_date_..."
8,146,9,SMP AAE-05,PRA#1,2021-06-28,2021-08-31,4000,"[{'time_date_start': '2021-06-28', 'time_date_..."
9,150,9,SMP AAE-06ST3,PRA#1,2021-08-12,2022-02-05,3000,"[{'time_date_start': '2021-08-09', 'time_date_..."
10,156,9,SMP AAE-07,PRA#1,2021-09-25,2021-10-31,3000,"[{'time_date_start': '2021-09-20', 'time_date_..."
11,160,9,SMP AAE-07ST3,PRA#1,2021-10-25,2022-01-01,3000,"[{'time_date_start': '2021-10-25', 'time_date_..."
12,170,9,SMP AAE-08,PRA#1,2022-01-27,2022-03-31,2500,"[{'time_date_start': '2022-01-24', 'time_date_..."
13,175,9,SMP T-11,Kaishan 1,2022-02-25,2022-04-30,3000,"[{'time_date_start': '2022-02-21', 'time_date_..."
14,182,9,SMP T-12,Kaishan-1,2022-04-12,2022-05-31,3000,"[{'time_date_start': '2022-04-11', 'time_date_..."
15,186,9,SMP T-11 WO,Kaishan 1,2022-05-14,2022-06-11,3000,"[{'time_date_start': '2022-05-09', 'time_date_..."

In [5]:
Well_ID_API = 156

### generate Activity Summary Data

In [6]:
from Streamlit_App import IO_Data
def cache_RealTime_Data(well_id, StartDateTime_select, EndDateTime_select):
    Activity_DF = IO_Data.getActivityData_v2(well_id, StartDateTime_select, EndDateTime_select)
    Activity_DF['dt'] = Activity_DF['dt'].astype('datetime64')
    Activity_DF['bitdepth'] = Activity_DF['bitdepth'].astype('float64')
    Activity_DF['blockpos'] = Activity_DF['blockpos'].astype('float64')
    Activity_DF['rop'] = Activity_DF['rop'].astype('float64')
    Activity_DF['hklda'] = Activity_DF['hklda'].astype('float64')
    Activity_DF['woba'] = Activity_DF['woba'].astype('float64')
    Activity_DF['torqa'] = Activity_DF['torqa'].astype('float64')
    Activity_DF['rpm'] = Activity_DF['rpm'].astype('float64')
    Activity_DF['stppress'] = Activity_DF['stppress'].astype('float64')
    Activity_DF['mudflowin'] = Activity_DF['mudflowin'].astype('float64')

    return Activity_DF

timestart = '2021-10-08 00:00:00'
timeend = '2021-10-10 00:00:00'
Activity_DF = cache_RealTime_Data(Well_ID_API, 
                                timestart,
                                timeend)
display(Activity_DF.tail(10))

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin
30804,2021-10-09 23:59:14,2021-10-09,23:59:14,632.27,632.27,26.84,6.35,92.22,12.01,0.0,0.0,1833.09,1111.69
30805,2021-10-09 23:59:19,2021-10-09,23:59:19,632.29,632.29,26.82,6.35,92.09,12.14,0.0,0.0,1838.91,1113.46
30806,2021-10-09 23:59:24,2021-10-09,23:59:24,632.31,632.31,26.80,6.35,92.43,11.80,0.0,0.0,1840.00,1112.58
30807,2021-10-09 23:59:29,2021-10-09,23:59:29,632.32,632.32,26.78,6.35,92.68,11.55,0.0,0.0,1837.09,1111.69
30808,2021-10-09 23:59:34,2021-10-09,23:59:34,632.34,632.34,26.77,6.35,92.68,11.55,0.0,0.0,1836.72,1112.58
30809,2021-10-09 23:59:39,2021-10-09,23:59:39,632.36,632.36,26.75,6.35,92.86,11.37,0.0,0.0,1834.55,1111.69
30810,2021-10-09 23:59:44,2021-10-09,23:59:44,632.38,632.38,26.73,6.35,92.13,12.10,0.0,0.0,1838.91,1112.58
30811,2021-10-09 23:59:49,2021-10-09,23:59:49,632.41,632.41,26.70,6.35,91.92,12.31,0.0,0.0,1846.91,1112.58
30812,2021-10-09 23:59:54,2021-10-09,23:59:54,632.43,632.43,26.68,6.35,91.44,12.79,0.0,0.0,1851.64,1110.81
30813,2021-10-09 23:59:59,2021-10-09,23:59:59,632.45,632.45,26.66,6.35,91.27,12.96,0.0,0.0,1855.27,1112.58

In [7]:
from importlib import reload
from datetime import datetime, timedelta
reload(IO_Data)
# Time_end = pd.to_datetime(DF_Temp.tail(1)['date'].values[0] + " " + str(datetime.strptime(Time_end_temp, "%H:%M:%S")) + (timedelta(seconds=5)).time())
timestart_input = str(datetime.strptime(timestart, '%Y-%m-%d %H:%M:%S') - timedelta(days=1))
InputActivity_DB = (IO_Data.DomeGetData(Well_ID_API, timestart_input, timeend))
InputActivity_DB
# str(timestart_input)

get Activity Log data/table from DOME

c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App\IO_Data.py:423: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  out_DF = out_DF.drop('date_time', 1)

,input_id,dt,date,time,activity,in_slip_threshold,remarks,pic,section
0,353,2021-10-04 09:00:01,2021-10-04,09:00:01,MAKE UP BHA,63,,Admin,"26"""""
1,354,2021-10-04 13:28:31,2021-10-04,13:28:31,TRIP IN,63,,Admin,"26"""""
2,355,2021-10-04 14:09:36,2021-10-04,14:09:36,DRILL OUT CEMENT,63,Lost connection at 15:47,Admin,"26"""""
3,356,2021-10-04 17:40:01,2021-10-04,17:40:01,RIG REPAIR,63,Repair TDS,Admin,"26"""""
4,357,2021-10-04 18:27:26,2021-10-04,18:27:26,DRILLING FORMATION,63,,Admin,"26"""""
...,...,...,...,...,...,...,...,...,...
81,434,2021-10-19 07:59:05,2021-10-19,07:59:05,DRILLING FORMATION,63,,Admin,"12-1/4"""""
82,435,2021-10-20 11:01:29,2021-10-20,11:01:29,CIRCULATE HOLE CLEANING,63,Circulation hole cleaning due to erratic torque,Admin,"12-1/4"""""
83,436,2021-10-20 12:10:00,2021-10-20,12:10:00,STUCK PIPE,63,Stuck pipe incident,Admin,"12-1/4"""""
84,437,2021-10-20 12:20:00,2021-10-20,12:20:00,CIRCULATION,63,Circulation hole cleaning post stuck pipe,Admin,"12-1/4"""""
85,438,2021-10-20 14:07:00,2021-10-20,14:07:00,STUCK PIPE,63,,Admin,"12-1/4"""""

In [12]:
from Streamlit_App import Activity
reload(Activity)
def InputTranslator(Input_DB):
    Input_DB['dt'] = (Input_DB['dt']).apply(lambda d: pd.to_datetime(str(d)))

    Input_DB.rename(columns = {'in_slip_threshold':'Hook Treshold', 'activity':'Activity'}, inplace = True)
    return Input_DB

Input_Temp = InputTranslator(InputActivity_DB)
print("\nInput Temporary:\n")
display(Input_Temp.tail(5))
Activity_DF_v1 = Activity.GetActivity_DF(Activity_DF, Input_Temp)
print("\n5s Data activity labelled:\n")
display(Activity_DF_v1.tail(5))

Activity_DF_v2 = Activity.GetSubActivity_DF_v3(Activity_DF_v1)
print("\n5s Data with SubActivity Formula:\n")
display(Activity_DF_v2)

Input Temporary:

,input_id,dt,date,time,Activity,Hook Treshold,remarks,pic,section
81,434,2021-10-19 07:59:05,2021-10-19,07:59:05,DRILLING FORMATION,63,,Admin,"12-1/4"""""
82,435,2021-10-20 11:01:29,2021-10-20,11:01:29,CIRCULATE HOLE CLEANING,63,Circulation hole cleaning due to erratic torque,Admin,"12-1/4"""""
83,436,2021-10-20 12:10:00,2021-10-20,12:10:00,STUCK PIPE,63,Stuck pipe incident,Admin,"12-1/4"""""
84,437,2021-10-20 12:20:00,2021-10-20,12:20:00,CIRCULATION,63,Circulation hole cleaning post stuck pipe,Admin,"12-1/4"""""
85,438,2021-10-20 14:07:00,2021-10-20,14:07:00,STUCK PIPE,63,,Admin,"12-1/4"""""

5s Data activity labelled:

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,pic,section,remarks,Activity,Hookload Treshold
30809,2021-10-09 23:59:39,2021-10-09,23:59:39,632.36,632.36,26.75,6.35,92.86,11.37,0.0,0.0,1834.55,1111.69,Admin,"17-1/2""""",,DRILLING FORMATION,63
30810,2021-10-09 23:59:44,2021-10-09,23:59:44,632.38,632.38,26.73,6.35,92.13,12.10,0.0,0.0,1838.91,1112.58,Admin,"17-1/2""""",,DRILLING FORMATION,63
30811,2021-10-09 23:59:49,2021-10-09,23:59:49,632.41,632.41,26.70,6.35,91.92,12.31,0.0,0.0,1846.91,1112.58,Admin,"17-1/2""""",,DRILLING FORMATION,63
30812,2021-10-09 23:59:54,2021-10-09,23:59:54,632.43,632.43,26.68,6.35,91.44,12.79,0.0,0.0,1851.64,1110.81,Admin,"17-1/2""""",,DRILLING FORMATION,63
30813,2021-10-09 23:59:59,2021-10-09,23:59:59,632.45,632.45,26.66,6.35,91.27,12.96,0.0,0.0,1855.27,1112.58,Admin,"17-1/2""""",,DRILLING FORMATION,63

5s Data with SubActivity Formula:

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,...,stppress,mudflowin,pic,section,remarks,Activity,Hookload Treshold,SubActivity,logic_status,isBitDepthMoving
0,2021-10-08 00:00:03,2021-10-08,00:00:03,0.00,400.02,15.55,16.14,37.42,0.00,0.0,...,0.00,0.00,Admin,"26""""",,WAIT ON CEMENT,63.0,WAIT ON CEMENT,14,False
1,2021-10-08 00:00:08,2021-10-08,00:00:08,0.00,400.02,15.55,16.14,37.42,0.00,0.0,...,0.00,0.00,Admin,"26""""",,WAIT ON CEMENT,63.0,WAIT ON CEMENT,14,False
2,2021-10-08 00:00:13,2021-10-08,00:00:13,0.00,400.02,15.55,16.14,37.42,0.00,0.0,...,0.00,0.00,Admin,"26""""",,WAIT ON CEMENT,63.0,WAIT ON CEMENT,14,False
3,2021-10-08 00:00:18,2021-10-08,00:00:18,0.00,400.02,15.55,16.14,37.42,0.00,0.0,...,0.00,0.00,Admin,"26""""",,WAIT ON CEMENT,63.0,WAIT ON CEMENT,14,False
4,2021-10-08 00:00:23,2021-10-08,00:00:23,0.00,400.02,15.55,16.14,37.42,0.00,0.0,...,0.00,0.00,Admin,"26""""",,WAIT ON CEMENT,63.0,WAIT ON CEMENT,14,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30809,2021-10-09 23:59:39,2021-10-09,23:59:39,632.36,632.36,26.75,6.35,92.86,11.37,0.0,...,1834.55,1111.69,Admin,"17-1/2""""",,DRILLING FORMATION,63.0,Slide Drilling,3,True
30810,2021-10-09 23:59:44,2021-10-09,23:59:44,632.38,632.38,26.73,6.35,92.13,12.10,0.0,...,1838.91,1112.58,Admin,"17-1/2""""",,DRILLING FORMATION,63.0,Slide Drilling,3,True
30811,2021-10-09 23:59:49,2021-10-09,23:59:49,632.41,632.41,26.70,6.35,91.92,12.31,0.0,...,1846.91,1112.58,Admin,"17-1/2""""",,DRILLING FORMATION,63.0,Slide Drilling,3,True
30812,2021-10-09 23:59:54,2021-10-09,23:59:54,632.43,632.43,26.68,6.35,91.44,12.79,0.0,...,1851.64,1110.81,Admin,"17-1/2""""",,DRILLING FORMATION,63.0,Slide Drilling,3,True
30813,2021-10-09 23:59:59,2021-10-09,23:59:59,632.45,632.45,26.66,6.35,91.27,12.96,0.0,...,1855.27,1112.58,Admin,"17-1/2""""",,DRILLING FORMATION,63.0,Slide Drilling,3,True

In [15]:
reload(Activity)
SummaryActivity_DF_0 = (((Activity.GenerateDuration_DF_v7(Activity_DF_v2))))
SummaryActivity_DF_1 = Activity.labelStand_v2(((Activity.GenerateDuration_DF_v6(Activity_DF_v2))))
SummaryActivity_DF_2 = Activity.labelStand_v2(Activity.cleanFalseSensor((Activity.GenerateDuration_DF_v6(Activity_DF_v2))))

In [16]:
SummaryActivity_DF_0

,date,Time_start,Time_end,date_time,Duration(minutes),Hole Depth(max),Bit Depth(mean),Meterage(m)(Drilling),LABEL_SubActivity,LABEL_Activity,PIC,Remarks,Section
0,2021-10-08,2021-10-08 00:00:03,2021-10-08 05:00:03,2021-10-08 00:00:03,299.92,400.02,0.00,0.00,WAIT ON CEMENT,WAIT ON CEMENT,Admin,,"26"""""
1,2021-10-08,2021-10-08 05:00:03,2021-10-08 14:18:33,2021-10-08 05:00:03,558.42,400.02,0.00,0.00,Connection,OTHER,Admin,,"26"""""
2,2021-10-08,2021-10-08 14:18:33,2021-10-08 14:18:58,2021-10-08 14:18:33,0.33,400.02,0.00,0.00,FALSE/Check,OTHER,Admin,,"26"""""
3,2021-10-08,2021-10-08 14:18:58,2021-10-08 14:51:35,2021-10-08 14:18:58,32.53,400.02,0.00,0.00,Connection,OTHER,Admin,,"26"""""
4,2021-10-08,2021-10-08 19:02:40,2021-10-08 22:01:59,2021-10-08 19:02:40,179.23,400.02,11.80,0.00,MAKE UP BHA,MAKE UP BHA,Admin,,"17-1/2"""""
...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,2021-10-09,2021-10-09 23:43:19,2021-10-09 23:44:29,2021-10-09 23:43:19,1.08,631.01,628.97,0.00,Reaming,DRILLING FORMATION,Admin,,"17-1/2"""""
411,2021-10-09,2021-10-09 23:44:29,2021-10-09 23:47:34,2021-10-09 23:44:29,3.00,631.01,629.23,0.00,Wash Up/Down,DRILLING FORMATION,Admin,,"17-1/2"""""
412,2021-10-09,2021-10-09 23:47:34,2021-10-09 23:47:44,2021-10-09 23:47:34,0.08,631.01,629.33,0.00,FALSE/Check,DRILLING FORMATION,Admin,,"17-1/2"""""
413,2021-10-09,2021-10-09 23:47:44,2021-10-09 23:48:39,2021-10-09 23:47:44,0.83,631.01,629.76,0.00,Wash Up/Down,DRILLING FORMATION,Admin,,"17-1/2"""""
414,2021-10-09,2021-10-09 23:48:39,2021-10-10 00:00:04,2021-10-09 23:48:39,11.33,632.45,631.64,1.44,Slide Drilling,DRILLING FORMATION,Admin,,"17-1/2"""""

In [1]:
def calculate

NameError: name 'reload' is not defined

In [74]:


idx_logic = (Activity_DF_v2['dt'] > "2021-10-08 23:10:00") & (Activity_DF_v2['dt'] < "2021-10-08 23:20:00")
Activity_DF_v2_Example = Activity_DF_v2[idx_logic]
Activity_DF_v2_Example.to_excel("Activity_DF_v2_Example.xlsx")
# Activity_DF_v2.head()

In [81]:
SummaryActivity_DF_2.to_excel("SummaryActivity_Example_v2.xlsx")

In [25]:
26*26

676

# Generate Drilling Time, Pre & Post Connection, and Labelling Stand

In [1]:
import pandas as pd 
from Streamlit_App import Activity

In [8]:
Data = pd.read_csv("KS ORKA_SMP AAE-07_ActivitySummary.csv", index_col=False)
with pd.option_context('display.max_rows', 200):
    display(Data[0:100])

,STATUS,Date,Start Time,End Time,ACTIVITY,SUB-ACTIVITY,Duration (Minutes),Hole Depth (Max),Bit Depth(mean),Drilling Meterage (m),PIC,Remarks,Section
0,ON REVIEW,2021-10-12 00:00:00,2021-10-12 21:00:01,2021-10-12 21:35:51,TRIP OUT,Connection,35.75,1015.00,0.00,0.00,Admin,NaN,"17-1/2"""""
1,ON REVIEW,2021-10-12 00:00:00,2021-10-12 21:35:51,2021-10-12 23:20:01,OTHER,Connection,104.08,1015.00,0.00,0.00,Admin,"OVERSHOT + FISH ON SURFACE, B/O OVERSHOT + FISH","17-1/2"""""
2,ON REVIEW,2021-10-12 00:00:00,2021-10-12 23:20:01,2021-10-13 00:14:41,MAKE UP BHA,MAKE UP BHA,54.58,1015.00,3.80,0.00,Admin,Make up BHA,"17-1/2"""""
3,ON REVIEW,2021-10-13 00:00:00,2021-10-13 00:14:41,2021-10-13 01:28:56,TRIP IN,Connection,73.75,1015.00,53.76,0.00,Admin,NaN,"17-1/2"""""
4,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:28:56,2021-10-13 01:29:46,TRIP IN,Moving,0.58,1015.00,67.40,0.00,Admin,NaN,"17-1/2"""""
5,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:29:46,2021-10-13 01:43:06,TRIP IN,Connection,13.25,1015.00,83.51,0.00,Admin,NaN,"17-1/2"""""
6,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:43:06,2021-10-13 01:47:01,TRIP IN,Stationary,3.67,1015.00,84.36,0.00,Admin,NaN,"17-1/2"""""
7,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:47:01,2021-10-13 01:47:56,TRIP IN,Moving,0.75,1015.00,91.58,0.00,Admin,NaN,"17-1/2"""""
8,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:47:56,2021-10-13 02:08:31,TRIP IN,Connection,20.08,1015.00,93.03,0.00,Admin,NaN,"17-1/2"""""
9,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:08:31,2021-10-13 02:09:26,TRIP IN,Stationary,0.67,1015.00,102.59,0.00,Admin,NaN,"17-1/2"""""
10,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:09:26,2021-10-13 02:19:56,TRIP IN,Connection,10.08,1015.00,107.95,0.00,Admin,NaN,"17-1/2"""""
11,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:19:56,2021-10-13 02:20:26,TRIP IN,Stationary,0.42,1015.00,112.45,0.00,Admin,NaN,"17-1/2"""""
12,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:20:26,2021-10-13 02:21:46,TRIP IN,Moving,0.91,1015.00,114.17,0.00,Admin,NaN,"17-1/2"""""
13,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:21:46,2021-10-13 02:24:41,TRIP IN,Connection,2.66,1015.00,139.84,0.00,Admin,NaN,"17-1/2"""""
14,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:24:41,2021-10-13 02:25:06,TRIP IN,Moving,0.33,1015.00,141.68,0.00,Admin,NaN,"17-1/2"""""
15,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:25:06,2021-10-13 02:27:01,TRIP IN,Connection,1.66,1015.00,167.94,0.00,Admin,NaN,"17-1/2"""""
16,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:27:01,2021-10-13 02:27:31,TRIP IN,Moving,0.33,1015.00,171.25,0.00,Admin,NaN,"17-1/2"""""
17,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:27:31,2021-10-13 02:31:26,TRIP IN,Connection,3.24,1015.00,195.99,0.00,Admin,NaN,"17-1/2"""""
18,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:31:26,2021-10-13 02:32:01,TRIP IN,Stationary,0.50,1015.00,196.92,0.00,Admin,NaN,"17-1/2"""""
19,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:32:01,2021-10-13 02:33:26,TRIP IN,Circulation,1.25,1015.00,196.99,0.00,Admin,NaN,"17-1/2"""""
20,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:33:26,2021-10-13 02:33:51,TRIP IN,Moving,0.33,1015.00,199.56,0.00,Admin,NaN,"17-1/2"""""
21,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:33:51,2021-10-13 02:52:21,TRIP IN,Connection,16.42,1015.00,282.30,0.00,Admin,NaN,"17-1/2"""""
22,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:52:21,2021-10-13 02:53:11,TRIP IN,Moving,0.75,1015.00,368.04,0.00,Admin,NaN,"17-1/2"""""
23,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:53:11,2021-10-13 02:54:46,TRIP IN,Connection,1.50,1015.00,390.53,0.00,Admin,NaN,"17-1/2"""""
24,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:54:46,2021-10-13 02:55:51,TRIP IN,Moving,0.92,1015.00,407.46,0.00,Admin,NaN,"17-1/2"""""
25,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:55:51,2021-10-13 02:57:26,TRIP IN,Connection,1.50,1015.00,419.88,0.00,Admin,NaN,"17-1/2"""""
26,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:57:26,2021-10-13 02:58:21,TRIP IN,Moving,0.75,1015.00,437.88,0.00,Admin,NaN,"17-1/2"""""
27,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:58:21,2021-10-13 03:00:06,TRIP IN,Connection,1.67,1015.00,448.88,0.00,Admin,NaN,"17-1/2"""""
28,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:00:06,2021-10-13 03:01:01,TRIP IN,Moving,0.49,1015.00,454.72,0.00,Admin,NaN,"17-1/2"""""
29,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:01:01,2021-10-13 03:08:01,TRIP IN,Connection,6.59,1015.00,461.34,0.00,Admin,NaN,"17-1/2"""""
30,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:08:01,2021-10-13 03:09:11,TRIP IN,Moving,1.08,1015.00,493.00,0.00,Admin,NaN,"17-1/2"""""
31,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:09:11,2021-10-13 03:10:51,TRIP IN,Connection,1.58,1015.00,506.51,0.00,Admin,NaN,"17-1/2"""""
32,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:10:51,2021-10-13 03:12:01,TRIP IN,Moving,0.92,1015.00,524.55,0.00,Admin,NaN,"17-1/2"""""
33,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:12:01,2021-10-13 03:13:41,TRIP IN,Connection,1.58,1015.00,534.73,0.00,Admin,NaN,"17-1/2"""""
34,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:13:41,2021-10-13 03:14:46,TRIP IN,Moving,1.00,1015.00,551.54,0.00,Admin,NaN,"17-1/2"""""
35,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:14:46,2021-10-13 03:16:31,TRIP IN,Connection,1.67,1015.00,567.81,0.00,Admin,NaN,"17-1/2"""""
36,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:16:31,2021-10-13 03:17:46,TRIP IN,Moving,1.08,1015.00,585.92,0.00,Admin,NaN,"17-1/2"""""
37,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:17:46,2021-10-13 03:19:41,TRIP IN,Connection,1.83,1015.00,597.70,0.00,Admin,NaN,"17-1/2"""""
38,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:19:41,2021-10-13 03:20:51,TRIP IN,Moving,1.00,1015.00,616.34,0.00,Admin,NaN,"17-1/2"""""
39,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:20:51,2021-10-13 03:22:36,TRIP IN,Connection,1.67,1015.00,627.10,0.00,Admin,NaN,"17-1/2"""""
40,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:22:36,2021-10-13 03:23:41,TRIP IN,Moving,1.00,1015.00,638.63,0.00,Admin,NaN,"17-1/2"""""
41,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:23:41,2021-10-13 03:25:51,TRIP IN,Connection,2.08,1015.00,656.80,0.00,Admin,NaN,"17-1/2"""""
42,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:25:51,2021-10-13 03:27:01,TRIP IN,Moving,1.00,1015.00,673.94,0.00,Admin,NaN,"17-1/2"""""
43,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:27:01,2021-10-13 03:29:06,TRIP IN,Connection,2.00,1015.00,686.79,0.00,Admin,NaN,"17-1/2"""""
44,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:29:06,2021-10-13 03:30:16,TRIP IN,Moving,1.08,1015.00,698.52,0.00,Admin,NaN,"17-1/2"""""
45,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:30:16,2021-10-13 03:32:26,TRIP IN,Connection,2.08,1015.00,715.55,0.00,Admin,NaN,"17-1/2"""""
46,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:32:26,2021-10-13 03:33:41,TRIP IN,Moving,1.08,1015.00,735.30,0.00,Admin,NaN,"17-1/2"""""
47,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:33:41,2021-10-13 03:35:11,TRIP IN,Connection,1.42,1015.00,745.67,0.00,Admin,NaN,"17-1/2"""""
48,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:35:11,2021-10-13 03:36:26,TRIP IN,Moving,0.91,1015.00,761.64,0.00,Admin,NaN,"17-1/2"""""
49,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:36:26,2021-10-13 03:40:51,TRIP IN,Connection,4.17,1015.00,764.19,0.00,Admin,NaN,"17-1/2"""""
50,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:40:51,2021-10-13 03:41:21,TRIP IN,Moving,0.33,1015.00,765.44,0.00,Admin,NaN,"17-1/2"""""
51,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:41:21,2021-10-13 03:43:16,TRIP IN,Connection,1.83,1015.00,773.91,0.00,Admin,NaN,"17-1/2"""""
52,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:43:16,2021-10-13 03:44:31,TRIP IN,Moving,1.17,1015.00,789.18,0.00,Admin,NaN,"17-1/2"""""
53,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:44:31,2021-10-13 03:46:21,TRIP IN,Connection,1.75,1015.00,805.12,0.00,Admin,NaN,"17-1/2"""""
54,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:46:21,2021-10-13 03:47:51,TRIP IN,Moving,1.42,1015.00,819.37,0.00,Admin,NaN,"17-1/2"""""
55,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:47:51,2021-10-13 03:49:36,TRIP IN,Connection,1.67,1015.00,834.67,0.00,Admin,NaN,"17-1/2"""""
56,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:49:36,2021-10-13 03:51:01,TRIP IN,Moving,1.33,1015.00,848.78,0.00,Admin,NaN,"17-1/2"""""
57,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:51:01,2021-10-13 03:52:41,TRIP IN,Connection,1.58,1015.00,864.03,0.00,Admin,NaN,"17-1/2"""""
58,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:52:41,2021-10-13 03:54:21,TRIP IN,Moving,1.50,1015.00,884.92,0.00,Admin,NaN,"17-1/2"""""
59,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:54:21,2021-10-13 03:56:16,TRIP IN,Connection,1.83,1015.00,893.64,0.00,Admin,NaN,"17-1/2"""""
60,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:56:16,2021-10-13 03:58:01,TRIP IN,Moving,1.67,1015.00,907.05,0.00,Admin,NaN,"17-1/2"""""
61,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:58:01,2021-10-13 04:12:41,TRIP IN,Connection,14.50,1015.00,922.67,0.00,Admin,NaN,"17-1/2"""""
62,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:12:41,2021-10-13 04:19:51,TRIP IN,Stationary,6.58,1015.00,923.13,0.00,Admin,NaN,"17-1/2"""""
63,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:19:51,2021-10-13 04:20:41,TRIP IN,Moving,0.75,1015.00,925.88,0.00,Admin,NaN,"17-1/2"""""
64,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:20:41,2021-10-13 04:33:36,TRIP IN,Stationary,12.83,1015.00,927.40,0.00,Admin,NaN,"17-1/2"""""
65,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:33:36,2021-10-13 04:36:41,TRIP IN,Moving,2.84,1015.00,947.06,0.00,Admin,NaN,"17-1/2"""""
66,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:36:41,2021-10-13 04:40:31,TRIP IN,Connection,3.75,1015.00,952.47,0.00,Admin,NaN,"17-1/2"""""
67,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:40:31,2021-10-13 04:43:21,TRIP IN,Moving,2.75,1015.00,965.37,0.00,Admin,NaN,"17-1/2"""""
68,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:43:21,2021-10-13 04:46:01,TRIP IN,Connection,2.58,1015.00,981.64,0.00,Admin,NaN,"17-1/2"""""
69,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:46:01,2021-10-13 04:46:46,TRIP IN,Wash Up/Down,0.67,1015.00,981.50,0.00,Admin,NaN,"17-1/2"""""
70,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:46:46,2021-10-13 04:47:26,TRIP IN,Circulation,0.42,1015.00,982.46,0.00,Admin,NaN,"17-1/2"""""
71,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:47:26,2021-10-13 04:50:41,TRIP IN,Wash Up/Down,3.17,1015.00,992.97,0.00,Admin,NaN,"17-1/2"""""
72,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:50:41,2021-10-13 04:52:41,TRIP IN,Circulation,1.75,1015.00,1005.55,0.00,Admin,NaN,"17-1/2"""""
73,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:52:41,2021-10-13 04:57:16,TRIP IN,Reaming,4.09,1015.00,1010.16,0.00,Admin,NaN,"17-1/2"""""
74,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:57:16,2021-10-13 05:00:56,TRIP IN,Connection,3.41,1015.00,1010.60,0.00,Admin,NaN,"17-1/2"""""
75,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:00:56,2021-10-13 05:02:06,TRIP IN,Circulation,1.08,1015.00,1010.38,0.00,Admin,NaN,"17-1/2"""""
76,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:02:06,2021-10-13 05:03:31,TRIP IN,Reaming,1.08,1015.00,1011.78,0.00,Admin,NaN,"17-1/2"""""
77,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:03:31,2021-10-13 06:30:36,DRILLING FORMATION,Rotary Drilling,87.00,1040.72,1026.08,25.72,Admin,NaN,"17-1/2"""""
78,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:30:36,2021-10-13 06:39:06,DRILLING FORMATION,Reaming,8.42,1040.72,1021.67,0.00,Admin,NaN,"17-1/2"""""
79,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:39:06,2021-10-13 06:43:21,DRILLING FORMATION,Rotary Drilling,4.08,1040.72,1040.37,0.00,Admin,NaN,"17-1/2"""""
80,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:43:21,2021-10-13 06:46:41,DRILLING FORMATION,Reaming,3.25,1040.72,1040.22,0.00,Admin,NaN,"17-1/2"""""
81,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:46:41,2021-10-13 08:07:47,DRILLING FORMATION,Rotary Drilling,81.02,1070.05,1055.71,29.32,Admin,NaN,"17-1/2"""""
82,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:07:47,2021-10-13 08:15:37,DRILLING FORMATION,Reaming,7.75,1070.05,1048.70,0.00,Admin,NaN,"17-1/2"""""
83,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:15:37,2021-10-13 08:16:12,DRILLING FORMATION,Wash Up/Down,0.42,1070.05,1065.72,0.00,Admin,NaN,"17-1/2"""""
84,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:16:12,2021-10-13 08:20:12,DRILLING FORMATION,Connection,3.75,1070.05,1069.41,0.00,Admin,NaN,"17-1/2"""""
85,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:20:12,2021-10-13 08:23:02,DRILLING FORMATION,Reaming,2.75,1070.05,1069.41,0.00,Admin,NaN,"17-1/2"""""
86,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:23:02,2021-10-13 09:48:32,DRILLING FORMATION,Rotary Drilling,85.42,1099.76,1085.17,29.71,Admin,NaN,"17-1/2"""""
87,ON REVIEW,2021-10-13 00:00:00,2021-10-13 09:48:32,2021-10-13 10:00:47,DRILLING FORMATION,Reaming,12.08,1099.76,1092.84,0.00,Admin,NaN,"17-1/2"""""
88,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:00:47,2021-10-13 10:03:37,DRILLING FORMATION,Connection,2.66,1099.76,1099.30,0.00,Admin,NaN,"17-1/2"""""
89,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:03:37,2021-10-13 10:06:22,DRILLING FORMATION,Wash Up/Down,2.50,1099.90,1099.64,0.00,Admin,NaN,"17-1/2"""""
90,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:06:22,2021-10-13 10:06:57,DRILLING FORMATION,Slide Drilling,0.50,1100.04,1100.02,0.07,Admin,NaN,"17-1/2"""""
91,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:06:57,2021-10-13 11:36:47,DRILLING FORMATION,Rotary Drilling,89.58,1129.18,1104.95,29.13,Admin,NaN,"17-1/2"""""
92,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:36:47,2021-10-13 11:47:12,DRILLING FORMATION,Reaming,10.17,1129.18,1122.57,0.00,Admin,NaN,"17-1/2"""""
93,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:47:12,2021-10-13 11:50:17,DRILLING FORMATION,Connection,2.91,1129.18,1128.48,0.00,Admin,NaN,"17-1/2"""""
94,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:50:17,2021-10-13 11:50:32,DRILLING FORMATION,Look and define,0.00,1129.18,1128.29,0.00,Admin,NaN,"17-1/2"""""
95,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:50:32,2021-10-13 11:54:47,DRILLING FORMATION,Reaming,4.17,1129.18,1128.52,0.00,Admin,NaN,"17-1/2"""""
96,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:54:47,2021-10-13 12:33:22,DRILLING FORMATION,Rotary Drilling,38.50,1141.49,1135.30,12.30,Admin,NaN,"17-1/2"""""
97,ON REVIEW,2021-10-13 00:00:00,2021-10-13 12:33:22,2021-10-13 12:39:17,DRILLING FORMATION,Reaming,5.83,1141.49,1135.40,0.00,Admin,NaN,"17-1/2"""""
98,ON REVIEW,2021-10-13 00:00:00,2021-10-13 12:39:32,2021-10-13 13:34:42,DRILLING FORMATION,Rotary Drilling,55.08,1158.69,1150.35,17.18,Admin,NaN,"17-1/2"""""
99,ON REVIEW,2021-10-13 00:00:00,2021-10-13 13:34:42,2021-10-13 13:46:47,DRILLING FORMATION,Reaming,11.75,1158.79,1155.43,0.00,Admin,NaN,"17-1/2"""""

In [11]:
from importlib import reload
reload(Activity)
Output = Activity.labelStand_v3(Data)
with pd.option_context('display.max_rows', 200):
    display(Output[0:100])

,STATUS,Date,Start Time,End Time,ACTIVITY,SUB-ACTIVITY,Duration (Minutes),Hole Depth (Max),Bit Depth(mean),Drilling Meterage (m),...,Stand Meterage (m) (Drilling),Stand Stand Duration (hrs),Stand On Bottom Hours,Rotate Drilling Time (Minutes),Slide Drilling Time (Minutes),Reaming Time (Minutes),Connection Time (Minutes),Stand Group,CONNECTION-ACTIVITY,Stand Duration (hrs)
0,ON REVIEW,2021-10-12 00:00:00,2021-10-12 21:00:01,2021-10-12 21:35:51,TRIP OUT,Connection,35.75,1015.00,0.00,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,35.75,,Connection--1,0.00
1,ON REVIEW,2021-10-12 00:00:00,2021-10-12 21:35:51,2021-10-12 23:20:01,OTHER,Connection,104.08,1015.00,0.00,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,104.08,,Connection--2,1.73
2,ON REVIEW,2021-10-12 00:00:00,2021-10-12 23:20:01,2021-10-13 00:14:41,MAKE UP BHA,MAKE UP BHA,54.58,1015.00,3.80,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--2,,0.00
3,ON REVIEW,2021-10-13 00:00:00,2021-10-13 00:14:41,2021-10-13 01:28:56,TRIP IN,Connection,73.75,1015.00,53.76,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,73.75,,Connection--3,2.14
4,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:28:56,2021-10-13 01:29:46,TRIP IN,Moving,0.58,1015.00,67.40,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--3,,0.00
5,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:29:46,2021-10-13 01:43:06,TRIP IN,Connection,13.25,1015.00,83.51,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,13.25,,Connection--4,0.23
6,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:43:06,2021-10-13 01:47:01,TRIP IN,Stationary,3.67,1015.00,84.36,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--4,,0.00
7,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:47:01,2021-10-13 01:47:56,TRIP IN,Moving,0.75,1015.00,91.58,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--4,,0.00
8,ON REVIEW,2021-10-13 00:00:00,2021-10-13 01:47:56,2021-10-13 02:08:31,TRIP IN,Connection,20.08,1015.00,93.03,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,20.08,,Connection--5,0.41
9,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:08:31,2021-10-13 02:09:26,TRIP IN,Stationary,0.67,1015.00,102.59,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--5,,0.00
10,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:09:26,2021-10-13 02:19:56,TRIP IN,Connection,10.08,1015.00,107.95,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,10.08,,Connection--6,0.18
11,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:19:56,2021-10-13 02:20:26,TRIP IN,Stationary,0.42,1015.00,112.45,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--6,,0.00
12,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:20:26,2021-10-13 02:21:46,TRIP IN,Moving,0.91,1015.00,114.17,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--6,,0.00
13,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:21:46,2021-10-13 02:24:41,TRIP IN,Connection,2.66,1015.00,139.84,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,2.66,,Connection--7,0.07
14,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:24:41,2021-10-13 02:25:06,TRIP IN,Moving,0.33,1015.00,141.68,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--7,,0.00
15,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:25:06,2021-10-13 02:27:01,TRIP IN,Connection,1.66,1015.00,167.94,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.66,,Connection--8,0.03
16,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:27:01,2021-10-13 02:27:31,TRIP IN,Moving,0.33,1015.00,171.25,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--8,,0.00
17,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:27:31,2021-10-13 02:31:26,TRIP IN,Connection,3.24,1015.00,195.99,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,3.24,,Connection--9,0.06
18,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:31:26,2021-10-13 02:32:01,TRIP IN,Stationary,0.50,1015.00,196.92,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--9,,0.00
19,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:32:01,2021-10-13 02:33:26,TRIP IN,Circulation,1.25,1015.00,196.99,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--9,,0.00
20,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:33:26,2021-10-13 02:33:51,TRIP IN,Moving,0.33,1015.00,199.56,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--9,,0.00
21,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:33:51,2021-10-13 02:52:21,TRIP IN,Connection,16.42,1015.00,282.30,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,16.42,,Connection--10,0.31
22,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:52:21,2021-10-13 02:53:11,TRIP IN,Moving,0.75,1015.00,368.04,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--10,,0.00
23,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:53:11,2021-10-13 02:54:46,TRIP IN,Connection,1.50,1015.00,390.53,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.50,,Connection--11,0.04
24,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:54:46,2021-10-13 02:55:51,TRIP IN,Moving,0.92,1015.00,407.46,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--11,,0.00
25,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:55:51,2021-10-13 02:57:26,TRIP IN,Connection,1.50,1015.00,419.88,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.50,,Connection--12,0.04
26,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:57:26,2021-10-13 02:58:21,TRIP IN,Moving,0.75,1015.00,437.88,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--12,,0.00
27,ON REVIEW,2021-10-13 00:00:00,2021-10-13 02:58:21,2021-10-13 03:00:06,TRIP IN,Connection,1.67,1015.00,448.88,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.67,,Connection--13,0.04
28,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:00:06,2021-10-13 03:01:01,TRIP IN,Moving,0.49,1015.00,454.72,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--13,,0.00
29,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:01:01,2021-10-13 03:08:01,TRIP IN,Connection,6.59,1015.00,461.34,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,6.59,,Connection--14,0.12
30,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:08:01,2021-10-13 03:09:11,TRIP IN,Moving,1.08,1015.00,493.00,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--14,,0.00
31,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:09:11,2021-10-13 03:10:51,TRIP IN,Connection,1.58,1015.00,506.51,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.58,,Connection--15,0.04
32,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:10:51,2021-10-13 03:12:01,TRIP IN,Moving,0.92,1015.00,524.55,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--15,,0.00
33,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:12:01,2021-10-13 03:13:41,TRIP IN,Connection,1.58,1015.00,534.73,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.58,,Connection--16,0.04
34,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:13:41,2021-10-13 03:14:46,TRIP IN,Moving,1.00,1015.00,551.54,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--16,,0.00
35,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:14:46,2021-10-13 03:16:31,TRIP IN,Connection,1.67,1015.00,567.81,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.67,,Connection--17,0.04
36,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:16:31,2021-10-13 03:17:46,TRIP IN,Moving,1.08,1015.00,585.92,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--17,,0.00
37,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:17:46,2021-10-13 03:19:41,TRIP IN,Connection,1.83,1015.00,597.70,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.83,,Connection--18,0.05
38,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:19:41,2021-10-13 03:20:51,TRIP IN,Moving,1.00,1015.00,616.34,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--18,,0.00
39,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:20:51,2021-10-13 03:22:36,TRIP IN,Connection,1.67,1015.00,627.10,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.67,,Connection--19,0.04
40,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:22:36,2021-10-13 03:23:41,TRIP IN,Moving,1.00,1015.00,638.63,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--19,,0.00
41,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:23:41,2021-10-13 03:25:51,TRIP IN,Connection,2.08,1015.00,656.80,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,2.08,,Connection--20,0.05
42,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:25:51,2021-10-13 03:27:01,TRIP IN,Moving,1.00,1015.00,673.94,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--20,,0.00
43,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:27:01,2021-10-13 03:29:06,TRIP IN,Connection,2.00,1015.00,686.79,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,2.00,,Connection--21,0.05
44,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:29:06,2021-10-13 03:30:16,TRIP IN,Moving,1.08,1015.00,698.52,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--21,,0.00
45,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:30:16,2021-10-13 03:32:26,TRIP IN,Connection,2.08,1015.00,715.55,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,2.08,,Connection--22,0.05
46,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:32:26,2021-10-13 03:33:41,TRIP IN,Moving,1.08,1015.00,735.30,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--22,,0.00
47,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:33:41,2021-10-13 03:35:11,TRIP IN,Connection,1.42,1015.00,745.67,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.42,,Connection--23,0.04
48,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:35:11,2021-10-13 03:36:26,TRIP IN,Moving,0.91,1015.00,761.64,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--23,,0.00
49,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:36:26,2021-10-13 03:40:51,TRIP IN,Connection,4.17,1015.00,764.19,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,4.17,,Connection--24,0.08
50,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:40:51,2021-10-13 03:41:21,TRIP IN,Moving,0.33,1015.00,765.44,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--24,,0.00
51,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:41:21,2021-10-13 03:43:16,TRIP IN,Connection,1.83,1015.00,773.91,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.83,,Connection--25,0.04
52,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:43:16,2021-10-13 03:44:31,TRIP IN,Moving,1.17,1015.00,789.18,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--25,,0.00
53,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:44:31,2021-10-13 03:46:21,TRIP IN,Connection,1.75,1015.00,805.12,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.75,,Connection--26,0.05
54,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:46:21,2021-10-13 03:47:51,TRIP IN,Moving,1.42,1015.00,819.37,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--26,,0.00
55,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:47:51,2021-10-13 03:49:36,TRIP IN,Connection,1.67,1015.00,834.67,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.67,,Connection--27,0.05
56,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:49:36,2021-10-13 03:51:01,TRIP IN,Moving,1.33,1015.00,848.78,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--27,,0.00
57,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:51:01,2021-10-13 03:52:41,TRIP IN,Connection,1.58,1015.00,864.03,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.58,,Connection--28,0.05
58,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:52:41,2021-10-13 03:54:21,TRIP IN,Moving,1.50,1015.00,884.92,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--28,,0.00
59,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:54:21,2021-10-13 03:56:16,TRIP IN,Connection,1.83,1015.00,893.64,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,1.83,,Connection--29,0.06
60,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:56:16,2021-10-13 03:58:01,TRIP IN,Moving,1.67,1015.00,907.05,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--29,,0.00
61,ON REVIEW,2021-10-13 00:00:00,2021-10-13 03:58:01,2021-10-13 04:12:41,TRIP IN,Connection,14.50,1015.00,922.67,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,14.50,,Connection--30,0.27
62,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:12:41,2021-10-13 04:19:51,TRIP IN,Stationary,6.58,1015.00,923.13,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--30,,0.00
63,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:19:51,2021-10-13 04:20:41,TRIP IN,Moving,0.75,1015.00,925.88,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--30,,0.00
64,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:20:41,2021-10-13 04:33:36,TRIP IN,Stationary,12.83,1015.00,927.40,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--30,,0.00
65,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:33:36,2021-10-13 04:36:41,TRIP IN,Moving,2.84,1015.00,947.06,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--30,,0.00
66,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:36:41,2021-10-13 04:40:31,TRIP IN,Connection,3.75,1015.00,952.47,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,3.75,,Connection--31,0.45
67,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:40:31,2021-10-13 04:43:21,TRIP IN,Moving,2.75,1015.00,965.37,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--31,,0.00
68,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:43:21,2021-10-13 04:46:01,TRIP IN,Connection,2.58,1015.00,981.64,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,2.58,,Connection--32,0.09
69,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:46:01,2021-10-13 04:46:46,TRIP IN,Wash Up/Down,0.67,1015.00,981.50,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--32,,0.00
70,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:46:46,2021-10-13 04:47:26,TRIP IN,Circulation,0.42,1015.00,982.46,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--32,,0.00
71,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:47:26,2021-10-13 04:50:41,TRIP IN,Wash Up/Down,3.17,1015.00,992.97,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--32,,0.00
72,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:50:41,2021-10-13 04:52:41,TRIP IN,Circulation,1.75,1015.00,1005.55,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--32,,0.00
73,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:52:41,2021-10-13 04:57:16,TRIP IN,Reaming,4.09,1015.00,1010.16,0.00,...,0.00,0.0,0.00,0.00,0.0,4.09,0.00,Stand Group--32,,0.00
74,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:57:16,2021-10-13 05:00:56,TRIP IN,Connection,3.41,1015.00,1010.60,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,3.41,,Connection--33,0.23
75,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:00:56,2021-10-13 05:02:06,TRIP IN,Circulation,1.08,1015.00,1010.38,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--33,Post-Connection--33,0.00
76,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:02:06,2021-10-13 05:03:31,TRIP IN,Reaming,1.08,1015.00,1011.78,0.00,...,0.00,0.0,0.00,0.00,0.0,1.08,0.00,Stand Group--33,Post-Connection--33,0.00
77,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:03:31,2021-10-13 06:30:36,DRILLING FORMATION,Rotary Drilling,87.00,1040.72,1026.08,25.72,...,0.00,0.0,0.00,87.00,0.0,0.00,0.00,Stand Group--33,,0.00
78,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:30:36,2021-10-13 06:39:06,DRILLING FORMATION,Reaming,8.42,1040.72,1021.67,0.00,...,0.00,0.0,0.00,0.00,0.0,8.42,0.00,Stand Group--33,,0.00
79,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:39:06,2021-10-13 06:43:21,DRILLING FORMATION,Rotary Drilling,4.08,1040.72,1040.37,0.00,...,0.00,0.0,0.00,4.08,0.0,0.00,0.00,Stand Group--33,,0.00
80,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:43:21,2021-10-13 06:46:41,DRILLING FORMATION,Reaming,3.25,1040.72,1040.22,0.00,...,0.00,0.0,0.00,0.00,0.0,3.25,0.00,Stand Group--33,,0.00
81,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:46:41,2021-10-13 08:07:47,DRILLING FORMATION,Rotary Drilling,81.02,1070.05,1055.71,29.32,...,0.00,0.0,0.00,81.02,0.0,0.00,0.00,Stand Group--33,,0.00
82,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:07:47,2021-10-13 08:15:37,DRILLING FORMATION,Reaming,7.75,1070.05,1048.70,0.00,...,0.00,0.0,0.00,0.00,0.0,7.75,0.00,Stand Group--33,Pre-Connection--34,0.00
83,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:15:37,2021-10-13 08:16:12,DRILLING FORMATION,Wash Up/Down,0.42,1070.05,1065.72,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--33,Pre-Connection--34,0.00
84,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:16:12,2021-10-13 08:20:12,DRILLING FORMATION,Connection,3.75,1070.05,1069.41,0.00,...,55.04,0.0,2.87,0.00,0.0,0.00,3.75,,Connection--34,3.30
85,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:20:12,2021-10-13 08:23:02,DRILLING FORMATION,Reaming,2.75,1070.05,1069.41,0.00,...,0.00,0.0,0.00,0.00,0.0,2.75,0.00,Stand Group--34,Post-Connection--34,0.00
86,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:23:02,2021-10-13 09:48:32,DRILLING FORMATION,Rotary Drilling,85.42,1099.76,1085.17,29.71,...,0.00,0.0,0.00,85.42,0.0,0.00,0.00,Stand Group--34,,0.00
87,ON REVIEW,2021-10-13 00:00:00,2021-10-13 09:48:32,2021-10-13 10:00:47,DRILLING FORMATION,Reaming,12.08,1099.76,1092.84,0.00,...,0.00,0.0,0.00,0.00,0.0,12.08,0.00,Stand Group--34,Pre-Connection--35,0.00
88,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:00:47,2021-10-13 10:03:37,DRILLING FORMATION,Connection,2.66,1099.76,1099.30,0.00,...,29.71,0.0,1.42,0.00,0.0,0.00,2.66,,Connection--35,1.72
89,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:03:37,2021-10-13 10:06:22,DRILLING FORMATION,Wash Up/Down,2.50,1099.90,1099.64,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--35,,0.00
90,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:06:22,2021-10-13 10:06:57,DRILLING FORMATION,Slide Drilling,0.50,1100.04,1100.02,0.07,...,0.00,0.0,0.00,0.00,0.5,0.00,0.00,Stand Group--35,,0.00
91,ON REVIEW,2021-10-13 00:00:00,2021-10-13 10:06:57,2021-10-13 11:36:47,DRILLING FORMATION,Rotary Drilling,89.58,1129.18,1104.95,29.13,...,0.00,0.0,0.00,89.58,0.0,0.00,0.00,Stand Group--35,,0.00
92,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:36:47,2021-10-13 11:47:12,DRILLING FORMATION,Reaming,10.17,1129.18,1122.57,0.00,...,0.00,0.0,0.00,0.00,0.0,10.17,0.00,Stand Group--35,,0.00
93,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:47:12,2021-10-13 11:50:17,DRILLING FORMATION,Connection,2.91,1129.18,1128.48,0.00,...,29.20,0.0,1.50,0.00,0.0,0.00,2.91,,Connection--36,1.76
94,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:50:17,2021-10-13 11:50:32,DRILLING FORMATION,Look and define,0.00,1129.18,1128.29,0.00,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,Stand Group--36,Post-Connection--36,0.00
95,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:50:32,2021-10-13 11:54:47,DRILLING FORMATION,Reaming,4.17,1129.18,1128.52,0.00,...,0.00,0.0,0.00,0.00,0.0,4.17,0.00,Stand Group--36,Post-Connection--36,0.00
96,ON REVIEW,2021-10-13 00:00:00,2021-10-13 11:54:47,2021-10-13 12:33:22,DRILLING FORMATION,Rotary Drilling,38.50,1141.49,1135.30,12.30,...,0.00,0.0,0.00,38.50,0.0,0.00,0.00,Stand Group--36,,0.00
97,ON REVIEW,2021-10-13 00:00:00,2021-10-13 12:33:22,2021-10-13 12:39:17,DRILLING FORMATION,Reaming,5.83,1141.49,1135.40,0.00,...,0.00,0.0,0.00,0.00,0.0,5.83,0.00,Stand Group--36,,0.00
98,ON REVIEW,2021-10-13 00:00:00,2021-10-13 12:39:32,2021-10-13 13:34:42,DRILLING FORMATION,Rotary Drilling,55.08,1158.69,1150.35,17.18,...,0.00,0.0,0.00,55.08,0.0,0.00,0.00,Stand Group--36,,0.00
99,ON REVIEW,2021-10-13 00:00:00,2021-10-13 13:34:42,2021-10-13 13:46:47,DRILLING FORMATION,Reaming,11.75,1158.79,1155.43,0.00,...,0.00,0.0,0.00,0.00,0.0,11.75,0.00,Stand Group--36,Pre-Connection--37,0.00

In [59]:
# idx_reaming = MasterReport_DF[MasterReport_DF.loc[idx_start:idx_end,"SUB-ACTIVITY"] == "Reaming"].index
reload(Activity)
Output = Activity.labelStand_v3(Data)
Output["CONNECTION-ACTIVITY"] = ""
idx_start = 75
idx_end =83
iii = 33
Output_temp = Output.loc[idx_start:idx_end,:]

idx_reaming = Output_temp.loc[Output_temp["SUB-ACTIVITY"]=="Reaming"].index.tolist()
print(idx_reaming)
if len(idx_reaming)>=2:
    idx_PreConnection = idx_reaming[-1]
    idx_PostConnection = idx_reaming[0]
    Output.loc[idx_PreConnection:idx_end, "CONNECTION-ACTIVITY"] = "Pre-Connection--" + str(iii+1)
    Output.loc[idx_start:idx_PostConnection, "CONNECTION-ACTIVITY"] = "Post-Connection--"+ str(iii)


display(Output.loc[idx_start-1:idx_end+1,:])

[76, 78, 80, 82]

,STATUS,Date,Start Time,End Time,ACTIVITY,SUB-ACTIVITY,Duration (Minutes),Hole Depth (Max),Bit Depth(mean),Drilling Meterage (m),...,Section,Stand Meterage (m) (Drilling),Stand Stand Duration (hrs),Stand On Bottom Hours,Rotate Drilling Time (Minutes),Slide Drilling Time (Minutes),Reaming Time (Minutes),Connection Time (Minutes),Stand Group,CONNECTION-ACTIVITY
74,ON REVIEW,2021-10-13 00:00:00,2021-10-13 04:57:16,2021-10-13 05:00:56,TRIP IN,Connection,3.41,1015.00,1010.60,0.00,...,"17-1/2""""",0.00,0.23,0.00,0.00,0.0,0.00,3.41,,
75,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:00:56,2021-10-13 05:02:06,TRIP IN,Circulation,1.08,1015.00,1010.38,0.00,...,"17-1/2""""",0.00,0.00,0.00,0.00,0.0,0.00,0.00,Stand Group--33,Post-Connection--33
76,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:02:06,2021-10-13 05:03:31,TRIP IN,Reaming,1.08,1015.00,1011.78,0.00,...,"17-1/2""""",0.00,0.00,0.00,0.00,0.0,1.08,0.00,Stand Group--33,Post-Connection--33
77,ON REVIEW,2021-10-13 00:00:00,2021-10-13 05:03:31,2021-10-13 06:30:36,DRILLING FORMATION,Rotary Drilling,87.00,1040.72,1026.08,25.72,...,"17-1/2""""",0.00,0.00,0.00,87.00,0.0,0.00,0.00,Stand Group--33,
78,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:30:36,2021-10-13 06:39:06,DRILLING FORMATION,Reaming,8.42,1040.72,1021.67,0.00,...,"17-1/2""""",0.00,0.00,0.00,0.00,0.0,8.42,0.00,Stand Group--33,
79,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:39:06,2021-10-13 06:43:21,DRILLING FORMATION,Rotary Drilling,4.08,1040.72,1040.37,0.00,...,"17-1/2""""",0.00,0.00,0.00,4.08,0.0,0.00,0.00,Stand Group--33,
80,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:43:21,2021-10-13 06:46:41,DRILLING FORMATION,Reaming,3.25,1040.72,1040.22,0.00,...,"17-1/2""""",0.00,0.00,0.00,0.00,0.0,3.25,0.00,Stand Group--33,
81,ON REVIEW,2021-10-13 00:00:00,2021-10-13 06:46:41,2021-10-13 08:07:47,DRILLING FORMATION,Rotary Drilling,81.02,1070.05,1055.71,29.32,...,"17-1/2""""",0.00,0.00,0.00,81.02,0.0,0.00,0.00,Stand Group--33,
82,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:07:47,2021-10-13 08:15:37,DRILLING FORMATION,Reaming,7.75,1070.05,1048.70,0.00,...,"17-1/2""""",0.00,0.00,0.00,0.00,0.0,7.75,0.00,Stand Group--33,Pre-Connection--34
83,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:15:37,2021-10-13 08:16:12,DRILLING FORMATION,Wash Up/Down,0.42,1070.05,1065.72,0.00,...,"17-1/2""""",0.00,0.00,0.00,0.00,0.0,0.00,0.00,Stand Group--33,Pre-Connection--34
84,ON REVIEW,2021-10-13 00:00:00,2021-10-13 08:16:12,2021-10-13 08:20:12,DRILLING FORMATION,Connection,3.75,1070.05,1069.41,0.00,...,"17-1/2""""",55.04,3.30,2.87,0.00,0.0,0.00,3.75,,

In [9]:
reload(Activity)
Output_2 = Activity.labelStand_v3(Data)
with pd.option_context('display.max_rows', 200):
    display(Output_2[0:100])

KeyError: "['Stand Duration (hrs)'] not in index"

In [6]:
reload(Activity)
list_column = []
for i in Data.columns:
    # print(i)
    list_column.append(i)
print(list_column)
# Activity.labelStand_v3(Data)

['STATUS', 'Date', 'Start Time', 'End Time', 'ACTIVITY', 'SUB-ACTIVITY', 'Duration (Minutes)', 'Hole Depth (Max)', 'Bit Depth(mean)', 'Drilling Meterage (m)', 'PIC', 'Remarks', 'Section', 'Stand Meterage (m) (Drilling)', 'Stand Stand Duration (hrs)', 'Stand On Bottom Hours', 'Rotate Drilling Time (Minutes)', 'Slide Drilling Time (Minutes)', 'Reaming Time (Minutes)', 'Connection Time (Minutes)', 'Stand Group', 'CONNECTION-ACTIVITY']

In [21]:
from Streamlit_App import IO_Data
StartDateTime_select = "2021-10-07 21:00:00"
EndDateTime_select = "2021-10-10 03:00:00"
well_id = 156
rt5s_Data = IO_Data.getActivityData_v2(well_id, StartDateTime_select, EndDateTime_select)

In [23]:
rt5s_Data.to_excel("realtime_manual.xlsx")

In [14]:
aa = [
    'Date', 'Start Time', 'End Time', 'date_time', 'Duration (Minutes)', 'Hole Depth (Max)', 'Bit Depth(mean)', 'Drilling Meterage (m)', 'SUB-ACTIVITY', 'ACTIVITY', 'MERGE_SubActivity-Activity', 'PIC', 'Remarks', 'Section', 'Total Stand Drilling Meterage (m)', 'Total Stand Duration (hrs)', 'On Bottom state (hrs)', 'Rotate Drilling Time (Minutes)', 'Slide Drilling Time (Minutes)', 'Reaming Time (Minutes)', 'Connection Time (Minutes)', 'Stand Group', 'CONNECTION-ACTIVITY', 'STATUS'
]
for i in aa:
    print('"' + i + '",')

"Date",
"Start Time",
"End Time",
"date_time",
"Duration (Minutes)",
"Hole Depth (Max)",
"Bit Depth(mean)",
"Drilling Meterage (m)",
"SUB-ACTIVITY",
"ACTIVITY",
"MERGE_SubActivity-Activity",
"PIC",
"Remarks",
"Section",
"Total Stand Drilling Meterage (m)",
"Total Stand Duration (hrs)",
"On Bottom state (hrs)",
"Rotate Drilling Time (Minutes)",
"Slide Drilling Time (Minutes)",
"Reaming Time (Minutes)",
"Connection Time (Minutes)",
"Stand Group",
"CONNECTION-ACTIVITY",
"STATUS",

In [7]:
from Streamlit_App import IO_Data,Activity
import pandas as pd
StartDateTime_select = "2010-10-07 21:00:00"
EndDateTime_select = "2030-10-10 03:00:00"
well_id_list = [140,146,150]
well_name_list = ['SMP AA-03','SMP AAE-05','SMP AAE-06ST3']
section_select = '17-1/2"'
Table_list = []
for wid_temp,wellname in zip(well_id_list,well_name_list):
    # ActivitySummary_DF_Dome = 
    welltemp = Activity.labelStand_v3(IO_Data.DomeGetData_v2(wid_temp, StartDateTime_select,EndDateTime_select, table_type="Activity Summary"))
    welltemp['WELLNAME'] = wellname
    Table_list.append(welltemp)
OffsetWell_DF_RAW = pd.concat(Table_list, ignore_index=True)
OffsetWell_DF_RAW = OffsetWell_DF_RAW[OffsetWell_DF_RAW['Section']==section_select]
display(OffsetWell_DF_RAW)

get Activity Summary data/table from DOME
get Activity Summary data/table from DOME
get Activity Summary data/table from DOME

,wid,Date,Start Time,End Time,Duration (Minutes),SUB-ACTIVITY,ACTIVITY,CONNECTION-ACTIVITY,Hole Depth (Max),Bit Depth(mean),...,Connection Time (Minutes),On Bottom state (hrs),Total Stand Duration (hrs),Total Stand Drilling Meterage (m),Stand Group,PIC,Section,Remarks,zeros,WELLNAME
346,140,2021-04-25,2021-04-25 21:17:52,2021-04-25 21:38:37,20.75000,Make Up Bha,MAKE UP BHA,,405.0,0.00,...,0.00,0.0,0.00,0.0,Stand Group--123,MIH,"17-1/2""","Make up BHA#4 17.5"" TCI Bit",0,SMP AA-03
347,140,2021-04-25,2021-04-25 21:38:37,2021-04-25 23:43:28,124.85000,Cementing Job,CEMENTING JOB,,405.0,0.00,...,0.00,0.0,0.00,0.0,Stand Group--123,MIH,"17-1/2""",Offline Cementing Top Job,0,SMP AA-03
348,140,2021-04-26,2021-04-25 23:43:28,2021-04-26 00:40:03,56.58330,Make Up Bha,MAKE UP BHA,,405.0,32.25,...,0.00,0.0,0.00,0.0,Stand Group--123,MIH,"17-1/2""",L/D DC/ M/U BHA,0,SMP AA-03
349,140,2021-04-26,2021-04-26 00:40:03,2021-04-26 00:46:48,6.75000,Connection,TRIP IN,Connection--124,405.0,80.33,...,6.75,0.0,25.78,0.0,,MIH,"17-1/2""",Make up BHA#4,0,SMP AA-03
350,140,2021-04-26,2021-04-26 00:46:48,2021-04-26 00:49:18,2.50000,Moving,TRIP IN,,405.0,80.00,...,0.00,0.0,0.00,0.0,Stand Group--124,MIH,"17-1/2""",Make Up BHA,0,SMP AA-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7379,150,2021-09-01,2021-09-01 04:50:14,2021-09-01 04:54:39,4.41667,Stationary,RUNNING CASING IN,,482.2,473.07,...,0.00,0.0,0.00,0.0,Stand Group--606,MIH,"17-1/2""",0,0,SMP AAE-06ST3
7380,150,2021-09-01,2021-09-01 04:54:39,2021-09-01 04:58:54,4.25000,Moving,RUNNING CASING IN,,482.2,479.89,...,0.00,0.0,0.00,0.0,Stand Group--606,MIH,"17-1/2""",0,0,SMP AAE-06ST3
7381,150,2021-09-01,2021-09-01 04:58:54,2021-09-01 05:06:59,8.08333,Stationary,RUNNING CASING IN,,482.2,479.53,...,0.00,0.0,0.00,0.0,Stand Group--606,MIH,"17-1/2""",0,0,SMP AAE-06ST3
7382,150,2021-09-01,2021-09-01 05:06:59,2021-09-01 06:00:00,0.00000,Moving,RUNNING CASING IN,,0.0,0.00,...,0.00,0.0,0.00,0.0,Stand Group--606,MIH,"17-1/2""",0,0,SMP AAE-06ST3
7383,150,2021-09-01,2021-09-01 06:00:00,2021-09-01 20:50:33,0.00000,Other,OTHER,,0.0,0.00,...,0.00,0.0,0.00,0.0,Stand Group--606,MIH,"17-1/2""",M/U stinger,0,SMP AAE-06ST3

In [10]:
OffsetWell_OBH_ROP_DF = OffsetWell_DF_RAW.groupby('WELLNAME').agg(
    {
        "Total Stand Drilling Meterage (m)":'mean',
        'On Bottom state (hrs)':'mean',
        'Total Stand Duration (hrs)':'mean'
    }
).reset_index()

display(OffsetWell_OBH_ROP_DF)
# OBH_ROP_DF = Data_Temp.copy()

# OBH_ROP_DF = OBH_ROP_DF[OBH_ROP_DF['SUB-ACTIVITY']=='Connection']

# OBH_ROP_DF = OBH_ROP_DF[OBH_ROP_DF['Total Stand Drilling Meterage (m)']!=0]
OffsetWell_OBH_ROP_DF['On Bottom ROP (m/hr)'] = OffsetWell_OBH_ROP_DF['Total Stand Drilling Meterage (m)'] / (OffsetWell_OBH_ROP_DF['On Bottom state (hrs)'])
OffsetWell_OBH_ROP_DF['Avg. ROP Per Stand'] = OffsetWell_OBH_ROP_DF['Total Stand Drilling Meterage (m)'] / (OffsetWell_OBH_ROP_DF['Total Stand Duration (hrs)'])
# OBH_ROP_DF
import plotly.express as px
fig = px.bar(OffsetWell_OBH_ROP_DF, x="WELLNAME", y=['On Bottom ROP (m/hr)','Avg. ROP Per Stand'],
              barmode='group',
             height=400)
fig.show()

,WELLNAME,Total Stand Drilling Meterage (m),On Bottom state (hrs),Total Stand Duration (hrs)
0,SMP AA-03,0.838885,0.060215,0.299276
1,SMP AAE-05,0.687241,0.054385,0.163902
2,SMP AAE-06ST3,0.613516,0.061004,0.152587

In [13]:
OffsetWell_StandTimeBreakdown_DF = OffsetWell_DF_RAW.copy()
idx_logic_activity = OffsetWell_StandTimeBreakdown_DF["ACTIVITY"].isin(["DRILLING FORMATION", 
                                                'CIRCULATE HOLE CLEANING',
                                                'CONNECTION',
                                                'DRILL OUT CEMENT',
                                            ])
OffsetWell_StandTimeBreakdown_DF= OffsetWell_StandTimeBreakdown_DF[idx_logic_activity]

OffsetWell_StandTimeBreakdown_DF = OffsetWell_StandTimeBreakdown_DF.groupby(['WELLNAME','SUB-ACTIVITY']).agg(
    {
        "Duration (Minutes)":'mean',
    }
).reset_index()
OffsetWell_StandTimeBreakdown_DF
figStandTimeBreakdown = px.bar(OffsetWell_StandTimeBreakdown_DF, x='WELLNAME', y=['Duration (Minutes)'],color='SUB-ACTIVITY', width=1000, height=1000)

figStandTimeBreakdown.update_xaxes(type='category')
figStandTimeBreakdown.update_layout(
                # title="Title",
                xaxis=dict(
                    title="Offset Well"
                ),
                yaxis=dict(
                    title="Duration(Minutes)"
                ) ) 
figStandTimeBreakdown.show()
        # st.markdown("#### Stand Break Down by " + WellName_Select + " " + SectionSelect+ " in Hole Section")
        # st.plotly_chart(figStandTimeBreakdown)