In [4]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is D42B-315F

 Directory of c:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\Notebook

12/28/2023  01:44 AM    <DIR>          .
12/28/2023  10:54 AM    <DIR>          ..
12/28/2023  01:44 AM           145,890 00_DataRealtimePipeline.ipynb
               1 File(s)        145,890 bytes
               2 Dir(s)  222,368,690,176 bytes free

In [7]:
import pandas as pd 
import numpy as np 
import requests
import json
import sys
# Now, if you've made changes to 'my_module' and want to reload it
# Path where your library is located
library_path = r'C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\\'

# Add the path to sys.path
sys.path.append(library_path)
from PDU_Func import IO_Data
import datetime
from importlib import reload

reload(IO_Data)

In [8]:
UserAuthDict = {'data':{'user_cid':'1'}}

IO_Data.getAvailableCompanyDF(UserAuthDict)
IO_Data.getAvailableWellDF('MCG', UserAuthDict)

,wid,cid,well_name,rig_name,active_date,end_date,proposed_total_measured_depth,time_master
0,148,74,IJEN 6-2,EPI-9,2022-12-07,2022-12-10,2800,"[{'time_date_start': '2022-12-05', 'time_date_..."
1,155,74,IJN 6-1 ST2,Harmand#01,2021-09-15,2021-11-30,2800,"[{'time_date_start': '2021-09-13', 'time_date_..."
2,240,74,IJN 5-1,IJN 5-1,2023-01-01,2023-05-17,0,[]
3,243,74,IJN 2-1,EPI-9,2023-04-05,2023-06-10,3500,"[{'time_date_start': '2023-04-03', 'time_date_..."
4,255,74,IJN 6-3,EPI-9,2023-06-14,2023-08-31,3000,"[{'time_date_start': '2023-06-12', 'time_date_..."
5,260,74,IJN 6-4,EPI-9,2023-08-01,2023-09-30,3500,"[{'time_date_start': '2023-07-31', 'time_date_..."
6,272,74,IJN 8-1,EPI-9,2023-10-05,2023-11-30,3000,"[{'time_date_start': '2023-10-02', 'time_date_..."
7,283,74,IJN 8-2,EPI-9,2023-11-26,2024-01-31,3500,"[{'time_date_start': '2023-11-20', 'time_date_..."

### getRigActivity

In [9]:
request_json = {
	"wid":243,
	"start_date":"2000-08-04 13:02:47",
	"end_date":"2029-08-04 22:17:30"
}
getRigActivityAPI = "https://pdumitradome.id/dome_api/rtdc/get_drilling_activity"

response = requests.post(
    getRigActivityAPI,
    data=json.dumps(
        request_json,
        indent = 4
    )
)

In [10]:
rigActivityDF = pd.DataFrame(dict(response.json())['data'])
rigActivityDF.sort_values(by='dt', inplace=True)
rigActivityDF.rename(columns={'activity': 'Activity', 'dt':'DateTime'}, inplace=True)
rigActivityDF['DateTime'] = pd.to_datetime(rigActivityDF['DateTime'])


rigActivityDF.to_excel('rigActivityDF.xlsx', index=False)

In [11]:
UserDateRange = {
  "StartDate": datetime.date(2023, 4, 9),
  "StartTime": datetime.time(00, 00),
  "EndDate": datetime.date(2023, 4, 11),
  "EndTime": datetime.time(23, 59)
}
WellInfoDict = {
  "cid": 74,
  "wid": 243,
  "WellName": "IJN 2-1",
  "RigName": "3    EPI-9\nName: rig_name, dtype: string",
  "ActiveDate": "2023-04-05",
  "EndDate": "2023-05-31"
}
UserDateRange

{'StartDate': datetime.date(2023, 4, 9),
 'StartTime': datetime.time(0, 0),
 'EndDate': datetime.date(2023, 4, 11),
 'EndTime': datetime.time(23, 59)}

In [12]:
reload(IO_Data)
RealtimeDF = IO_Data.DomeGetRealtimeSensorData(WellInfoDict, UserDateRange, hours=3)
RealtimeDF

 Download Realtime Sensor Data, 0.0 % Complete
 Download Realtime Sensor Data, 4.0 % Complete
 Download Realtime Sensor Data, 8.0 % Complete
 Download Realtime Sensor Data, 12.0 % Complete
 Download Realtime Sensor Data, 17.0 % Complete
 Download Realtime Sensor Data, 21.0 % Complete
 Download Realtime Sensor Data, 25.0 % Complete
 Download Realtime Sensor Data, 28.999999999999996 % Complete
 Download Realtime Sensor Data, 33.0 % Complete
 Download Realtime Sensor Data, 38.0 % Complete
 Download Realtime Sensor Data, 42.0 % Complete
 Download Realtime Sensor Data, 46.0 % Complete
 Download Realtime Sensor Data, 50.0 % Complete
 Download Realtime Sensor Data, 54.0 % Complete
 Download Realtime Sensor Data, 57.99999999999999 % Complete
 Download Realtime Sensor Data, 62.0 % Complete
 Download Realtime Sensor Data, 67.0 % Complete
 Download Realtime Sensor Data, 71.0 % Complete
 Download Realtime Sensor Data, 75.0 % Complete
 Download Realtime Sensor Data, 79.0 % Complete
 Download Realtime Sensor Data, 83.0 % Complete
 Download Realtime Sensor Data, 88.0 % Complete
 Download Realtime Sensor Data, 92.0 % Complete
 Download Realtime Sensor Data, 96.0 % Complete

C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:139: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw['dt'] = pd.to_datetime(realtimeraw['dt'], format='%Y-%m-%d %H:%M:%S')
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:140: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw['dt_relative'] = (realtimeraw['dt'] - realtimeraw['dt'].min()).dt.total_seconds()
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)
C:\Users\mk.muhammad.h1\Documents\MIH-Python\MIH-Dashboard-Project\Streamlit_App_v3\PDU_Func\IO_Data.py:153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[cols] = realtimeraw[cols].astype(float)

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin
0,2023-04-09 00:00:05,2023-04-09,00:00:05,14.84,110.00,4.84,4.58,42.66,0.0,0.00,0.0,0.00,0.00
1,2023-04-09 00:00:10,2023-04-09,00:00:10,14.84,110.00,4.71,4.58,43.71,0.0,0.00,0.0,0.00,0.00
2,2023-04-09 00:00:15,2023-04-09,00:00:15,14.84,110.00,4.51,4.58,43.71,0.0,0.00,0.0,0.00,0.00
3,2023-04-09 00:00:20,2023-04-09,00:00:20,14.84,110.00,4.51,4.58,43.29,0.0,0.00,0.0,0.00,0.00
4,2023-04-09 00:00:25,2023-04-09,00:00:25,14.84,110.00,4.51,4.58,43.18,0.0,0.00,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51823,2023-04-11 23:58:40,2023-04-11,23:58:40,323.89,417.92,26.88,11.18,160.57,0.0,1.99,13.0,1636.97,963.82
51824,2023-04-11 23:58:45,2023-04-11,23:58:45,323.53,417.92,27.24,11.18,160.26,0.0,1.70,14.0,1631.52,964.97
51825,2023-04-11 23:58:50,2023-04-11,23:58:50,323.16,417.92,27.61,11.18,160.03,0.0,1.65,13.0,1630.00,966.12
51826,2023-04-11 23:58:55,2023-04-11,23:58:55,322.80,417.92,27.98,11.18,159.95,0.0,1.96,14.0,1630.61,963.82
51827,2023-04-11 23:59:00,2023-04-11,23:59:00,322.42,417.92,28.35,11.18,159.65,0.0,1.92,13.0,1631.82,966.12

In [52]:
def addRigActivityLabel (RTSensor_df, InputActivity_DB, UserDateRange="All"):
    ii = 0
    if UserDateRange != "All":
        StartDateTime = datetime.combine(UserDateRange['StartDate'], UserDateRange['StartTime'])
        EndDateTime = datetime.combine(UserDateRange['EndDate'], UserDateRange['EndTime'])
        RTSensor_df = RTSensor_df[(RTSensor_df['dt'] >= StartDateTime) & (RTSensor_df['dt'] < EndDateTime)]

    InputActivity_DB = InputActivity_DB.reset_index()

    for i,row in InputActivity_DB.iterrows():


        try:
            start_time_temp = InputActivity_DB.loc[ii, 'DateTime']
            end_time_temp = InputActivity_DB.loc[ii+1, 'DateTime']

            idx_logic = (RTSensor_df['dt'] >= start_time_temp) & (RTSensor_df['dt'] < end_time_temp)
        except:
            start_time_temp = InputActivity_DB.loc[ii, 'DateTime']

            idx_logic = (RTSensor_df['dt'] >= start_time_temp)

        activity_label_temp = InputActivity_DB.loc[ii, 'Activity']
        # pic_label_temp = InputActivity_DB.loc[ii, 'PIC']
        # section_label_temp = InputActivity_DB.loc[ii, 'Section Size']
        # remarks_label_temp = InputActivity_DB.loc[ii, 'Remarks']
        # activity_label_temp = InputActivity_DB.loc[ii, 'In-Slip Threshold']

        RTSensor_df.loc[idx_logic, ("Activity")] = activity_label_temp
        # RTSensor_df.loc[idx_logic, ("PIC")] = pic_label_temp
        # RTSensor_df.loc[idx_logic, ("Section Size")] = section_label_temp
        # RTSensor_df.loc[idx_logic, ("remarks")] = remarks_label_temp
        # RTSensor_df.loc[idx_logic, ("In-Slip Threshold")] = activity_label_temp
        ii = ii+1
    return RTSensor_df
def addSectionParams (RTSensor_df, InputActivity_DB, UserDateRange="All"):
    ii = 0
    if UserDateRange != "All":
        StartDateTime = datetime.combine(UserDateRange['StartDate'], UserDateRange['StartTime'])
        EndDateTime = datetime.combine(UserDateRange['EndDate'], UserDateRange['EndTime'])
        RTSensor_df = RTSensor_df[(RTSensor_df['dt'] >= StartDateTime) & (RTSensor_df['dt'] < EndDateTime)]

    InputActivity_DB = InputActivity_DB.reset_index()
    display(InputActivity_DB)

    for i,row in InputActivity_DB.iterrows():


        try:
            start_time_temp = InputActivity_DB.loc[ii, 'DateTime']
            end_time_temp = InputActivity_DB.loc[ii+1, 'DateTime']

            idx_logic = (RTSensor_df['dt'] >= start_time_temp) & (RTSensor_df['dt'] < end_time_temp)
        except:
            start_time_temp = InputActivity_DB.loc[ii, 'DateTime']

            idx_logic = (RTSensor_df['dt'] >= start_time_temp)

        # activity_label_temp = InputActivity_DB.loc[ii, 'Activity']
        # pic_label_temp = InputActivity_DB.loc[ii, 'PIC']
        section_label_temp = InputActivity_DB.loc[ii, 'Section Size']
        # remarks_label_temp = InputActivity_DB.loc[ii, 'Remarks']
        activity_label_temp = InputActivity_DB.loc[ii, 'In-Slip Threshold']

        # RTSensor_df.loc[idx_logic, ("Activity")] = activity_label_temp
        # RTSensor_df.loc[idx_logic, ("PIC")] = pic_label_temp
        RTSensor_df.loc[idx_logic, ("Section Size")] = section_label_temp
        # RTSensor_df.loc[idx_logic, ("remarks")] = remarks_label_temp
        RTSensor_df.loc[idx_logic, ("In-Slip Threshold")] = activity_label_temp
        ii = ii+1
    return RTSensor_df
def translateRigActivity2Activity(RigActivityDF):
    replacement_dict = {
        "Cementing":"Cementing Job",
        "Condition and/or Circulate mud":"Circulation",
        "Connection (drilling)":"Connection",
        "Cut/Slip Drilling Line":"Other",
        "Drill Cement and/or Float Equipment":"Drill Out Cement",
        "Drilling":"Drilling Formation",
        "Fishing":"Other",
        "Flow Check":"Other",
        "Lost Circulation":"Other",
        "Lubricate Rig":"Rig Repair",
        "Nipple Up /Nipple Down BOP Stack":"Make up BHA",
        "Plug Back":"Other",
        "Pressure Integrity Test":"Other",
        "Reaming":"Stationary",
        "Rig Repair":"Rig Repair",
        "Run Casing":"Running Casing In",
        "Short Trip In":"Trip In",
        "Short Trip Out":"Trip Out",
        "Squeeze Cementing":"Cementing Job",
        "Stuck Pipe":"Stuck Pipe",
        "Test BOP":"Make up BHA",
        "Tripping In":"Trip In",
        "Tripping Out":"Trip Out",
        "Undefined Status":"Other",
        "Wait on Cement":"Wait on Cement",
        "Wireline Logs":"Other",
    }
    RigActivityDF['Activity'] = RigActivityDF['Activity'].replace(replacement_dict)
    RigActivityDF['Activity'] = RigActivityDF['Activity'].str.upper()

    
    return RigActivityDF

In [53]:
rigActivityDF = translateRigActivity2Activity(rigActivityDF)
rigActivityDF.to_excel('rigActivityDF_translate.xlsx', index=False)
rigActivityDF

               DateTime actcode            Activity
15  2023-04-07 08:38:46       2  DRILLING FORMATION
143 2023-04-07 08:54:31       3          CONNECTION
16  2023-04-07 08:59:28       2  DRILLING FORMATION
144 2023-04-07 09:51:59       3          CONNECTION
314 2023-04-07 12:06:02       8             TRIP IN
..                  ...     ...                 ...
13  2023-05-30 21:02:51       0               OTHER
408 2023-05-30 23:36:06      14               OTHER
313 2023-05-31 17:20:27       7         CIRCULATION
14  2023-05-31 19:31:59       0               OTHER
458 2023-06-01 17:17:43      21         MAKE UP BHA

[485 rows x 3 columns]

In [54]:
SectionParams_DF = pd.read_excel('SectionParams.xlsx')
display(SectionParams_DF)
RealtimeDF_out = addRigActivityLabel (RealtimeDF, translateRigActivity2Activity(rigActivityDF), UserDateRange="All")
RealtimeDF_out = addSectionParams (RealtimeDF_out, SectionParams_DF, UserDateRange="All")
RealtimeDF_out['PIC'] = None
RealtimeDF_out['remarks'] = None
RealtimeDF_out.to_excel('RealtimeDF_out_label.xlsx', index=False)
display(RealtimeDF_out)

              DateTime Section Size  In-Slip Threshold
0  2023-04-08 13:02:47          26"                 54

   index             DateTime Section Size  In-Slip Threshold
0      0  2023-04-08 13:02:47          26"                 54

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin,Activity,Section Size,In-Slip Threshold,PIC,remarks
0,2023-04-09 00:00:05,2023-04-09,00:00:05,14.84,110.00,4.84,4.58,42.66,0.0,0.00,0.0,0.00,0.00,TRIP OUT,"26""",54.0,None,None
1,2023-04-09 00:00:10,2023-04-09,00:00:10,14.84,110.00,4.71,4.58,43.71,0.0,0.00,0.0,0.00,0.00,TRIP OUT,"26""",54.0,None,None
2,2023-04-09 00:00:15,2023-04-09,00:00:15,14.84,110.00,4.51,4.58,43.71,0.0,0.00,0.0,0.00,0.00,TRIP OUT,"26""",54.0,None,None
3,2023-04-09 00:00:20,2023-04-09,00:00:20,14.84,110.00,4.51,4.58,43.29,0.0,0.00,0.0,0.00,0.00,TRIP OUT,"26""",54.0,None,None
4,2023-04-09 00:00:25,2023-04-09,00:00:25,14.84,110.00,4.51,4.58,43.18,0.0,0.00,0.0,0.00,0.00,TRIP OUT,"26""",54.0,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51823,2023-04-11 23:58:40,2023-04-11,23:58:40,323.89,417.92,26.88,11.18,160.57,0.0,1.99,13.0,1636.97,963.82,CIRCULATION,"26""",54.0,None,None
51824,2023-04-11 23:58:45,2023-04-11,23:58:45,323.53,417.92,27.24,11.18,160.26,0.0,1.70,14.0,1631.52,964.97,CIRCULATION,"26""",54.0,None,None
51825,2023-04-11 23:58:50,2023-04-11,23:58:50,323.16,417.92,27.61,11.18,160.03,0.0,1.65,13.0,1630.00,966.12,CIRCULATION,"26""",54.0,None,None
51826,2023-04-11 23:58:55,2023-04-11,23:58:55,322.80,417.92,27.98,11.18,159.95,0.0,1.96,14.0,1630.61,963.82,CIRCULATION,"26""",54.0,None,None
51827,2023-04-11 23:59:00,2023-04-11,23:59:00,322.42,417.92,28.35,11.18,159.65,0.0,1.92,13.0,1631.82,966.12,CIRCULATION,"26""",54.0,None,None

### Predict The SubActivity

In [55]:
def getSubActivityLabel(RTSensor_df, TripActivityList='default', DrillActivityList='default', OverrideActivityList='default'):
    #TODO makesure the column name and data type is match
    RTSensor_df = RTSensor_df.astype(
        {
            "dt":"datetime64[ns]",
            # "date":"object",
            # "time":"object",
            "bitdepth":"float64",
            "md":"float64",
            "blockpos":"float64",
            "rop":"float64",
            "hklda":"float64", 
            "woba":"float64",
            "torqa":"float64",
            "rpm":"float64",
            "stppress":"float64",
            "mudflowin":"float64",
            # "Activity":"object",
            "In-Slip Threshold":"float64",
            "PIC":'str',
            "remarks":'str',
            "Section Size":'str',
            # "SubActivity":"object",
            # "logic_status":"int64",
            # "isBitDepthMoving":"bool",
            # "LABEL_All":"object",
        }
    )
    if TripActivityList=='default':
        TripActivityList = ['NPT', 'N/D BOP', 'N/U BOP', 'OTHER', 'RUNNING CASING IN', 'STATIONARY', 'STUCK PIPE', 
                            'TRIP IN', 'TRIP OUT', 'WAIT ON CEMENT', 'LAY DOWN BHA', 'MAKE UP BHA', 'WIPER TRIP']
        
    if DrillActivityList=='default':
        DrillActivityList = ["DRILLING FORMATION", 'CIRCULATE HOLE CLEANING','CONNECTION','DRILL OUT CEMENT',]

    if OverrideActivityList=='default':
        OverrideActivityList = ['CEMENTING JOB', 'CONNECTION', 'LAY DOWN BHA', 'MAKE UP BHA', 'NPT', 'N/D BOP', 
                                'N/U BOP', 'RUNNING CASING IN', 'STATIONARY', 'STUCK PIPE', 'WAIT ON CEMENT', 'RIG REPAIR','N/A', 'OTHER']

    logic_status = 0
    RTSensor_df["SubActivity"] = "FALSE/Check"
    RTSensor_df["logic_status"] = logic_status

    idx_logic_activity = RTSensor_df["Activity"].isin(
                                                    DrillActivityList
                                                    )
    # print((RTSensor_df.dtypes))

    idx_logic = idx_logic_activity & ((RTSensor_df['woba']>0) & (RTSensor_df['rpm']>10) & (RTSensor_df['stppress']>100) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']))
    SubActivity_Label = "Rotary Drilling"
    RTSensor_df.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic, "logic_status"] = logic_status
    # 1

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic, "logic_status"] = logic_status

    idx_logic = idx_logic_activity &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((RTSensor_df['woba']>0) & (RTSensor_df['rpm']<10) & (RTSensor_df['stppress']>100) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']))
    SubActivity_Label = "Slide Drilling"
    RTSensor_df.loc[idx_logic, "SubActivity"] = SubActivity_Label
    # 2

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic, "logic_status"] = logic_status
    
    idx_logic = idx_logic_activity &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((RTSensor_df['woba']==0) & (RTSensor_df['rpm']>10) & (RTSensor_df['stppress']>100) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']))
    SubActivity_Label = "Reaming"
    RTSensor_df.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #3

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic, "logic_status"] = logic_status

    idx_logic = idx_logic_activity &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((RTSensor_df['woba']==0) & (RTSensor_df['rpm']==0) & (RTSensor_df['stppress']>100) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']))
    SubActivity_Label = "Wash Up/Down"
    RTSensor_df.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #4

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic, "logic_status"] = logic_status


    idx_logic = idx_logic_activity &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((RTSensor_df['woba']==0) & (RTSensor_df['rpm']==0) & (RTSensor_df['stppress']<50))
    SubActivity_Label = "Connection"
    RTSensor_df.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #5

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic, "logic_status"] = logic_status

    # idx_logic = idx_logic_activity & ((RTSensor_df["SubActivity"] == "FALSE/Check") & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']))
    idx_logic = idx_logic & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold'])
    SubActivity_Label="Look and define"
    RTSensor_df.loc[idx_logic, "SubActivity"] = SubActivity_Label
    #6

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic, "logic_status"] = logic_status
    #7


    # ############################
    idx_logic_activity_2 = RTSensor_df["Activity"].isin(
        TripActivityList
        )
    RTSensor_df['isBitDepthMoving'] = RTSensor_df['bitdepth'].shift(periods=-1) != RTSensor_df['bitdepth']

    # RTSensor_df["LABEL_SubActivity"] = "Check"
    idx_logic_2 = idx_logic_activity_2 & ((RTSensor_df['isBitDepthMoving']) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']) & (RTSensor_df['rpm']==0) & (RTSensor_df['mudflowin']>10))
    SubActivity_Label = "Wash Up/Down"
    RTSensor_df.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    # DisplayDF(RTSensor_df.loc[idx_logic_2, :])
    #

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic_2, "logic_status"] = logic_status
    #8
    
    idx_logic_2 = idx_logic_activity_2 &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((RTSensor_df['isBitDepthMoving']) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']) & (RTSensor_df['rpm']>10) & (RTSensor_df['stppress']>100) & (RTSensor_df['mudflowin']>10))
    SubActivity_Label = "Reaming"
    RTSensor_df.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic_2, "logic_status"] = logic_status
    #9

    idx_logic_2 = idx_logic_activity_2 &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((RTSensor_df['isBitDepthMoving']) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']) & (RTSensor_df['rpm']<10) & (RTSensor_df['stppress']<100) & (RTSensor_df['mudflowin']<50))
    SubActivity_Label = "Moving"
    RTSensor_df.loc[idx_logic_2, "SubActivity"] = SubActivity_Label

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic_2, "logic_status"] = logic_status
    #10

    idx_logic_2 = idx_logic_activity_2 &(RTSensor_df["SubActivity"] == "FALSE/Check") & (~(RTSensor_df['isBitDepthMoving']) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']) & (RTSensor_df['mudflowin']>10))
    SubActivity_Label = "Circulation"
    RTSensor_df.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic_2, "logic_status"] = logic_status
    #11

    idx_logic_2 = idx_logic_activity_2 &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((RTSensor_df['mudflowin']<10) & (RTSensor_df['rpm']<10) & (RTSensor_df['hklda']<RTSensor_df['In-Slip Threshold']))
    SubActivity_Label = "Connection"
    RTSensor_df.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic_2, "logic_status"] = logic_status
    #12

    idx_logic_2 = idx_logic_activity_2 &(RTSensor_df["SubActivity"] == "FALSE/Check") & ((~RTSensor_df['isBitDepthMoving']) & (RTSensor_df['mudflowin']<10) & (RTSensor_df['rpm']<10) & (RTSensor_df['hklda']>RTSensor_df['In-Slip Threshold']))
    SubActivity_Label = "Stationary"
    RTSensor_df.loc[idx_logic_2, "SubActivity"] = SubActivity_Label
    #

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic_2, "logic_status"] = logic_status
    #13
    ## force to be same as activity

    idx_logic_3 = RTSensor_df["Activity"].isin(
                                                OverrideActivityList
                                                )
    RTSensor_df.loc[idx_logic_3, "SubActivity"] = RTSensor_df.loc[idx_logic_3, "Activity"]
    #

    logic_status = logic_status + 1
    RTSensor_df.loc[idx_logic_3, "logic_status"] = logic_status
    #14

    # print(RTSensor_df.columns)

    return RTSensor_df

In [56]:
RealtimeDF_out = getSubActivityLabel(RealtimeDF_out, TripActivityList='default', DrillActivityList='default', OverrideActivityList='default')
RealtimeDF_out.to_excel('RealtimeDF_out_label_predict.xlsx', index=False)
RealtimeDF_out

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,...,stppress,mudflowin,Activity,Section Size,In-Slip Threshold,PIC,remarks,SubActivity,logic_status,isBitDepthMoving
0,2023-04-09 00:00:05,2023-04-09,00:00:05,14.84,110.00,4.84,4.58,42.66,0.0,0.00,...,0.00,0.00,TRIP OUT,"26""",54.0,None,None,Connection,12,False
1,2023-04-09 00:00:10,2023-04-09,00:00:10,14.84,110.00,4.71,4.58,43.71,0.0,0.00,...,0.00,0.00,TRIP OUT,"26""",54.0,None,None,Connection,12,False
2,2023-04-09 00:00:15,2023-04-09,00:00:15,14.84,110.00,4.51,4.58,43.71,0.0,0.00,...,0.00,0.00,TRIP OUT,"26""",54.0,None,None,Connection,12,False
3,2023-04-09 00:00:20,2023-04-09,00:00:20,14.84,110.00,4.51,4.58,43.29,0.0,0.00,...,0.00,0.00,TRIP OUT,"26""",54.0,None,None,Connection,12,False
4,2023-04-09 00:00:25,2023-04-09,00:00:25,14.84,110.00,4.51,4.58,43.18,0.0,0.00,...,0.00,0.00,TRIP OUT,"26""",54.0,None,None,Connection,12,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51823,2023-04-11 23:58:40,2023-04-11,23:58:40,323.89,417.92,26.88,11.18,160.57,0.0,1.99,...,1636.97,963.82,CIRCULATION,"26""",54.0,None,None,FALSE/Check,0,True
51824,2023-04-11 23:58:45,2023-04-11,23:58:45,323.53,417.92,27.24,11.18,160.26,0.0,1.70,...,1631.52,964.97,CIRCULATION,"26""",54.0,None,None,FALSE/Check,0,True
51825,2023-04-11 23:58:50,2023-04-11,23:58:50,323.16,417.92,27.61,11.18,160.03,0.0,1.65,...,1630.00,966.12,CIRCULATION,"26""",54.0,None,None,FALSE/Check,0,True
51826,2023-04-11 23:58:55,2023-04-11,23:58:55,322.80,417.92,27.98,11.18,159.95,0.0,1.96,...,1630.61,963.82,CIRCULATION,"26""",54.0,None,None,FALSE/Check,0,True
51827,2023-04-11 23:59:00,2023-04-11,23:59:00,322.42,417.92,28.35,11.18,159.65,0.0,1.92,...,1631.82,966.12,CIRCULATION,"26""",54.0,None,None,FALSE/Check,0,True

In [63]:
def getGroupDuration_v2(RTSensor_df , DrillActivityList='default'):
    if DrillActivityList=='default':
        DrillActivityList = ["DRILLING FORMATION", 'CIRCULATE HOLE CLEANING','CONNECTION','DRILL OUT CEMENT',]


    RTSensor_df ['dt'] = pd.to_datetime(RTSensor_df ['dt'])
    RTSensor_df ["LABEL_All"] =RTSensor_df ['SubActivity'].astype(str)+'--'+RTSensor_df['Activity'].astype(str)
    RTSensor_df ['Activity'] = RTSensor_df ['Activity'].fillna("N/A").astype(str)
    RTSensor_df ['SubActivity'] = RTSensor_df ['SubActivity'].fillna("N/A").astype(str)
    # TODO , a funtion that check the latest hole depth
    Hole_Depth_max = 0
    list_dict_out = []
    # st.write(RTSensor_df)
    for k,DF_Temp in RTSensor_df .groupby((RTSensor_df ['LABEL_All'].shift() != RTSensor_df ['LABEL_All']).cumsum()):

        # if not(("Hole_Depth" in locals()) or ("Hole_Depth" in globals())):
        #     Hole_Depth = 0

        list_temp = []

        # date = DF_Temp.head(1)['date'].values[0]

        # Time_start = pd.to_datetime(date + " " + DF_Temp.head(1)['time'].values[0])
        # Time_end_temp = DF_Temp.tail(1)['time'].values[0]
        # Time_end = pd.to_datetime(DF_Temp.tail(1)['date'].values[0] + " " + str((datetime.strptime(Time_end_temp, "%H:%M:%S") + timedelta(seconds=5)).time()))
        Date = DF_Temp['date'].iloc[0]
        StartDateTime = DF_Temp['dt'].iloc[0]
        EndDateTime = DF_Temp['dt'].iloc[-1]
        # Time_start = DF_Temp.head(1)['time'].values[0]
        # Time_end_temp = DF_Temp.tail(1)['time'].values[0]
        # Time_end = str((datetime.strptime(Time_end_temp, "%H:%M:%S") + timedelta(seconds=5)).time())

        LABEL_Activity = DF_Temp['Activity'].iloc[0]
        LABEL_SubActivity = DF_Temp['SubActivity'].iloc[0]
        section_data = DF_Temp['Section Size'].iloc[0]
        pic_data = DF_Temp['PIC'].iloc[0]
        InSlip_Treshold_data = DF_Temp['In-Slip Threshold'].iloc[0]
        remarks_data = DF_Temp['remarks'].iloc[0]
        # status_data = DF_Temp['status'].iloc[0]

        # Duration(minutes)
        # the duration should add 5 second to compensate the delta 5s
        Duration = (((EndDateTime-StartDateTime).total_seconds()+5) / 60.0 )


        Hole_Depth_Temp = DF_Temp['md'].max()
        if float(Hole_Depth_Temp)>= float(Hole_Depth_max):
            Hole_Depth_max = Hole_Depth_Temp
        
        Bit_Depth_avg = DF_Temp['bitdepth'].mean()

        DrillingMeterage = np.nan

        RotateDrillingDuration = np.nan
        SlideDrillingDuration = np.nan
        ReamingDuration = np.nan
        ConnectionDuration = np.nan

        # OnBottomHours = np.nan
        # StandDuration = np.nan

        if LABEL_Activity in DrillActivityList:
            DrillingMeterage = round((DF_Temp['md'].max()-DF_Temp['md'].min()),2)

        if LABEL_SubActivity == "Rotary Drilling":
            RotateDrillingDuration = Duration

        if LABEL_SubActivity == "Slide Drilling":
            SlideDrillingDuration = Duration

        if LABEL_SubActivity == "Reaming":
            ReamingDuration = Duration
        if LABEL_SubActivity == "Connection":
            ConnectionDuration = Duration


        list_dict_out.append(
            {
            'Date':Date,
            'StartDateTime':StartDateTime,
            'EndDateTime':EndDateTime,
            'Duration':Duration,
            'Hole_Depth_max':Hole_Depth_max,
            'Bit_Depth_avg':Bit_Depth_avg,
            "DrillingMeterage": DrillingMeterage,
            'RotateDrillingDuration':RotateDrillingDuration,
            'SlideDrillingDuration':SlideDrillingDuration,
            'ReamingDuration':ReamingDuration,
            'ConnectionDuration':ConnectionDuration,
            # 'On Bottom Hours':OnBottomHours,
            # 'Stand Duration': StandDuration,
            'LABEL_SubActivity': LABEL_SubActivity,
            "LABEL_Activity": LABEL_Activity,
            "LABEL_All": LABEL_SubActivity+'--'+LABEL_Activity,
            "PIC":pic_data,
            "InSlip_Treshold":InSlip_Treshold_data,
            "Remarks":remarks_data,
            "Section":section_data,
            # "status":status_data,

            }
        )

    ActSum_df = pd.DataFrame.from_dict(list_dict_out,orient='columns')
    
    # st.write(ActSum_df)

    
    listSetDecimals = ['Duration','Hole_Depth_max','Bit_Depth_avg','DrillingMeterage',
                       'RotateDrillingDuration','SlideDrillingDuration','ReamingDuration',
                       'ConnectionDuration','InSlip_Treshold',]
    for ColumnName in listSetDecimals:
        ActSum_df[ColumnName] = np.round(ActSum_df[ColumnName].astype('float'),2)
    # TODO a function that validate the data type output
        # ActSum_df = ActSum_df.astype({'date': np.dtype('<M8[ns]'),
        # 'StartDateTime': np.dtype('<M8[ns]'),
        # 'EndDateTime': np.dtype('<M8[ns]'),
        # 'Duration': np.dtype('float64'),
        # 'Hole_Depth_max': np.dtype('float64'),
        # 'Bit_Depth_avg': np.dtype('float64'),
        # 'DrillingMeterage': np.dtype('float64'),
        # 'RotateDrillingDuration': dtype('float64'),
        # 'SlideDrillingDuration': np.dtype('float64'),
        # 'ReamingDuration': np.dtype('float64'),
        # 'ConnectionDuration': np.dtype('float64'), 
        # 'LABEL_SubActivity': 'str',
        # 'LABEL_Activity': 'str',
        # 'PIC': 'str',
        # 'InSlip_Treshold': np.dtype('float64'),
        # 'Remarks': 'str',
        # 'Section': 'str'})
        #     # )
    ActSum_df['LABEL_SubActivity'] = ActSum_df['LABEL_SubActivity'].replace('CONNECTION', 'Connection')
    return ActSum_df

In [72]:
ActSum_df = getGroupDuration_v2(RealtimeDF_out, DrillActivityList='default')
ActSum_df.to_excel('ActSum_df.xlsx', index=False)
ActSum_df
# Done

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,ConnectionDuration,LABEL_SubActivity,LABEL_Activity,LABEL_All,PIC,InSlip_Treshold,Remarks,Section
0,2023-04-09,2023-04-09 00:00:05,2023-04-09 00:11:50,11.83,110.00,14.84,NaN,NaN,NaN,NaN,11.83,Connection,TRIP OUT,Connection--TRIP OUT,None,54.0,None,"26"""
1,2023-04-09,2023-04-09 00:11:55,2023-04-09 00:13:35,1.75,110.00,14.84,NaN,NaN,NaN,NaN,NaN,Stationary,TRIP OUT,Stationary--TRIP OUT,None,54.0,None,"26"""
2,2023-04-09,2023-04-09 00:13:40,2023-04-09 00:14:30,0.92,110.00,19.26,NaN,NaN,NaN,NaN,NaN,Moving,TRIP OUT,Moving--TRIP OUT,None,54.0,None,"26"""
3,2023-04-09,2023-04-09 00:14:35,2023-04-09 00:16:20,1.83,110.00,24.07,NaN,NaN,NaN,NaN,NaN,Stationary,TRIP OUT,Stationary--TRIP OUT,None,54.0,None,"26"""
4,2023-04-09,2023-04-09 00:16:25,2023-04-09 00:16:55,0.58,110.00,24.95,NaN,NaN,NaN,NaN,NaN,Moving,TRIP OUT,Moving--TRIP OUT,None,54.0,None,"26"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,2023-04-11,2023-04-11 21:18:45,2023-04-11 21:31:50,13.17,417.92,404.26,0.0,NaN,NaN,13.17,NaN,Reaming,DRILLING FORMATION,Reaming--DRILLING FORMATION,None,54.0,None,"26"""
1241,2023-04-11,2023-04-11 21:31:55,2023-04-11 21:31:55,0.08,417.92,415.11,0.0,NaN,NaN,NaN,NaN,FALSE/Check,DRILLING FORMATION,FALSE/Check--DRILLING FORMATION,None,54.0,None,"26"""
1242,2023-04-11,2023-04-11 21:32:00,2023-04-11 21:39:35,7.67,417.92,414.91,0.0,NaN,NaN,NaN,NaN,Wash Up/Down,DRILLING FORMATION,Wash Up/Down--DRILLING FORMATION,None,54.0,None,"26"""
1243,2023-04-11,2023-04-11 21:39:40,2023-04-11 22:36:35,57.00,417.92,401.51,0.0,NaN,NaN,NaN,NaN,Connection,CONNECTION,CONNECTION--CONNECTION,None,54.0,None,"26"""
1244,2023-04-11,2023-04-11 22:36:40,2023-04-11 23:59:00,82.42,417.92,371.25,NaN,NaN,NaN,NaN,NaN,FALSE/Check,CIRCULATION,FALSE/Check--CIRCULATION,None,54.0,None,"26"""

In [73]:
def cleanFalseSensor(ActSum_df, MinuteTolerances=1, CleaningIteration=1, includeStatus=False):
    def _first_non_empty(x):
        non_empty_values = x[x != ''].tolist()
        return non_empty_values[0] if non_empty_values else ''
    # st.write('clean')
    if 'LABEL_ConnectionActivity' not in ActSum_df.columns:
        ActSum_df['LABEL_ConnectionActivity']  = ''
    # ActSum_df['LABEL_ConnectionActivity'] = ActSum_df['LABEL_ConnectionActivity'].fillna('-')

    # Set the Duration==0 to FALSE/Check
    # ActSum_df.loc[, 'LABEL_SubActivity'] = "Look and define"

    ActSum_df['Duration'] = ActSum_df['Duration'].astype('float')
    for iter in range(CleaningIteration):
        ActSum_df = ActSum_df.reset_index(drop=True)
        # while ("FALSE/Check" in ActSum_df['LABEL_SubActivity'].values) or ("Look and define" in ActSum_df['LABEL_SubActivity'].values):
        lookdefine_logic = ActSum_df['LABEL_SubActivity']=="Look and define"
        falsecheck_logic = ActSum_df['LABEL_SubActivity']=="FALSE/Check"
        duration_logic = (ActSum_df['Duration'] <= float(MinuteTolerances))

        
        idx_same = ActSum_df.index[
            (lookdefine_logic | falsecheck_logic) #& duration_logic
            ]
        idx_before = idx_same - 1

        idx_same = idx_same[idx_before>=0]
        idx_before = idx_before[idx_before>=0]
        
        ActSum_df.loc[idx_same, 'LABEL_SubActivity'] = ActSum_df.loc[idx_before, 'LABEL_SubActivity'].values
        ActSum_df.loc[idx_same, 'LABEL_All'] = ActSum_df.loc[idx_before, 'LABEL_All'].values
        AggDict = {'Date': 'max',
                    'StartDateTime': 'min',
                    'EndDateTime': 'max',
                    'Duration': 'sum',
                    'Hole_Depth_max': 'max',
                    'Bit_Depth_avg': 'mean',
                    'DrillingMeterage': 'sum',
                    'RotateDrillingDuration': 'sum',
                    'SlideDrillingDuration': 'sum',
                    'ReamingDuration': 'sum',
                    'ConnectionDuration': 'sum',
                    'LABEL_SubActivity': 'first',
                    'LABEL_Activity': 'first',
                    'LABEL_All': 'first',
                    'LABEL_ConnectionActivity': _first_non_empty,
                    'PIC': 'first',
                    'InSlip_Treshold': 'first',
                    'Remarks': 'first',
                    'Section': 'first'
                    }
        # if includeStatus:
        #     AggDict['status'] = 'first'
        ActSum_df = ActSum_df.groupby((ActSum_df['LABEL_All'].shift() != ActSum_df['LABEL_All']).cumsum(), as_index=False).agg(AggDict)

    return ActSum_df

In [74]:
ActSum_df = cleanFalseSensor(ActSum_df, MinuteTolerances=10, CleaningIteration=10, includeStatus=True)
ActSum_df.to_excel('ActSum_df_clean.xlsx', index=False)
ActSum_df

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,ConnectionDuration,LABEL_SubActivity,LABEL_Activity,LABEL_All,LABEL_ConnectionActivity,PIC,InSlip_Treshold,Remarks,Section
0,2023-04-09,2023-04-09 00:00:05,2023-04-09 00:11:50,11.83,110.00,14.840,0.0,0.00,0.0,0.00,11.83,Connection,TRIP OUT,Connection--TRIP OUT,,None,54.0,None,"26"""
1,2023-04-09,2023-04-09 00:11:55,2023-04-09 00:13:35,1.75,110.00,14.840,0.0,0.00,0.0,0.00,0.00,Stationary,TRIP OUT,Stationary--TRIP OUT,,None,54.0,None,"26"""
2,2023-04-09,2023-04-09 00:13:40,2023-04-09 00:14:30,0.92,110.00,19.260,0.0,0.00,0.0,0.00,0.00,Moving,TRIP OUT,Moving--TRIP OUT,,None,54.0,None,"26"""
3,2023-04-09,2023-04-09 00:14:35,2023-04-09 00:16:20,1.83,110.00,24.070,0.0,0.00,0.0,0.00,0.00,Stationary,TRIP OUT,Stationary--TRIP OUT,,None,54.0,None,"26"""
4,2023-04-09,2023-04-09 00:16:25,2023-04-09 00:16:55,0.58,110.00,24.950,0.0,0.00,0.0,0.00,0.00,Moving,TRIP OUT,Moving--TRIP OUT,,None,54.0,None,"26"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,2023-04-11,2023-04-11 19:37:50,2023-04-11 19:42:15,4.50,403.62,401.270,0.0,0.00,0.0,4.50,0.00,Reaming,DRILLING FORMATION,Reaming--DRILLING FORMATION,,None,54.0,None,"26"""
1047,2023-04-11,2023-04-11 19:42:20,2023-04-11 21:18:40,96.42,417.92,410.800,14.3,96.42,0.0,0.00,0.00,Rotary Drilling,DRILLING FORMATION,Rotary Drilling--DRILLING FORMATION,,None,54.0,None,"26"""
1048,2023-04-11,2023-04-11 21:18:45,2023-04-11 21:31:55,13.25,417.92,409.685,0.0,0.00,0.0,13.17,0.00,Reaming,DRILLING FORMATION,Reaming--DRILLING FORMATION,,None,54.0,None,"26"""
1049,2023-04-11,2023-04-11 21:32:00,2023-04-11 21:39:35,7.67,417.92,414.910,0.0,0.00,0.0,0.00,0.00,Wash Up/Down,DRILLING FORMATION,Wash Up/Down--DRILLING FORMATION,,None,54.0,None,"26"""
1050,2023-04-11,2023-04-11 21:39:40,2023-04-11 23:59:00,139.42,417.92,386.380,0.0,0.00,0.0,0.00,0.00,Connection,CONNECTION,CONNECTION--CONNECTION,,None,54.0,None,"26"""

In [77]:
def getStandLabel(ActSum_df, DrillActivityList='default',stand_num=None):
    # if ActSum_df[ActSum_df['status']=='REVIEW'].empty:
    #     return ActSum_df
    # else:
    # ActSum_df = ActSum_df[ActSum_df['status']=='REVIEW']

    ActSum_df['DrillingMeteragePerStand'] = np.NaN
    ActSum_df['StandDuration'] = np.NaN
    ActSum_df['OnBottomDurationPerStand'] = np.NaN
    ActSum_df['Stand Group_Pred'] = ""
    ActSum_df['LABEL_ConnectionActivity'] = ""
    ActSum_df['RotateDrillingDuration'] = ActSum_df['RotateDrillingDuration'].astype('float')
    ActSum_df['SlideDrillingDuration']= ActSum_df['SlideDrillingDuration'].astype('float')
    ActSum_df['DrillingMeterage']= ActSum_df['DrillingMeterage'].astype('float')
    ActSum_df['Duration']= ActSum_df['Duration'].astype('float')

    # ActSum_df['ConnectionDurationPerStand'] = np.NaN

    ActSum_df = ActSum_df.reset_index(drop=True).fillna(0)
    if DrillActivityList=='default':
        DrillActivityList = ["DRILLING FORMATION", 'DRILL OUT CEMENT','CONNECTION']


    ActSum_df['LABEL_Activity'] = ActSum_df['LABEL_Activity'].astype(str)
    ActSum_df['LABEL_Activity'] = ActSum_df['LABEL_Activity'].replace({"CONNECTION":"DRILLING FORMATION"})
    

    if stand_num is None:
        stand_num = 0
    stand_num = stand_num+1

    # st.write(ActSum_df_Drilling.index[0])
    for k,ActSum_df_Temp in ActSum_df.groupby((ActSum_df['LABEL_Activity'].shift() != ActSum_df ['LABEL_Activity']).cumsum()):
        if ActSum_df_Temp['LABEL_Activity'].tolist()[0] in (DrillActivityList):
            ii = 1
            idx_start = ActSum_df_Temp.index[0]



            len_connection = len(ActSum_df_Temp[(ActSum_df_Temp['LABEL_SubActivity']=='Connection')])
            # First, define the stand first
            for idx,row in ActSum_df_Temp[(ActSum_df_Temp['LABEL_SubActivity']=='Connection')].iterrows():
                idx_end=idx-1
                ActSum_df_Stand = ActSum_df[idx_start:idx_end+1]

                if 'Reaming' in ActSum_df_Stand['LABEL_SubActivity'].tolist():
                    OnBottomDurationPerStand =  ActSum_df.loc[idx_start:idx_end, 'RotateDrillingDuration'].sum() + ActSum_df.loc[idx_start:idx_end, 'SlideDrillingDuration'].sum()
                    StandDuration =  ActSum_df.loc[idx_start:idx_end+1, 'Duration'].sum()
                    DrillingMeteragePerStand = ActSum_df.loc[idx_start:idx_end, 'DrillingMeterage'].sum()


                    ActSum_df.loc[idx, 'OnBottomDurationPerStand'] = OnBottomDurationPerStand
                    ActSum_df.loc[idx, 'StandDuration'] = StandDuration
                    ActSum_df.loc[idx, "DrillingMeteragePerStand"] = DrillingMeteragePerStand
                    ActSum_df.loc[idx_start:idx_end, 'Stand Group_Pred'] = 'Drilling Stand-' + str(stand_num)
                    if ii==1:
                        PreCon_Start_idx = ActSum_df_Stand[ActSum_df_Stand['LABEL_SubActivity']=='Reaming'].index[-1]
                        
                        PreCon_End_idx = (idx-1)
                        ActSum_df.loc[PreCon_Start_idx:PreCon_End_idx,'LABEL_ConnectionActivity'] = 'Pre Connection-'+str(stand_num)
                        # stand_num = stand_num-1
                        ii = ii +1
                        # st.write(PreCon_Start_idx)
                    else:
                        


                        # try:
                        PostCon_Start_idx = idx_start
                        PostCon_End_idx = ActSum_df_Stand[ActSum_df_Stand['LABEL_SubActivity']=='Reaming'].index[0]
                        ActSum_df.loc[PostCon_Start_idx:PostCon_End_idx,'LABEL_ConnectionActivity'] = 'Post Connection-'+str(stand_num-1)
                        print(PostCon_Start_idx)
                        print('PostCon')
                        print(PostCon_End_idx)
                        # if ii < len_connection:
                        PreCon_Start_idx = ActSum_df_Stand[ActSum_df_Stand['LABEL_SubActivity']=='Reaming'].index[-1]
                        PreCon_End_idx = (idx-1)
                        ActSum_df.loc[PreCon_Start_idx:PreCon_End_idx,'LABEL_ConnectionActivity'] = 'Pre Connection-'+str(stand_num)
                        # st.write(f"PreConIdx {PreCon_Start_idx} - {PreCon_End_idx}")

                        # except:
                        #     pass
                        ii = ii+1



                    # st.write()
                    stand_num = stand_num+1
                




                idx_start = idx+1
            # if len_connection == 1:
            try:
                ActSum_df_PostCon = ActSum_df_Temp[idx_start-2:]
                # st.write(ActSum_df_PostCon)

                PostCon_Start_idx = idx_start
                PostCon_End_idx = ActSum_df_PostCon[ActSum_df_PostCon['LABEL_SubActivity']=='Reaming'].index[0]
                ActSum_df.loc[PostCon_Start_idx:PostCon_End_idx,'LABEL_ConnectionActivity'] = 'Post Connection-'+str(stand_num-1)
            except:
                # st.write(ii)
                try:
                    ActSum_df.loc[PreCon_Start_idx:PreCon_End_idx,'LABEL_ConnectionActivity'] = ''
                except:
                    pass
                # pass





            

    return ActSum_df

In [78]:
ActSum_df = getStandLabel(ActSum_df)
ActSum_df.to_excel('ActSum_df_clean_stand.xlsx', index=False)
ActSum_df

315
PostCon
316
432
PostCon
432
451
PostCon
451
506
PostCon
506
537
PostCon
538
543
PostCon
543
552
PostCon
553
556
PostCon
557
574
PostCon
574
603
PostCon
603
637
PostCon
637
660
PostCon
661
686
PostCon
687
725
PostCon
726
1021
PostCon
1021
1045
PostCon
1046

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,LABEL_All,LABEL_ConnectionActivity,PIC,InSlip_Treshold,Remarks,Section,DrillingMeteragePerStand,StandDuration,OnBottomDurationPerStand,Stand Group_Pred
0,2023-04-09,2023-04-09 00:00:05,2023-04-09 00:11:50,11.83,110.00,14.840,0.0,0.00,0.0,0.00,...,Connection--TRIP OUT,,None,54.0,None,"26""",0.00,0.00,0.0,
1,2023-04-09,2023-04-09 00:11:55,2023-04-09 00:13:35,1.75,110.00,14.840,0.0,0.00,0.0,0.00,...,Stationary--TRIP OUT,,None,54.0,None,"26""",0.00,0.00,0.0,
2,2023-04-09,2023-04-09 00:13:40,2023-04-09 00:14:30,0.92,110.00,19.260,0.0,0.00,0.0,0.00,...,Moving--TRIP OUT,,None,54.0,None,"26""",0.00,0.00,0.0,
3,2023-04-09,2023-04-09 00:14:35,2023-04-09 00:16:20,1.83,110.00,24.070,0.0,0.00,0.0,0.00,...,Stationary--TRIP OUT,,None,54.0,None,"26""",0.00,0.00,0.0,
4,2023-04-09,2023-04-09 00:16:25,2023-04-09 00:16:55,0.58,110.00,24.950,0.0,0.00,0.0,0.00,...,Moving--TRIP OUT,,None,54.0,None,"26""",0.00,0.00,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,2023-04-11,2023-04-11 19:37:50,2023-04-11 19:42:15,4.50,403.62,401.270,0.0,0.00,0.0,4.50,...,Reaming--DRILLING FORMATION,Post Connection-19,None,54.0,None,"26""",0.00,0.00,0.0,Drilling Stand-20
1047,2023-04-11,2023-04-11 19:42:20,2023-04-11 21:18:40,96.42,417.92,410.800,14.3,96.42,0.0,0.00,...,Rotary Drilling--DRILLING FORMATION,,None,54.0,None,"26""",0.00,0.00,0.0,Drilling Stand-20
1048,2023-04-11,2023-04-11 21:18:45,2023-04-11 21:31:55,13.25,417.92,409.685,0.0,0.00,0.0,13.17,...,Reaming--DRILLING FORMATION,,None,54.0,None,"26""",0.00,0.00,0.0,Drilling Stand-20
1049,2023-04-11,2023-04-11 21:32:00,2023-04-11 21:39:35,7.67,417.92,414.910,0.0,0.00,0.0,0.00,...,Wash Up/Down--DRILLING FORMATION,,None,54.0,None,"26""",0.00,0.00,0.0,Drilling Stand-20
1050,2023-04-11,2023-04-11 21:39:40,2023-04-11 23:59:00,139.42,417.92,386.380,0.0,0.00,0.0,0.00,...,CONNECTION--CONNECTION,,None,54.0,None,"26""",19.18,294.84,130.0,