In [1]:
import pandas as pd 
import plotly.graph_objects as go
from plotly.subplots import make_subplots

ActSum_df = pd.read_csv('ActSum_Trial.csv', index_col=0, sep=';')
display(ActSum_df)

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,28/08/2024,28/08/2024 17:50,28/08/2024 21:08,198.00,162.78,156.75,12.14,198.00,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724880585
1,28/08/2024,28/08/2024 21:08,28/08/2024 21:29,21.25,162.78,149.08,0.00,0.00,0.0,21.25,...,0.00,Reaming,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724880585
2,28/08/2024,28/08/2024 21:29,28/08/2024 21:37,7.33,162.78,161.92,0.00,0.00,0.0,0.00,...,28.58,Connection,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,NaN
3,28/08/2024,28/08/2024 21:37,28/08/2024 21:47,10.92,162.99,162.41,0.21,0.00,0.0,10.92,...,0.00,Reaming,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724903040
4,28/08/2024,28/08/2024 21:48,28/08/2024 21:49,1.83,163.10,163.06,0.10,1.83,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724903040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4331,24/09/2024,24/09/2024 20:16,24/09/2024 20:17,1.25,1653.02,1024.65,0.00,0.00,0.0,0.00,...,0.00,Moving,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4332,24/09/2024,24/09/2024 20:17,24/09/2024 20:18,1.33,1653.02,1012.29,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4333,24/09/2024,24/09/2024 20:18,24/09/2024 22:56,158.17,1653.02,436.42,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4334,24/09/2024,24/09/2024 22:56,27/09/2024 11:06,3610.08,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,OTHER,OTHER,0.0,34,0,NaN,"12-1/4""",NaN,NaN
4335,27/09/2024,27/09/2024 11:06,28/09/2024 09:21,1335.17,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,MAKE UP BHA,MAKE UP BHA,0.0,34,0,NaN,"12-1/4""",NaN,NaN

# Pie Chart Activity Duration

In [ ]:
display(ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index())
display(ActSum_df.groupby(['LABEL_SubActivity'])['Duration'].sum().reset_index())
# ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index()

In [ ]:
SumDuration_Act = (ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index())
SumDuration_SubAct = (ActSum_df.groupby(['LABEL_SubActivity'])['Duration'].sum().reset_index())


fig = go.Figure()
fig.add_trace(go.Pie(labels=SumDuration_Act['LABEL_Activity'], hole=0.5,
                     values=SumDuration_Act['Duration'], ))

LegendDict= {
        'legend':{
            'orientation':'h', 
            'xref':"paper",
            'yref':"container",
            'y':-0.3,
            'x':0.5,
            'xanchor':'center', 
            'yanchor':'bottom', 
            }
        }

fig.update_layout(LegendDict)
fig.update_layout(
        height=600,
        width=600,
        margin=dict(l=0, r=0, t=50, b=50),
        title={'text': "Activity Duration", 'x': 0.5, 'xanchor': 'center'},
)
fig.show()

In [ ]:
ActSum_df

In [ ]:
import pandas as pd
import plotly.graph_objects as go

# Example data
data = {
    "StartDateTime": ["2025-01-01 08:00", "2025-01-01 09:00", "2025-01-01 10:00"],
    "EndDateTime": ["2025-01-01 08:30", "2025-01-01 09:30", "2025-01-01 10:30"],
    "Duration": [30, 45, 60],
    "Activity": ["Activity A", "Activity B", "Activity C"]
}

# Convert to DataFrame
df = pd.DataFrame(data)
import pandas as pd
import plotly.graph_objects as go

# Example data
data = {
    "StartDateTime": ["2025-01-01 08:00", "2025-01-01 09:00", "2025-01-01 10:00"],
    "EndDateTime": ["2025-01-01 08:30", "2025-01-01 09:30", "2025-01-01 10:30"],
    "Duration": [30, 45, 60],
    "Activity": ["Activity A", "Activity B", "Activity C"]
}

# Convert to DataFrame
df = pd.DataFrame(ActSum_df)
df = df.reset_index()
df['HoverText'] = df['StartDateTime'] + " - " + df['EndDateTime']
# Create the bar chart
fig = go.Figure()

# Add a bar for each activity
for activity in df['LABEL_SubActivity'].unique():
    activity_data = df[df['LABEL_SubActivity'] == activity]
    fig.add_trace(go.Bar(
        x=activity_data['StartDateTime'],  # Activity as X-axis (category)
        y=activity_data['Duration'],  # Duration as Y-axis
        hovertext=activity_data['HoverText'],  # Hover text for StartDateTime
        # text=activity_data['Duration'],  # Add Duration as text on bars
        # textposition='auto',
        name=activity  # Legend name for the activity
    ))

# Update layout for X and Y axes
fig.update_layout(
    xaxis=dict(
        title="StartDateTime",
        tickvals=df.index,
        ticktext=df['StartDateTime'],  # Show StartDateTime on the X-axis
        title_standoff=20
    ),
    yaxis=dict(
        title="Duration (minutes)"
    ),
    title="Activity Duration by Category",
    showlegend=True
)

# Show the figure
fig.show()

# Flat time Generation

In [2]:
ActSum_df

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,28/08/2024,28/08/2024 17:50,28/08/2024 21:08,198.00,162.78,156.75,12.14,198.00,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724880585
1,28/08/2024,28/08/2024 21:08,28/08/2024 21:29,21.25,162.78,149.08,0.00,0.00,0.0,21.25,...,0.00,Reaming,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724880585
2,28/08/2024,28/08/2024 21:29,28/08/2024 21:37,7.33,162.78,161.92,0.00,0.00,0.0,0.00,...,28.58,Connection,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,NaN
3,28/08/2024,28/08/2024 21:37,28/08/2024 21:47,10.92,162.99,162.41,0.21,0.00,0.0,10.92,...,0.00,Reaming,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724903040
4,28/08/2024,28/08/2024 21:48,28/08/2024 21:49,1.83,163.10,163.06,0.10,1.83,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724903040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4331,24/09/2024,24/09/2024 20:16,24/09/2024 20:17,1.25,1653.02,1024.65,0.00,0.00,0.0,0.00,...,0.00,Moving,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4332,24/09/2024,24/09/2024 20:17,24/09/2024 20:18,1.33,1653.02,1012.29,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4333,24/09/2024,24/09/2024 20:18,24/09/2024 22:56,158.17,1653.02,436.42,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4334,24/09/2024,24/09/2024 22:56,27/09/2024 11:06,3610.08,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,OTHER,OTHER,0.0,34,0,NaN,"12-1/4""",NaN,NaN
4335,27/09/2024,27/09/2024 11:06,28/09/2024 09:21,1335.17,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,MAKE UP BHA,MAKE UP BHA,0.0,34,0,NaN,"12-1/4""",NaN,NaN

In [3]:
list(ActSum_df.index)

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       4326, 4327, 4328, 4329, 4330, 4331, 4332, 4333, 4334, 4335],
      dtype='int64', length=4336)

In [3]:
import plotly.graph_objects as go
x = list(ActSum_df.index)

fig = go.Figure()

# Bar Chart Drilling Meterage

In [ ]:
import plotly.express as px

# Group by the new 'Date' column and sum the 'DrillingMeterage'
DrilingMeterage_df = ActSum_df.groupby('Date')['DrillingMeterage'].sum().reset_index()
DrilingMeterage_df
DrilingMeterage_df['Date'] = pd.to_datetime(DrilingMeterage_df['Date']).dt.date

# Create a bar chart using Plotly
fig = px.bar(DrilingMeterage_df, x='Date', y='DrillingMeterage',
             labels={'Date': 'Date', 'DrillingMeterage': 'Total Drilling Meterage'},
             )
fig.update_xaxes(
    dtick="D",)
# Show the plot
fig.show()

In [9]:
import pandas as pd
import plotly.graph_objects as go

# Sample DataFrame - replace with your actual data
data = {
    'StartDateTime': ['2024-01-01 08:00', '2024-01-01 10:00', '2024-01-01 14:00'],
    'EndDateTime': ['2024-01-01 10:00', '2024-01-01 14:00', '2024-01-01 16:00'],
    'BitDepth': [100, 200, 150],
    'Activity': ['Drilling', 'Moving', 'Drilling']
}
df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']

In [ ]:
df['LABEL_Activity'].unique()

# Depth vs Time

In [ ]:
import pandas as pd
import plotly.graph_objects as go
from datetime import timedelta
def round_up_to_next_15_minutes(dt):
    n_minutes = 15 - dt.minute % 15
    return dt + timedelta(minutes=n_minutes) if n_minutes != 15 else dt


df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']
# Convert the 'StartDateTime' and 'EndDateTime' columns to datetime type
df['StartDateTime'] = pd.to_datetime(df['StartDateTime'])
df['EndDateTime'] = pd.to_datetime(df['EndDateTime'])

# Sort the DataFrame by 'StartDateTime'
df = df.sort_values('StartDateTime')
df = df.reset_index(drop=True)

# Create a new Plotly figure
fig = go.Figure()

# Define your own colors for each activity
# activity_colors = {'Drilling': 'blue', 'Moving': 'red', 'Stationary': 'green'}
activity_colors ={'TRIP OUT': '#636EFA',
 'TRIP IN': '#EF553B',
 'CEMENTING JOB': '#00CC96',
 'OTHER': '#AB63FA',
 'WAIT ON CEMENT': '#FFA15A',
 'DRILL OUT CEMENT': '#19D3F3',
 'DRILLING FORMATION': '#FF6692'}
temp_actvity_list = []

# Plot each activity as a separate line segment
for idx, row in df.iterrows():
    if row['Activity'] not in temp_actvity_list: 
        temp_actvity_list.append(row['Activity'])
        legend_show = True
    else:
        legend_show = False
    # Adjust EndDateTime to be on a 15-minute interval if it's not
    # adjusted_end_time = round_up_to_next_15_minutes(row['EndDateTime'])

    # Create a date range with 15-minute intervals
    time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')

    # Ensure that the actual end time is included in the range
    if time_range[-1] != row['EndDateTime']:
        time_range = time_range.union(pd.DatetimeIndex([row['EndDateTime']]))

    # Interpolate BitDepth for each time point (assuming BitDepth is constant for simplicity)
    bit_depth_values = [row['BitDepth']] * len(time_range)
    # Create a date range with 15-minute intervals
    # time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')

    # Interpolate BitDepth for each time point (assuming BitDepth is constant for simplicity)
    bit_depth_values = [row['BitDepth']] * len(time_range)
    
    if idx == 0:
        df_plot = pd.DataFrame({'Datetime': time_range.values.tolist(), 'bit_depth': bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
    else:
        df_plot = pd.DataFrame({'Datetime': [time_range.values.tolist()[0]] + time_range.values.tolist(), 'bit_depth': before_bit_depth + bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
LegendDict= {
        'legend':{
            'orientation':'h', 
            'xref':"paper",
            'yref':"container",
            'y':-0.3,
            'x':0.5,
            'xanchor':'center', 
            'yanchor':'bottom', 
            }
        }

fig.update_layout(LegendDict)

# Set the plot titles and labels
fig.update_layout(
    # title='Time vs Bit Depth with Activity Intervals',
    height=600,
    width=1200,
    margin=dict(l=0, r=50, t=50, b=50),
    xaxis_title='Datetime',
    yaxis_title='Avg. Bit Depth (m)',
    yaxis_autorange='reversed',
    legend_title='Activity'
)

# Show the plot
fig.show()

In [ ]:
import pandas as pd
import plotly.graph_objects as go

# Create a DataFrame and rename columns for clarity
df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']

# Convert the 'StartDateTime' and 'EndDateTime' columns to datetime type
df['StartDateTime'] = pd.to_datetime(df['StartDateTime'])
df['EndDateTime'] = pd.to_datetime(df['EndDateTime'])

# Sort the DataFrame by 'StartDateTime' for chronological plotting
df = df.sort_values('StartDateTime').reset_index(drop=True)

# Create a new Plotly figure
fig = go.Figure()

# Define custom colors for each activity type
activity_colors = {'TRIP IN': 'red',
 'TRIP OUT': 'orange',
 'WIPER TRIP': '#00CC96',
 'DRILLING FORMATION': '#AB63FA',
 'CIRCULATE HOLE CLEANING': '#FFA15A',
 'CONNECTION': '#19D3F3',
 'DRILL OUT CEMENT': '#FF6692',
 'CEMENTING JOB': '#B6E880',
 'LAY DOWN BHA': '#FF97FF',
 'MAKE UP BHA': '#FECB52',
 'NPT': '#4D8BFA',
 'N/D BOP': '#F5663B',
 'N/U BOP': '#00D596',
 'RUNNING CASING IN': '#9B63FA',
 'STATIONARY': '#FFB85A',
 'STUCK PIPE': '#39D4F3',
 'WAIT ON CEMENT': '#FF3388',
 'RIG REPAIR': '#C6F980',
 'N/A': '#FFC0FF',
 'OTHER': '#FED752'}

# Temporary list to track activities for legend display
temp_activity_list = []

# Iterate over each row in the DataFrame to plot the activities
for idx, row in df.iterrows():
    # Show legend only for the first instance of each activity
    legend_show = row['Activity'] not in temp_activity_list
    if legend_show:
        temp_activity_list.append(row['Activity'])

    # Create a date range with 15-minute intervals, ensuring to include the end time
    time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')
    if time_range[-1] != row['EndDateTime']:
        time_range = time_range.union(pd.DatetimeIndex([row['EndDateTime']]))

    # Assume BitDepth is constant for simplicity
    bit_depth_values = [row['BitDepth']] * len(time_range)

    # Create and add a trace to the figure for each activity
    if idx == 0:
        df_plot = pd.DataFrame({'Datetime': time_range.values.tolist(), 'bit_depth': bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
    else:
        df_plot = pd.DataFrame({'Datetime': [time_range.values.tolist()[0]] + time_range.values.tolist(), 'bit_depth': before_bit_depth + bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]

# Update layout for the legend
legend_layout = {
    'orientation': 'h',
    'xref': "paper",
    'yref': "container",
    'y': -0.3,
    'x': 0.5,
    'xanchor': 'center',
    'yanchor': 'bottom'
}
fig.update_layout(legend=legend_layout)

# Set the plot titles and labels
fig.update_layout(
    height=600,
    width=1200,
    margin=dict(l=0, r=50, t=50, b=50),
    xaxis_title='Datetime',
    yaxis_title='Avg. Bit Depth (m)',
    yaxis_autorange='reversed',  # Reverse the y-axis to show deeper depths at the top
    legend_title='Activity'
)

# Show the plot
fig.show()

# ROP Stand vs On Bottom

In [ ]:
import plotly.graph_objects as go
ROP_df = ActSum_df.copy()
ROP_df['StartDateTime'] = pd.to_datetime(ROP_df['StartDateTime'])
ROP_df['EndDateTime'] = pd.to_datetime(ROP_df['EndDateTime'])

# Calculate MidDateTime as the average of StartDateTime and EndDateTime
ROP_df['MidDateTime'] = ROP_df['StartDateTime'] + (ROP_df['EndDateTime'] - ROP_df['StartDateTime']) / 2

idx_logic = (ROP_df['LABEL_Activity'].isin(["DRILLING FORMATION", 'CIRCULATE HOLE CLEANING','DRILL OUT CEMENT',])) & (ROP_df['LABEL_SubActivity'] == 'Connection')


ROP_df = ROP_df[idx_logic]

ROP_df['ROP_OnBottom'] = ROP_df['DrillingMeteragePerStand'] / (ROP_df['OnBottomDurationPerStand']/60) 
ROP_df['ROP_Stand'] = ROP_df['DrillingMeteragePerStand'] / (ROP_df['StandDuration']/60)
display(ROP_df[['MidDateTime', 'LABEL_SubActivity', 'LABEL_Activity', 'DrillingMeteragePerStand', 'OnBottomDurationPerStand', 'StandDuration', 'ROP_OnBottom', 'ROP_Stand']])
# ROP stand m/hr 



# Assuming your DataFrame is named df and contains columns 'ROP_OnBottom', 'ROP_Stand', and 'DateTime'
# First, convert your 'DateTime' column to a datetime type if it's not already
df = pd.DataFrame(ROP_df)
# df['DateTime'] = pd.to_datetime(df['DateTime'])

# Create a new Plotly figure
fig = go.Figure()
bar_width = 60*60*60*10
# Add ROP_OnBottom as one set of bars
fig.add_trace(go.Bar(
    x=df['MidDateTime'],
    y=df['ROP_OnBottom'],
    name='ROP On Bottom',
    marker_color='blue',  # You can choose a color
    #  width=bar_width 
))

# Add ROP_Stand as another set of bars
fig.add_trace(go.Bar(
    x=df['MidDateTime'],
    y=df['ROP_Stand'],
    name='ROP Stand',
    marker_color='red',  # You can choose a different color
    #  width=bar_width 
))

# Update the layout
fig.update_layout(
    barmode='group',  # This will group the bars side by side at each x-value (datetime)
        bargap=0, # gap between bars of adjacent location coordinates.
    bargroupgap=0, # gap between bars of the same location coordinate.
    # title='ROP On Bottom vs ROP Stand Over Time',
    xaxis_title='Datetime',
    yaxis_title='ROP(m/hr)',
    xaxis=dict(type='date')  # Ensuring x-axis is treated as date
)
fig.show()

# Stand Time Break down

In [ ]:
StandTime_df = ActSum_df.copy()
display(StandTime_df.columns)
display(StandTime_df)

In [ ]:
grouped_df = StandTime_df.groupby('Stand Group_Pred').agg({
    'RotateDrillingDuration': 'sum',
    'SlideDrillingDuration': 'sum',
    'ReamingDuration': 'sum',
    'ConnectionDuration': 'sum',
    'EndDateTime': 'max'
})

# Resetting index to make 'Stand Group_Pred' a column again
grouped_df = grouped_df.reset_index()
# grouped_df = StandTime_df.groupby('Stand Group_Pred')[[ 'RotateDrillingDuration', 'SlideDrillingDuration', 'ReamingDuration', 'ConnectionDuration']].sum()

# Resetting index to make 'Stand Group_Pred' a column again
# grouped_df = grouped_df.reset_index()
grouped_df

In [ ]:
# Create a new Plotly figure
fig = go.Figure()
bar_width = 60*60*60*10
for DurationCols in [ 'Rotate Drilling', 'Slide Drilling', 'Reaming', 'Connection']:
    # DurationCols = DurationCols.replace(' ', '').replace('Duration', '')
    
    fig.add_trace(go.Bar(
        x=grouped_df['EndDateTime'],
        y=grouped_df[DurationCols.replace(' ', '') + "Duration"],
        name=DurationCols,
        # marker_color='blue',  # You can choose a color
        #  width=bar_width 
    ))


# Update the layout
fig.update_layout(
    barmode='stack',  # This will group the bars side by side at each x-value (datetime)
    xaxis_title='Datetime',
    yaxis_title='Duration',
    xaxis=dict(type='date')  # Ensuring x-axis is treated as date
)
fig.show()

# Casing Trip Speed

In [ ]:
import pandas as pd 
import plotly.graph_objects as go
from plotly.subplots import make_subplots
ActSum_df = pd.read_csv('ActSum_Trial.csv', delimiter=';', index_col=0)
display(ActSum_df)

In [ ]:
CasingTrip_df = ActSum_df.copy()
CasingTrip_df = CasingTrip_df[CasingTrip_df['LABEL_Activity'].isin(['TRIP IN', 'TRIP OUT'])]
CasingTrip_df = CasingTrip_df.reset_index(drop=True)
CasingTrip_df['Stand Group_Pred_TRIP'] = None
# Step 2: Find indices where the activity is 'Connection'
connection_indices = CasingTrip_df[CasingTrip_df['LABEL_SubActivity'] == 'Connection'].index.tolist()
CasingTrip_df['StartDateTime'] = pd.to_datetime((CasingTrip_df['StartDateTime']))
CasingTrip_df['EndDateTime'] = pd.to_datetime((CasingTrip_df['EndDateTime']))
CasingTrip_df

In [ ]:
segments_start_list = []
segments_end_list = []

for i,indices in enumerate(connection_indices):
    if i == 0:
        segments_start_list.append(0)
        segments_end_list.append(indices)
    else:
        segments_start_list.append(connection_indices[i-1]+1)
        segments_end_list.append(indices)

for segments_start,segments_end, connection_idx in zip(segments_start_list, segments_end_list, connection_indices):
    ReferenceTime = CasingTrip_df.loc[connection_idx, 'StartDateTime']
    CasingTrip_df.loc[segments_start:segments_end, 'Stand Group_Pred_TRIP'] = int(CasingTrip_df.loc[connection_idx,'StartDateTime'].timestamp())
    CasingTrip_df.loc[segments_start:segments_end, 'Stand Group_Pred_TRIP'] = "Joint-" + CasingTrip_df.loc[segments_start:segments_end, 'Stand Group_Pred_TRIP'].astype(str)

CasingTrip_df = CasingTrip_df.dropna(subset = ['Stand Group_Pred_TRIP'])

CasingTrip_df

<!-- "Stand Group_Pred_TRIP"	"Duration"	"StartDateTim" -->

In [ ]:
FinalCasingTrip_df = CasingTrip_df[["Stand Group_Pred_TRIP", "LABEL_SubActivity", "Duration", "StartDateTime"]]
FinalCasingTrip_df = FinalCasingTrip_df.groupby("Stand Group_Pred_TRIP", as_index=False).agg(
        Duration=("Duration", "sum"),
        StartDateTime=("StartDateTime", "first")
    )

FinalCasingTrip_df.drop_duplicates(subset=['StartDateTime'], keep='first', inplace=True)
FinalCasingTrip_df['StartDateTime'] = pd.to_datetime(FinalCasingTrip_df['StartDateTime'])
FinalCasingTrip_df

In [ ]:
FinalCasingTrip_df['Duration_Hours'] = FinalCasingTrip_df['Duration'] / 3600
FinalCasingTrip_df['Joint Per Hour'] = 1/FinalCasingTrip_df['Duration_Hours']
FinalCasingTrip_df

In [ ]:
import plotly.graph_objects as go
import datetime

# StartDateTime = pd.to_datetime(FinalCasingTrip_df['StartDateTime'].dt.strftime('%Y-%m-%d %H'), format='%Y-%m-%d %H')
# Create the bar plot
fig = go.Figure(data=[
    go.Bar(name='Values', x=FinalCasingTrip_df['StartDateTime'].dt.strftime('.%Y-%m-%d %H:%M'), y=FinalCasingTrip_df['Duration'])
])
# df['HourFormatted'] = df['StartDateTime'].dt.strftime('"%Y-%m-%d %H:%M"')


# Update layout for better visuals
fig.update_layout(
    title='Casing Trip Duration',
    xaxis_title='Date',
    yaxis_title='Duration (s)',
     bargap=0
    # template='plotly_white'
)

# Show the plot
fig.show()

In [18]:
FinalCasingTrip_df = CasingTrip_df[["Stand Group_Pred_TRIP", "LABEL_SubActivity", "Duration", "StartDateTime"]]
FinalCasingTrip_df = FinalCasingTrip_df.groupby("Stand Group_Pred_TRIP", as_index=False).agg(
        Duration=("Duration", "sum"),
        StartDateTime=("StartDateTime", "first")
    )

In [ ]:
FinalCasingTripBreakdown_df = CasingTrip_df[["Stand Group_Pred_TRIP", "LABEL_SubActivity", "Duration", "StartDateTime"]]
FinalCasingTripBreakdown_df = FinalCasingTripBreakdown_df.groupby(["Stand Group_Pred_TRIP", "LABEL_SubActivity"], as_index=False).agg(
        Duration=("Duration", "sum"),
        StartDateTime=("StartDateTime", "first")
    )
FinalCasingTripBreakdown_df

In [ ]:
import plotly.graph_objects as go
import datetime

# StartDateTime = pd.to_datetime(FinalCasingTrip_df['StartDateTime'].dt.strftime('%Y-%m-%d %H'), format='%Y-%m-%d %H')
# Create the bar plot
fig = go.Figure()

for LABEL_SubActivity in FinalCasingTripBreakdown_df['LABEL_SubActivity'].unique():
    FinalCasingTripBreakdown_df_temp = FinalCasingTripBreakdown_df[FinalCasingTripBreakdown_df['LABEL_SubActivity'] == LABEL_SubActivity]
    fig.add_trace(go.Bar(name=LABEL_SubActivity, x=FinalCasingTripBreakdown_df_temp['StartDateTime'].dt.strftime('%Y-%m-%d %H:%M'), y=FinalCasingTripBreakdown_df_temp['Duration'])
)

# df['HourFormatted'] = df['StartDateTime'].dt.strftime('"%Y-%m-%d %H:%M"')


# Update layout for better visuals
fig.update_layout(
    title='Casing Trip Breakdown Duration',
    xaxis_title='Date',
    yaxis_title='Duration (s)',
     bargap=0,
     barmode='stack'
    # template='plotly_white'
)

# Show the plot
fig.show()

In [ ]:
FinalCasingTrip_df

In [ ]:
FinalCasingTripBreakdown_df

In [ ]:
import pandas as pd

# Sample data
data = {
    "Value": ["A", "A", "A", "B", "B", "C", "C", "C", "C", "A", "A", "A", "C", "C"]
}
df = pd.DataFrame(data)

# Detect group boundaries
df['GroupChange'] = (df['Value'] != df['Value'].shift()).cumsum()

# Group by the detected boundaries
group_info = df.groupby('GroupChange').apply(
    lambda x: {
        "Group": x['Value'].iloc[0],
        "StartIndex": x.index[0],
        "EndIndex": x.index[-1],
    }
)

# Convert to a DataFrame
result = pd.DataFrame(group_info.tolist())

print(result)

In [ ]:
type(result)