In [4]:
import pandas as pd 
import plotly.graph_objects as go
from plotly.subplots import make_subplots
ActSum_df = pd.read_csv('ActSum_Trial.csv', index_col=0)
display(ActSum_df)

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,2024-08-28,2024-08-28 17:50:10,2024-08-28 21:08:05,198.00,162.78,156.75,12.14,198.00,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724880585
1,2024-08-28,2024-08-28 21:08:30,2024-08-28 21:29:40,21.25,162.78,149.08,0.00,0.00,0.0,21.25,...,0.00,Reaming,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724880585
2,2024-08-28,2024-08-28 21:29:45,2024-08-28 21:37:00,7.33,162.78,161.92,0.00,0.00,0.0,0.00,...,28.58,Connection,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,NaN
3,2024-08-28,2024-08-28 21:37:05,2024-08-28 21:47:55,10.92,162.99,162.41,0.21,0.00,0.0,10.92,...,0.00,Reaming,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724903040
4,2024-08-28,2024-08-28 21:48:00,2024-08-28 21:49:45,1.83,163.10,163.06,0.10,1.83,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724903040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4331,2024-09-24,2024-09-24 20:16:00,2024-09-24 20:17:10,1.25,1653.02,1024.65,0.00,0.00,0.0,0.00,...,0.00,Moving,TRIP IN,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4332,2024-09-24,2024-09-24 20:17:15,2024-09-24 20:18:30,1.33,1653.02,1012.29,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP IN,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4333,2024-09-24,2024-09-24 20:18:35,2024-09-24 22:56:40,158.17,1653.02,436.42,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4334,2024-09-24,2024-09-24 22:56:45,2024-09-27 11:06:45,3610.08,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,OTHER,OTHER,0.0,34.0,0.0,NaN,"12-1/4""",NaN,NaN
4335,2024-09-27,2024-09-27 11:06:50,2024-09-28 09:21:55,1335.17,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,MAKE UP BHA,MAKE UP BHA,0.0,34.0,0.0,NaN,"12-1/4""",NaN,NaN

# Pie Chart Activity Duration

In [5]:
display(ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index())
display(ActSum_df.groupby(['LABEL_SubActivity'])['Duration'].sum().reset_index())
# ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index()

             LABEL_Activity  Duration
0             CEMENTING JOB   1133.58
1   CIRCULATE HOLE CLEANING    134.75
2          DRILL OUT CEMENT   1577.78
3        DRILLING FORMATION  18030.94
4              LAY DOWN BHA    677.58
5               MAKE UP BHA   2837.76
6                     OTHER   5039.93
7         RUNNING CASING IN   3356.25
8                STATIONARY   1012.18
9                   TRIP IN   3884.85
10                 TRIP OUT   4759.14
11           WAIT ON CEMENT   1674.75

    LABEL_SubActivity  Duration
0       CEMENTING JOB   1133.58
1         Circulation    991.78
2          Connection   1332.49
3         FALSE/Check     29.51
4        LAY DOWN BHA    677.58
5     Look and define     34.24
6         MAKE UP BHA   2837.76
7              Moving   1427.05
8               OTHER   5039.93
9   RUNNING CASING IN   3356.25
10            Reaming   5438.97
11    Rotary Drilling   9744.51
12         STATIONARY   1012.18
13     Slide Drilling   2848.44
14         Stationary   5912.36
15            TRIP IN     56.42
16     WAIT ON CEMENT   1674.75
17       Wash Up/Down    571.69

In [6]:
SumDuration_Act = (ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index())
SumDuration_SubAct = (ActSum_df.groupby(['LABEL_SubActivity'])['Duration'].sum().reset_index())


fig = go.Figure()
fig.add_trace(go.Pie(labels=SumDuration_Act['LABEL_Activity'], hole=0.5,
                     values=SumDuration_Act['Duration'], ))

LegendDict= {
        'legend':{
            'orientation':'h', 
            'xref':"paper",
            'yref':"container",
            'y':-0.3,
            'x':0.5,
            'xanchor':'center', 
            'yanchor':'bottom', 
            }
        }

fig.update_layout(LegendDict)
fig.update_layout(
        height=600,
        width=600,
        margin=dict(l=0, r=0, t=50, b=50),
        title={'text': "Activity Duration", 'x': 0.5, 'xanchor': 'center'},
)
fig.show()

In [7]:
ActSum_df

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,2024-08-28,2024-08-28 17:50:10,2024-08-28 21:08:05,198.00,162.78,156.75,12.14,198.00,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724880585
1,2024-08-28,2024-08-28 21:08:30,2024-08-28 21:29:40,21.25,162.78,149.08,0.00,0.00,0.0,21.25,...,0.00,Reaming,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724880585
2,2024-08-28,2024-08-28 21:29:45,2024-08-28 21:37:00,7.33,162.78,161.92,0.00,0.00,0.0,0.00,...,28.58,Connection,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,NaN
3,2024-08-28,2024-08-28 21:37:05,2024-08-28 21:47:55,10.92,162.99,162.41,0.21,0.00,0.0,10.92,...,0.00,Reaming,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724903040
4,2024-08-28,2024-08-28 21:48:00,2024-08-28 21:49:45,1.83,163.10,163.06,0.10,1.83,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724903040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4331,2024-09-24,2024-09-24 20:16:00,2024-09-24 20:17:10,1.25,1653.02,1024.65,0.00,0.00,0.0,0.00,...,0.00,Moving,TRIP IN,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4332,2024-09-24,2024-09-24 20:17:15,2024-09-24 20:18:30,1.33,1653.02,1012.29,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP IN,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4333,2024-09-24,2024-09-24 20:18:35,2024-09-24 22:56:40,158.17,1653.02,436.42,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4334,2024-09-24,2024-09-24 22:56:45,2024-09-27 11:06:45,3610.08,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,OTHER,OTHER,0.0,34.0,0.0,NaN,"12-1/4""",NaN,NaN
4335,2024-09-27,2024-09-27 11:06:50,2024-09-28 09:21:55,1335.17,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,MAKE UP BHA,MAKE UP BHA,0.0,34.0,0.0,NaN,"12-1/4""",NaN,NaN

# Bar Chart Drilling Meterage

In [8]:
import plotly.express as px

# Group by the new 'Date' column and sum the 'DrillingMeterage'
DrilingMeterage_df = ActSum_df.groupby('Date')['DrillingMeterage'].sum().reset_index()
DrilingMeterage_df
DrilingMeterage_df['Date'] = pd.to_datetime(DrilingMeterage_df['Date']).dt.date

# Create a bar chart using Plotly
fig = px.bar(DrilingMeterage_df, x='Date', y='DrillingMeterage',
             labels={'Date': 'Date', 'DrillingMeterage': 'Total Drilling Meterage'},
             )
fig.update_xaxes(
    dtick="D",)
# Show the plot
fig.show()

In [9]:
import pandas as pd
import plotly.graph_objects as go

# Sample DataFrame - replace with your actual data
data = {
    'StartDateTime': ['2024-01-01 08:00', '2024-01-01 10:00', '2024-01-01 14:00'],
    'EndDateTime': ['2024-01-01 10:00', '2024-01-01 14:00', '2024-01-01 16:00'],
    'BitDepth': [100, 200, 150],
    'Activity': ['Drilling', 'Moving', 'Drilling']
}
df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']

In [10]:
df['LABEL_Activity'].unique()

array(['DRILLING FORMATION', 'CIRCULATE HOLE CLEANING', 'TRIP OUT',
       'TRIP IN', 'LAY DOWN BHA', 'RUNNING CASING IN', 'CEMENTING JOB',
       'WAIT ON CEMENT', 'MAKE UP BHA', 'DRILL OUT CEMENT', 'STATIONARY',
       'OTHER'], dtype=object)

# Depth vs Time

In [11]:
import pandas as pd
import plotly.graph_objects as go
from datetime import timedelta
def round_up_to_next_15_minutes(dt):
    n_minutes = 15 - dt.minute % 15
    return dt + timedelta(minutes=n_minutes) if n_minutes != 15 else dt


df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']
# Convert the 'StartDateTime' and 'EndDateTime' columns to datetime type
df['StartDateTime'] = pd.to_datetime(df['StartDateTime'])
df['EndDateTime'] = pd.to_datetime(df['EndDateTime'])

# Sort the DataFrame by 'StartDateTime'
df = df.sort_values('StartDateTime')
df = df.reset_index(drop=True)

# Create a new Plotly figure
fig = go.Figure()

# Define your own colors for each activity
# activity_colors = {'Drilling': 'blue', 'Moving': 'red', 'Stationary': 'green'}
activity_colors ={'TRIP OUT': '#636EFA',
 'TRIP IN': '#EF553B',
 'CEMENTING JOB': '#00CC96',
 'OTHER': '#AB63FA',
 'WAIT ON CEMENT': '#FFA15A',
 'DRILL OUT CEMENT': '#19D3F3',
 'DRILLING FORMATION': '#FF6692'}
temp_actvity_list = []

# Plot each activity as a separate line segment
for idx, row in df.iterrows():
    if row['Activity'] not in temp_actvity_list: 
        temp_actvity_list.append(row['Activity'])
        legend_show = True
    else:
        legend_show = False
    # Adjust EndDateTime to be on a 15-minute interval if it's not
    # adjusted_end_time = round_up_to_next_15_minutes(row['EndDateTime'])

    # Create a date range with 15-minute intervals
    time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')

    # Ensure that the actual end time is included in the range
    if time_range[-1] != row['EndDateTime']:
        time_range = time_range.union(pd.DatetimeIndex([row['EndDateTime']]))

    # Interpolate BitDepth for each time point (assuming BitDepth is constant for simplicity)
    bit_depth_values = [row['BitDepth']] * len(time_range)
    # Create a date range with 15-minute intervals
    # time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')

    # Interpolate BitDepth for each time point (assuming BitDepth is constant for simplicity)
    bit_depth_values = [row['BitDepth']] * len(time_range)
    
    if idx == 0:
        df_plot = pd.DataFrame({'Datetime': time_range.values.tolist(), 'bit_depth': bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
    else:
        df_plot = pd.DataFrame({'Datetime': [time_range.values.tolist()[0]] + time_range.values.tolist(), 'bit_depth': before_bit_depth + bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
LegendDict= {
        'legend':{
            'orientation':'h', 
            'xref':"paper",
            'yref':"container",
            'y':-0.3,
            'x':0.5,
            'xanchor':'center', 
            'yanchor':'bottom', 
            }
        }

fig.update_layout(LegendDict)

# Set the plot titles and labels
fig.update_layout(
    # title='Time vs Bit Depth with Activity Intervals',
    height=600,
    width=1200,
    margin=dict(l=0, r=50, t=50, b=50),
    xaxis_title='Datetime',
    yaxis_title='Avg. Bit Depth (m)',
    yaxis_autorange='reversed',
    legend_title='Activity'
)

# Show the plot
fig.show()

KeyError: 'CIRCULATE HOLE CLEANING'

In [ ]:
import pandas as pd
import plotly.graph_objects as go

# Create a DataFrame and rename columns for clarity
df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']

# Convert the 'StartDateTime' and 'EndDateTime' columns to datetime type
df['StartDateTime'] = pd.to_datetime(df['StartDateTime'])
df['EndDateTime'] = pd.to_datetime(df['EndDateTime'])

# Sort the DataFrame by 'StartDateTime' for chronological plotting
df = df.sort_values('StartDateTime').reset_index(drop=True)

# Create a new Plotly figure
fig = go.Figure()

# Define custom colors for each activity type
activity_colors = {'TRIP IN': 'red',
 'TRIP OUT': 'orange',
 'WIPER TRIP': '#00CC96',
 'DRILLING FORMATION': '#AB63FA',
 'CIRCULATE HOLE CLEANING': '#FFA15A',
 'CONNECTION': '#19D3F3',
 'DRILL OUT CEMENT': '#FF6692',
 'CEMENTING JOB': '#B6E880',
 'LAY DOWN BHA': '#FF97FF',
 'MAKE UP BHA': '#FECB52',
 'NPT': '#4D8BFA',
 'N/D BOP': '#F5663B',
 'N/U BOP': '#00D596',
 'RUNNING CASING IN': '#9B63FA',
 'STATIONARY': '#FFB85A',
 'STUCK PIPE': '#39D4F3',
 'WAIT ON CEMENT': '#FF3388',
 'RIG REPAIR': '#C6F980',
 'N/A': '#FFC0FF',
 'OTHER': '#FED752'}

# Temporary list to track activities for legend display
temp_activity_list = []

# Iterate over each row in the DataFrame to plot the activities
for idx, row in df.iterrows():
    # Show legend only for the first instance of each activity
    legend_show = row['Activity'] not in temp_activity_list
    if legend_show:
        temp_activity_list.append(row['Activity'])

    # Create a date range with 15-minute intervals, ensuring to include the end time
    time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')
    if time_range[-1] != row['EndDateTime']:
        time_range = time_range.union(pd.DatetimeIndex([row['EndDateTime']]))

    # Assume BitDepth is constant for simplicity
    bit_depth_values = [row['BitDepth']] * len(time_range)

    # Create and add a trace to the figure for each activity
    if idx == 0:
        df_plot = pd.DataFrame({'Datetime': time_range.values.tolist(), 'bit_depth': bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
    else:
        df_plot = pd.DataFrame({'Datetime': [time_range.values.tolist()[0]] + time_range.values.tolist(), 'bit_depth': before_bit_depth + bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]

# Update layout for the legend
legend_layout = {
    'orientation': 'h',
    'xref': "paper",
    'yref': "container",
    'y': -0.3,
    'x': 0.5,
    'xanchor': 'center',
    'yanchor': 'bottom'
}
fig.update_layout(legend=legend_layout)

# Set the plot titles and labels
fig.update_layout(
    height=600,
    width=1200,
    margin=dict(l=0, r=50, t=50, b=50),
    xaxis_title='Datetime',
    yaxis_title='Avg. Bit Depth (m)',
    yaxis_autorange='reversed',  # Reverse the y-axis to show deeper depths at the top
    legend_title='Activity'
)

# Show the plot
fig.show()

# ROP Stand vs On Bottom

In [12]:
import plotly.graph_objects as go
ROP_df = ActSum_df.copy()
ROP_df['StartDateTime'] = pd.to_datetime(ROP_df['StartDateTime'])
ROP_df['EndDateTime'] = pd.to_datetime(ROP_df['EndDateTime'])

# Calculate MidDateTime as the average of StartDateTime and EndDateTime
ROP_df['MidDateTime'] = ROP_df['StartDateTime'] + (ROP_df['EndDateTime'] - ROP_df['StartDateTime']) / 2

idx_logic = (ROP_df['LABEL_Activity'].isin(["DRILLING FORMATION", 'CIRCULATE HOLE CLEANING','DRILL OUT CEMENT',])) & (ROP_df['LABEL_SubActivity'] == 'Connection')


ROP_df = ROP_df[idx_logic]

ROP_df['ROP_OnBottom'] = ROP_df['DrillingMeteragePerStand'] / (ROP_df['OnBottomDurationPerStand']/60) 
ROP_df['ROP_Stand'] = ROP_df['DrillingMeteragePerStand'] / (ROP_df['StandDuration']/60)
display(ROP_df[['MidDateTime', 'LABEL_SubActivity', 'LABEL_Activity', 'DrillingMeteragePerStand', 'OnBottomDurationPerStand', 'StandDuration', 'ROP_OnBottom', 'ROP_Stand']])
# ROP stand m/hr 



# Assuming your DataFrame is named df and contains columns 'ROP_OnBottom', 'ROP_Stand', and 'DateTime'
# First, convert your 'DateTime' column to a datetime type if it's not already
df = pd.DataFrame(ROP_df)
# df['DateTime'] = pd.to_datetime(df['DateTime'])

# Create a new Plotly figure
fig = go.Figure()
bar_width = 60*60*60*10
# Add ROP_OnBottom as one set of bars
fig.add_trace(go.Bar(
    x=df['MidDateTime'],
    y=df['ROP_OnBottom'],
    name='ROP On Bottom',
    marker_color='blue',  # You can choose a color
    #  width=bar_width 
))

# Add ROP_Stand as another set of bars
fig.add_trace(go.Bar(
    x=df['MidDateTime'],
    y=df['ROP_Stand'],
    name='ROP Stand',
    marker_color='red',  # You can choose a different color
    #  width=bar_width 
))

# Update the layout
fig.update_layout(
    barmode='group',  # This will group the bars side by side at each x-value (datetime)
        bargap=0, # gap between bars of adjacent location coordinates.
    bargroupgap=0, # gap between bars of the same location coordinate.
    # title='ROP On Bottom vs ROP Stand Over Time',
    xaxis_title='Datetime',
    yaxis_title='ROP(m/hr)',
    xaxis=dict(type='date')  # Ensuring x-axis is treated as date
)
fig.show()

,MidDateTime,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,OnBottomDurationPerStand,StandDuration,ROP_OnBottom,ROP_Stand
2,2024-08-28 21:33:22.500,Connection,DRILLING FORMATION,0.00,0.00,28.58,NaN,0.000000
32,2024-08-29 03:47:35.000,Connection,DRILLING FORMATION,27.66,304.32,374.16,5.453470,4.435536
52,2024-08-29 13:01:40.000,Connection,DRILLING FORMATION,0.00,0.00,32.17,NaN,0.000000
75,2024-08-29 22:08:42.500,Connection,DRILLING FORMATION,28.40,426.91,548.24,3.991474,3.108128
77,2024-08-29 22:18:30.000,Connection,DRILLING FORMATION,0.00,0.00,5.75,NaN,0.000000
...,...,...,...,...,...,...,...,...
4078,2024-09-22 07:25:40.000,Connection,DRILLING FORMATION,18.79,112.25,183.00,10.043653,6.160656
4088,2024-09-22 10:18:35.000,Connection,DRILLING FORMATION,19.19,111.17,172.51,10.357111,6.674396
4098,2024-09-22 13:16:32.500,Connection,DRILLING FORMATION,19.27,98.51,179.08,11.736880,6.456332
4106,2024-09-22 16:05:07.500,Connection,DRILLING FORMATION,19.11,103.42,170.08,11.086830,6.741533
4118,2024-09-22 19:37:55.000,Connection,DRILLING FORMATION,18.88,127.43,221.35,8.889586,5.117687

# Stand Time Break down

In [13]:
StandTime_df = ActSum_df.copy()
display(StandTime_df.columns)
display(StandTime_df)

Index(['Date', 'StartDateTime', 'EndDateTime', 'Duration', 'Hole_Depth_max',
       'Bit_Depth_avg', 'DrillingMeterage', 'RotateDrillingDuration',
       'SlideDrillingDuration', 'ReamingDuration', 'ConnectionDuration',
       'LABEL_ConnectionActivity', 'OnBottomDurationPerStand', 'StandDuration',
       'LABEL_SubActivity', 'LABEL_Activity', 'DrillingMeteragePerStand',
       'InSlip_Treshold', 'stand_on_bottom', 'PIC', 'Section', 'Remarks',
       'Stand Group_Pred'],
      dtype='object')

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,2024-08-28,2024-08-28 17:50:10,2024-08-28 21:08:05,198.00,162.78,156.75,12.14,198.00,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724880585
1,2024-08-28,2024-08-28 21:08:30,2024-08-28 21:29:40,21.25,162.78,149.08,0.00,0.00,0.0,21.25,...,0.00,Reaming,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724880585
2,2024-08-28,2024-08-28 21:29:45,2024-08-28 21:37:00,7.33,162.78,161.92,0.00,0.00,0.0,0.00,...,28.58,Connection,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,NaN
3,2024-08-28,2024-08-28 21:37:05,2024-08-28 21:47:55,10.92,162.99,162.41,0.21,0.00,0.0,10.92,...,0.00,Reaming,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724903040
4,2024-08-28,2024-08-28 21:48:00,2024-08-28 21:49:45,1.83,163.10,163.06,0.10,1.83,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28.0,0.0,NaN,"26""",NaN,Drilling Stand-1724903040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4331,2024-09-24,2024-09-24 20:16:00,2024-09-24 20:17:10,1.25,1653.02,1024.65,0.00,0.00,0.0,0.00,...,0.00,Moving,TRIP IN,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4332,2024-09-24,2024-09-24 20:17:15,2024-09-24 20:18:30,1.33,1653.02,1012.29,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP IN,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4333,2024-09-24,2024-09-24 20:18:35,2024-09-24 22:56:40,158.17,1653.02,436.42,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.0,34.0,0.0,NaN,"17-1/2""",NaN,NaN
4334,2024-09-24,2024-09-24 22:56:45,2024-09-27 11:06:45,3610.08,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,OTHER,OTHER,0.0,34.0,0.0,NaN,"12-1/4""",NaN,NaN
4335,2024-09-27,2024-09-27 11:06:50,2024-09-28 09:21:55,1335.17,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,MAKE UP BHA,MAKE UP BHA,0.0,34.0,0.0,NaN,"12-1/4""",NaN,NaN

In [14]:
grouped_df = StandTime_df.groupby('Stand Group_Pred').agg({
    'RotateDrillingDuration': 'sum',
    'SlideDrillingDuration': 'sum',
    'ReamingDuration': 'sum',
    'ConnectionDuration': 'sum',
    'EndDateTime': 'max'
})

# Resetting index to make 'Stand Group_Pred' a column again
grouped_df = grouped_df.reset_index()
# grouped_df = StandTime_df.groupby('Stand Group_Pred')[[ 'RotateDrillingDuration', 'SlideDrillingDuration', 'ReamingDuration', 'ConnectionDuration']].sum()

# Resetting index to make 'Stand Group_Pred' a column again
# grouped_df = grouped_df.reset_index()
grouped_df

,Stand Group_Pred,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,ConnectionDuration,EndDateTime
0,Drilling Stand-1724880585,198.00,0.00,21.25,0.0,2024-08-28 21:29:40
1,Drilling Stand-1724903040,221.82,82.50,56.27,0.0,2024-08-29 03:43:55
2,Drilling Stand-1724936330,237.33,224.99,65.59,0.0,2024-08-29 12:58:45
3,Drilling Stand-1724969080,186.33,240.58,104.50,0.0,2024-08-29 22:04:35
4,Drilling Stand-1724969910,0.00,0.00,5.67,0.0,2024-08-29 22:18:25
...,...,...,...,...,...,...
73,Drilling Stand-1726989375,112.25,0.00,50.58,0.0,2024-09-22 07:16:10
74,Drilling Stand-1726999775,111.17,0.00,42.09,0.0,2024-09-22 10:09:30
75,Drilling Stand-1727010385,98.51,0.00,58.83,0.0,2024-09-22 13:06:20
76,Drilling Stand-1727020410,103.42,0.00,41.92,0.0,2024-09-22 15:53:25
77,Drilling Stand-1727032665,127.43,0.00,51.67,0.0,2024-09-22 19:17:40

In [15]:
# Create a new Plotly figure
fig = go.Figure()
bar_width = 60*60*60*10
for DurationCols in [ 'Rotate Drilling', 'Slide Drilling', 'Reaming', 'Connection']:
    # DurationCols = DurationCols.replace(' ', '').replace('Duration', '')
    
    fig.add_trace(go.Bar(
        x=grouped_df['EndDateTime'],
        y=grouped_df[DurationCols.replace(' ', '') + "Duration"],
        name=DurationCols,
        # marker_color='blue',  # You can choose a color
        #  width=bar_width 
    ))


# Update the layout
fig.update_layout(
    barmode='stack',  # This will group the bars side by side at each x-value (datetime)
    xaxis_title='Datetime',
    yaxis_title='Duration',
    xaxis=dict(type='date')  # Ensuring x-axis is treated as date
)
fig.show()

# Casing Trip Speed

In [12]:
import pandas as pd 
import plotly.graph_objects as go
from plotly.subplots import make_subplots
ActSum_df = pd.read_csv('ActSum_Trial.csv', delimiter=';', index_col=0)
display(ActSum_df)

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,28/08/2024,28/08/2024 17:50,28/08/2024 21:08,198.00,162.78,156.75,12.14,198.00,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724880585
1,28/08/2024,28/08/2024 21:08,28/08/2024 21:29,21.25,162.78,149.08,0.00,0.00,0.0,21.25,...,0.00,Reaming,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724880585
2,28/08/2024,28/08/2024 21:29,28/08/2024 21:37,7.33,162.78,161.92,0.00,0.00,0.0,0.00,...,28.58,Connection,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,NaN
3,28/08/2024,28/08/2024 21:37,28/08/2024 21:47,10.92,162.99,162.41,0.21,0.00,0.0,10.92,...,0.00,Reaming,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724903040
4,28/08/2024,28/08/2024 21:48,28/08/2024 21:49,1.83,163.10,163.06,0.10,1.83,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.0,28,0,NaN,"26""",NaN,Drilling Stand-1724903040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4331,24/09/2024,24/09/2024 20:16,24/09/2024 20:17,1.25,1653.02,1024.65,0.00,0.00,0.0,0.00,...,0.00,Moving,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4332,24/09/2024,24/09/2024 20:17,24/09/2024 20:18,1.33,1653.02,1012.29,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4333,24/09/2024,24/09/2024 20:18,24/09/2024 22:56,158.17,1653.02,436.42,0.00,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.0,34,0,NaN,"17-1/2""",NaN,NaN
4334,24/09/2024,24/09/2024 22:56,27/09/2024 11:06,3610.08,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,OTHER,OTHER,0.0,34,0,NaN,"12-1/4""",NaN,NaN
4335,27/09/2024,27/09/2024 11:06,28/09/2024 09:21,1335.17,1653.02,0.00,0.00,0.00,0.0,0.00,...,0.00,MAKE UP BHA,MAKE UP BHA,0.0,34,0,NaN,"12-1/4""",NaN,NaN

In [13]:
CasingTrip_df = ActSum_df.copy()
CasingTrip_df = CasingTrip_df[CasingTrip_df['LABEL_Activity'].isin(['TRIP IN', 'TRIP OUT'])]
CasingTrip_df = CasingTrip_df.reset_index(drop=True)
CasingTrip_df['Stand Group_Pred_TRIP'] = None
# Step 2: Find indices where the activity is 'Connection'
connection_indices = CasingTrip_df[CasingTrip_df['LABEL_SubActivity'] == 'Connection'].index.tolist()
CasingTrip_df['StartDateTime'] = pd.to_datetime((CasingTrip_df['StartDateTime']))
CasingTrip_df['EndDateTime'] = pd.to_datetime((CasingTrip_df['EndDateTime']))
CasingTrip_df

C:\Users\irsya\AppData\Local\Temp\ipykernel_27216\3786270979.py:7: UserWarning:

Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.

C:\Users\irsya\AppData\Local\Temp\ipykernel_27216\3786270979.py:8: UserWarning:

Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred,Stand Group_Pred_TRIP
0,31/08/2024,2024-08-31 20:49:00,2024-08-31 20:55:00,5.83,400.50,389.10,0.0,0.0,0.0,0.0,...,Moving,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,NaN
1,31/08/2024,2024-08-31 20:55:00,2024-08-31 20:55:00,0.25,400.50,378.99,0.0,0.0,0.0,0.0,...,Stationary,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,NaN
2,31/08/2024,2024-08-31 20:55:00,2024-08-31 20:55:00,0.42,400.50,379.14,0.0,0.0,0.0,0.0,...,Moving,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,NaN
3,31/08/2024,2024-08-31 20:55:00,2024-08-31 20:56:00,0.67,400.50,379.40,0.0,0.0,0.0,0.0,...,Stationary,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,NaN
4,31/08/2024,2024-08-31 20:56:00,2024-08-31 20:57:00,0.58,400.50,379.23,0.0,0.0,0.0,0.0,...,Moving,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,24/09/2024,2024-09-24 20:13:00,2024-09-24 20:14:00,0.33,1653.02,1041.97,0.0,0.0,0.0,0.0,...,Circulation,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,NaN
2981,24/09/2024,2024-09-24 20:14:00,2024-09-24 20:15:00,1.92,1653.02,1041.97,0.0,0.0,0.0,0.0,...,Stationary,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,NaN
2982,24/09/2024,2024-09-24 20:16:00,2024-09-24 20:17:00,1.25,1653.02,1024.65,0.0,0.0,0.0,0.0,...,Moving,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,NaN
2983,24/09/2024,2024-09-24 20:17:00,2024-09-24 20:18:00,1.33,1653.02,1012.29,0.0,0.0,0.0,0.0,...,Stationary,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,NaN
2984,24/09/2024,2024-09-24 20:18:00,2024-09-24 22:56:00,158.17,1653.02,436.42,0.0,0.0,0.0,0.0,...,Stationary,TRIP OUT,0.0,34,0,NaN,"17-1/2""",NaN,NaN,NaN

In [14]:
segments_start_list = []
segments_end_list = []

for i,indices in enumerate(connection_indices):
    if i == 0:
        segments_start_list.append(0)
        segments_end_list.append(indices)
    else:
        segments_start_list.append(connection_indices[i-1]+1)
        segments_end_list.append(indices)

for segments_start,segments_end, connection_idx in zip(segments_start_list, segments_end_list, connection_indices):
    ReferenceTime = CasingTrip_df.loc[connection_idx, 'StartDateTime']
    CasingTrip_df.loc[segments_start:segments_end, 'Stand Group_Pred_TRIP'] = int(CasingTrip_df.loc[connection_idx,'StartDateTime'].timestamp())
    CasingTrip_df.loc[segments_start:segments_end, 'Stand Group_Pred_TRIP'] = "Joint-" + CasingTrip_df.loc[segments_start:segments_end, 'Stand Group_Pred_TRIP'].astype(str)

CasingTrip_df = CasingTrip_df.dropna(subset = ['Stand Group_Pred_TRIP'])

CasingTrip_df

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred,Stand Group_Pred_TRIP
0,31/08/2024,2024-08-31 20:49:00,2024-08-31 20:55:00,5.83,400.50,389.10,0.0,0.0,0.0,0.0,...,Moving,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,Joint-1725138180
1,31/08/2024,2024-08-31 20:55:00,2024-08-31 20:55:00,0.25,400.50,378.99,0.0,0.0,0.0,0.0,...,Stationary,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,Joint-1725138180
2,31/08/2024,2024-08-31 20:55:00,2024-08-31 20:55:00,0.42,400.50,379.14,0.0,0.0,0.0,0.0,...,Moving,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,Joint-1725138180
3,31/08/2024,2024-08-31 20:55:00,2024-08-31 20:56:00,0.67,400.50,379.40,0.0,0.0,0.0,0.0,...,Stationary,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,Joint-1725138180
4,31/08/2024,2024-08-31 20:56:00,2024-08-31 20:57:00,0.58,400.50,379.23,0.0,0.0,0.0,0.0,...,Moving,TRIP OUT,0.0,28,0,NaN,"26""",NaN,NaN,Joint-1725138180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2965,24/09/2024,2024-09-24 19:42:00,2024-09-24 19:43:00,0.92,1653.02,1042.21,0.0,0.0,0.0,0.0,...,Circulation,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,Joint-1727207100
2966,24/09/2024,2024-09-24 19:43:00,2024-09-24 19:45:00,1.67,1653.02,1042.21,0.0,0.0,0.0,0.0,...,Stationary,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,Joint-1727207100
2967,24/09/2024,2024-09-24 19:45:00,2024-09-24 19:45:00,0.17,1653.02,1042.21,0.0,0.0,0.0,0.0,...,Connection,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,Joint-1727207100
2968,24/09/2024,2024-09-24 19:45:00,2024-09-24 19:47:00,1.92,1653.02,1042.22,0.0,0.0,0.0,0.0,...,Stationary,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,Joint-1727207220
2969,24/09/2024,2024-09-24 19:47:00,2024-09-24 19:47:00,0.33,1653.02,854.70,0.0,0.0,0.0,0.0,...,Connection,TRIP IN,0.0,34,0,NaN,"17-1/2""",NaN,NaN,Joint-1727207220

<!-- "Stand Group_Pred_TRIP"	"Duration"	"StartDateTim" -->

In [15]:
FinalCasingTrip_df = CasingTrip_df[["Stand Group_Pred_TRIP", "LABEL_SubActivity", "Duration", "StartDateTime"]]
FinalCasingTrip_df = FinalCasingTrip_df.groupby("Stand Group_Pred_TRIP", as_index=False).agg(
        Duration=("Duration", "sum"),
        StartDateTime=("StartDateTime", "first")
    )

FinalCasingTrip_df.drop_duplicates(subset=['StartDateTime'], keep='first', inplace=True)
FinalCasingTrip_df['StartDateTime'] = pd.to_datetime(FinalCasingTrip_df['StartDateTime'])
FinalCasingTrip_df

    Stand Group_Pred_TRIP  Duration       StartDateTime
0        Joint-1725138180     14.58 2024-08-31 20:49:00
1        Joint-1725138240      0.16 2024-08-31 21:04:00
3        Joint-1725140820      9.09 2024-08-31 21:38:00
4        Joint-1725141480     11.24 2024-08-31 21:47:00
5        Joint-1725142500     17.17 2024-08-31 21:58:00
..                    ...       ...                 ...
240      Joint-1727202240      0.67 2024-09-24 18:24:00
242      Joint-1727204040     28.14 2024-09-24 18:26:00
243      Joint-1727204220      2.84 2024-09-24 18:55:00
244      Joint-1727207100     47.31 2024-09-24 18:57:00
245      Joint-1727207220      2.25 2024-09-24 19:45:00

[237 rows x 3 columns]

In [16]:
FinalCasingTrip_df['Duration_Hours'] = FinalCasingTrip_df['Duration'] / 3600
FinalCasingTrip_df['Joint Per Hour'] = 1/FinalCasingTrip_df['Duration_Hours']
FinalCasingTrip_df

,Stand Group_Pred_TRIP,Duration,StartDateTime,Duration_Hours,Joint Per Hour
0,Joint-1725138180,14.58,2024-08-31 20:49:00,0.004050,246.913580
1,Joint-1725138240,0.16,2024-08-31 21:04:00,0.000044,22500.000000
3,Joint-1725140820,9.09,2024-08-31 21:38:00,0.002525,396.039604
4,Joint-1725141480,11.24,2024-08-31 21:47:00,0.003122,320.284698
5,Joint-1725142500,17.17,2024-08-31 21:58:00,0.004769,209.668026
...,...,...,...,...,...
240,Joint-1727202240,0.67,2024-09-24 18:24:00,0.000186,5373.134328
242,Joint-1727204040,28.14,2024-09-24 18:26:00,0.007817,127.931770
243,Joint-1727204220,2.84,2024-09-24 18:55:00,0.000789,1267.605634
244,Joint-1727207100,47.31,2024-09-24 18:57:00,0.013142,76.093849
245,Joint-1727207220,2.25,2024-09-24 19:45:00,0.000625,1600.000000

In [17]:
import plotly.graph_objects as go
import datetime

# StartDateTime = pd.to_datetime(FinalCasingTrip_df['StartDateTime'].dt.strftime('%Y-%m-%d %H'), format='%Y-%m-%d %H')
# Create the bar plot
fig = go.Figure(data=[
    go.Bar(name='Values', x=FinalCasingTrip_df['StartDateTime'].dt.strftime('.%Y-%m-%d %H:%M'), y=FinalCasingTrip_df['Duration'])
])
# df['HourFormatted'] = df['StartDateTime'].dt.strftime('"%Y-%m-%d %H:%M"')


# Update layout for better visuals
fig.update_layout(
    title='Casing Trip Duration',
    xaxis_title='Date',
    yaxis_title='Duration (s)',
     bargap=0
    # template='plotly_white'
)

# Show the plot
fig.show()

In [18]:
FinalCasingTrip_df = CasingTrip_df[["Stand Group_Pred_TRIP", "LABEL_SubActivity", "Duration", "StartDateTime"]]
FinalCasingTrip_df = FinalCasingTrip_df.groupby("Stand Group_Pred_TRIP", as_index=False).agg(
        Duration=("Duration", "sum"),
        StartDateTime=("StartDateTime", "first")
    )

In [19]:
FinalCasingTripBreakdown_df = CasingTrip_df[["Stand Group_Pred_TRIP", "LABEL_SubActivity", "Duration", "StartDateTime"]]
FinalCasingTripBreakdown_df = FinalCasingTripBreakdown_df.groupby(["Stand Group_Pred_TRIP", "LABEL_SubActivity"], as_index=False).agg(
        Duration=("Duration", "sum"),
        StartDateTime=("StartDateTime", "first")
    )
FinalCasingTripBreakdown_df

    Stand Group_Pred_TRIP LABEL_SubActivity  Duration       StartDateTime
0        Joint-1725138180        Connection      0.33 2024-08-31 21:03:00
1        Joint-1725138180            Moving      6.83 2024-08-31 20:49:00
2        Joint-1725138180        Stationary      7.42 2024-08-31 20:55:00
3        Joint-1725138240        Connection      0.08 2024-08-31 21:04:00
4        Joint-1725138240        Stationary      0.08 2024-08-31 21:04:00
..                    ...               ...       ...                 ...
701      Joint-1727207100           Reaming     20.48 2024-09-24 19:21:00
702      Joint-1727207100        Stationary      2.33 2024-09-24 18:57:00
703      Joint-1727207100      Wash Up/Down      0.08 2024-09-24 19:42:00
704      Joint-1727207220        Connection      0.33 2024-09-24 19:47:00
705      Joint-1727207220        Stationary      1.92 2024-09-24 19:45:00

[706 rows x 4 columns]

In [20]:
import plotly.graph_objects as go
import datetime

# StartDateTime = pd.to_datetime(FinalCasingTrip_df['StartDateTime'].dt.strftime('%Y-%m-%d %H'), format='%Y-%m-%d %H')
# Create the bar plot
fig = go.Figure()

for LABEL_SubActivity in FinalCasingTripBreakdown_df['LABEL_SubActivity'].unique():
    FinalCasingTripBreakdown_df_temp = FinalCasingTripBreakdown_df[FinalCasingTripBreakdown_df['LABEL_SubActivity'] == LABEL_SubActivity]
    fig.add_trace(go.Bar(name=LABEL_SubActivity, x=FinalCasingTripBreakdown_df_temp['StartDateTime'].dt.strftime('%Y-%m-%d %H:%M'), y=FinalCasingTripBreakdown_df_temp['Duration'])
)

# df['HourFormatted'] = df['StartDateTime'].dt.strftime('"%Y-%m-%d %H:%M"')


# Update layout for better visuals
fig.update_layout(
    title='Casing Trip Breakdown Duration',
    xaxis_title='Date',
    yaxis_title='Duration (s)',
     bargap=0,
     barmode='stack'
    # template='plotly_white'
)

# Show the plot
fig.show()

In [21]:
FinalCasingTrip_df

    Stand Group_Pred_TRIP  Duration       StartDateTime
0        Joint-1725138180     14.58 2024-08-31 20:49:00
1        Joint-1725138240      0.16 2024-08-31 21:04:00
2        Joint-1725140280     34.09 2024-08-31 21:04:00
3        Joint-1725140820      9.09 2024-08-31 21:38:00
4        Joint-1725141480     11.24 2024-08-31 21:47:00
..                    ...       ...                 ...
241      Joint-1727202300      2.17 2024-09-24 18:24:00
242      Joint-1727204040     28.14 2024-09-24 18:26:00
243      Joint-1727204220      2.84 2024-09-24 18:55:00
244      Joint-1727207100     47.31 2024-09-24 18:57:00
245      Joint-1727207220      2.25 2024-09-24 19:45:00

[246 rows x 3 columns]

In [23]:
FinalCasingTripBreakdown_df

    Stand Group_Pred_TRIP LABEL_SubActivity  Duration       StartDateTime
0        Joint-1725138180        Connection      0.33 2024-08-31 21:03:00
1        Joint-1725138180            Moving      6.83 2024-08-31 20:49:00
2        Joint-1725138180        Stationary      7.42 2024-08-31 20:55:00
3        Joint-1725138240        Connection      0.08 2024-08-31 21:04:00
4        Joint-1725138240        Stationary      0.08 2024-08-31 21:04:00
..                    ...               ...       ...                 ...
701      Joint-1727207100           Reaming     20.48 2024-09-24 19:21:00
702      Joint-1727207100        Stationary      2.33 2024-09-24 18:57:00
703      Joint-1727207100      Wash Up/Down      0.08 2024-09-24 19:42:00
704      Joint-1727207220        Connection      0.33 2024-09-24 19:47:00
705      Joint-1727207220        Stationary      1.92 2024-09-24 19:45:00

[706 rows x 4 columns]