In [12]:
import pandas as pd 
import plotly.graph_objects as go
from plotly.subplots import make_subplots
ActSum_df = pd.read_csv('../Data/ActSumForTest.csv', index_col=0)
display(ActSum_df)

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,2023-04-09,2023-04-09 00:00:05,2023-04-09 00:11:50,11.83,110.00,14.840,0.0,0.00,0.0,0.00,...,0.00,Connection,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
1,2023-04-09,2023-04-09 00:11:55,2023-04-09 00:13:35,1.75,110.00,14.840,0.0,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
2,2023-04-09,2023-04-09 00:13:40,2023-04-09 00:14:30,0.92,110.00,19.260,0.0,0.00,0.0,0.00,...,0.00,Moving,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
3,2023-04-09,2023-04-09 00:14:35,2023-04-09 00:16:20,1.83,110.00,24.070,0.0,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
4,2023-04-09,2023-04-09 00:16:25,2023-04-09 00:16:55,0.58,110.00,24.950,0.0,0.00,0.0,0.00,...,0.00,Moving,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,2023-04-11,2023-04-11 19:37:50,2023-04-11 19:42:15,4.50,403.62,401.270,0.0,0.00,0.0,4.50,...,0.00,Reaming,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1051,2023-04-11,2023-04-11 19:42:20,2023-04-11 21:18:40,96.42,417.92,410.800,14.3,96.42,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1052,2023-04-11,2023-04-11 21:18:45,2023-04-11 21:31:55,13.25,417.92,409.685,0.0,0.00,0.0,13.17,...,0.00,Reaming,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1053,2023-04-11,2023-04-11 21:32:00,2023-04-11 21:39:35,7.67,417.92,414.910,0.0,0.00,0.0,0.00,...,0.00,Wash Up/Down,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1054,2023-04-11,2023-04-11 21:39:40,2023-04-11 23:59:00,139.42,417.92,386.380,0.0,0.00,0.0,0.00,...,294.84,Connection,DRILLING FORMATION,19.18,54,0,NaN,"26""",NaN,NaN

# Pie Chart Activity Duration

In [13]:
display(ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index())
display(ActSum_df.groupby(['LABEL_SubActivity'])['Duration'].sum().reset_index())
# ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index()

       LABEL_Activity  Duration
0       CEMENTING JOB    122.66
1    DRILL OUT CEMENT     37.16
2  DRILLING FORMATION   2374.79
3               OTHER    174.17
4             TRIP IN   1208.53
5            TRIP OUT    282.25
6      WAIT ON CEMENT    119.08

   LABEL_SubActivity  Duration
0      CEMENTING JOB    122.66
1        Circulation     58.44
2         Connection   1391.30
3        FALSE/Check      6.67
4    Look and define      0.08
5             Moving    133.44
6              OTHER    174.17
7            Reaming    844.25
8    Rotary Drilling    934.56
9     Slide Drilling    197.44
10        Stationary    140.99
11    WAIT ON CEMENT    119.08
12      Wash Up/Down    195.56

In [14]:
SumDuration_Act = (ActSum_df.groupby(['LABEL_Activity'])['Duration'].sum().reset_index())
SumDuration_SubAct = (ActSum_df.groupby(['LABEL_SubActivity'])['Duration'].sum().reset_index())


fig = go.Figure()
fig.add_trace(go.Pie(labels=SumDuration_Act['LABEL_Activity'], hole=0.5,
                     values=SumDuration_Act['Duration'], ))

LegendDict= {
        'legend':{
            'orientation':'h', 
            'xref':"paper",
            'yref':"container",
            'y':-0.3,
            'x':0.5,
            'xanchor':'center', 
            'yanchor':'bottom', 
            }
        }

fig.update_layout(LegendDict)
fig.update_layout(
        height=600,
        width=600,
        margin=dict(l=0, r=0, t=50, b=50),
        title={'text': "Activity Duration", 'x': 0.5, 'xanchor': 'center'},
)
fig.show()

In [15]:
ActSum_df

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,2023-04-09,2023-04-09 00:00:05,2023-04-09 00:11:50,11.83,110.00,14.840,0.0,0.00,0.0,0.00,...,0.00,Connection,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
1,2023-04-09,2023-04-09 00:11:55,2023-04-09 00:13:35,1.75,110.00,14.840,0.0,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
2,2023-04-09,2023-04-09 00:13:40,2023-04-09 00:14:30,0.92,110.00,19.260,0.0,0.00,0.0,0.00,...,0.00,Moving,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
3,2023-04-09,2023-04-09 00:14:35,2023-04-09 00:16:20,1.83,110.00,24.070,0.0,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
4,2023-04-09,2023-04-09 00:16:25,2023-04-09 00:16:55,0.58,110.00,24.950,0.0,0.00,0.0,0.00,...,0.00,Moving,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,2023-04-11,2023-04-11 19:37:50,2023-04-11 19:42:15,4.50,403.62,401.270,0.0,0.00,0.0,4.50,...,0.00,Reaming,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1051,2023-04-11,2023-04-11 19:42:20,2023-04-11 21:18:40,96.42,417.92,410.800,14.3,96.42,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1052,2023-04-11,2023-04-11 21:18:45,2023-04-11 21:31:55,13.25,417.92,409.685,0.0,0.00,0.0,13.17,...,0.00,Reaming,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1053,2023-04-11,2023-04-11 21:32:00,2023-04-11 21:39:35,7.67,417.92,414.910,0.0,0.00,0.0,0.00,...,0.00,Wash Up/Down,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1054,2023-04-11,2023-04-11 21:39:40,2023-04-11 23:59:00,139.42,417.92,386.380,0.0,0.00,0.0,0.00,...,294.84,Connection,DRILLING FORMATION,19.18,54,0,NaN,"26""",NaN,NaN

# Bar Chart Drilling Meterage

In [16]:
import plotly.express as px

# Group by the new 'Date' column and sum the 'DrillingMeterage'
DrilingMeterage_df = ActSum_df.groupby('Date')['DrillingMeterage'].sum().reset_index()
DrilingMeterage_df
DrilingMeterage_df['Date'] = pd.to_datetime(DrilingMeterage_df['Date']).dt.date

# Create a bar chart using Plotly
fig = px.bar(DrilingMeterage_df, x='Date', y='DrillingMeterage',
             labels={'Date': 'Date', 'DrillingMeterage': 'Total Drilling Meterage'},
             )
fig.update_xaxes(
    dtick="D",)
# Show the plot
fig.show()

In [17]:
import pandas as pd
import plotly.graph_objects as go

# Sample DataFrame - replace with your actual data
data = {
    'StartDateTime': ['2024-01-01 08:00', '2024-01-01 10:00', '2024-01-01 14:00'],
    'EndDateTime': ['2024-01-01 10:00', '2024-01-01 14:00', '2024-01-01 16:00'],
    'BitDepth': [100, 200, 150],
    'Activity': ['Drilling', 'Moving', 'Drilling']
}
df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']

In [18]:
df['LABEL_Activity'].unique()

array(['TRIP OUT', 'TRIP IN', 'CEMENTING JOB', 'OTHER', 'WAIT ON CEMENT',
       'DRILL OUT CEMENT', 'DRILLING FORMATION'], dtype=object)

# Depth vs Time

In [19]:
import pandas as pd
import plotly.graph_objects as go
from datetime import timedelta
def round_up_to_next_15_minutes(dt):
    n_minutes = 15 - dt.minute % 15
    return dt + timedelta(minutes=n_minutes) if n_minutes != 15 else dt


df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']
# Convert the 'StartDateTime' and 'EndDateTime' columns to datetime type
df['StartDateTime'] = pd.to_datetime(df['StartDateTime'])
df['EndDateTime'] = pd.to_datetime(df['EndDateTime'])

# Sort the DataFrame by 'StartDateTime'
df = df.sort_values('StartDateTime')
df = df.reset_index(drop=True)

# Create a new Plotly figure
fig = go.Figure()

# Define your own colors for each activity
# activity_colors = {'Drilling': 'blue', 'Moving': 'red', 'Stationary': 'green'}
activity_colors ={'TRIP OUT': '#636EFA',
 'TRIP IN': '#EF553B',
 'CEMENTING JOB': '#00CC96',
 'OTHER': '#AB63FA',
 'WAIT ON CEMENT': '#FFA15A',
 'DRILL OUT CEMENT': '#19D3F3',
 'DRILLING FORMATION': '#FF6692'}
temp_actvity_list = []

# Plot each activity as a separate line segment
for idx, row in df.iterrows():
    if row['Activity'] not in temp_actvity_list: 
        temp_actvity_list.append(row['Activity'])
        legend_show = True
    else:
        legend_show = False
    # Adjust EndDateTime to be on a 15-minute interval if it's not
    # adjusted_end_time = round_up_to_next_15_minutes(row['EndDateTime'])

    # Create a date range with 15-minute intervals
    time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')

    # Ensure that the actual end time is included in the range
    if time_range[-1] != row['EndDateTime']:
        time_range = time_range.union(pd.DatetimeIndex([row['EndDateTime']]))

    # Interpolate BitDepth for each time point (assuming BitDepth is constant for simplicity)
    bit_depth_values = [row['BitDepth']] * len(time_range)
    # Create a date range with 15-minute intervals
    # time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')

    # Interpolate BitDepth for each time point (assuming BitDepth is constant for simplicity)
    bit_depth_values = [row['BitDepth']] * len(time_range)
    
    if idx == 0:
        df_plot = pd.DataFrame({'Datetime': time_range.values.tolist(), 'bit_depth': bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
    else:
        df_plot = pd.DataFrame({'Datetime': [time_range.values.tolist()[0]] + time_range.values.tolist(), 'bit_depth': before_bit_depth + bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
LegendDict= {
        'legend':{
            'orientation':'h', 
            'xref':"paper",
            'yref':"container",
            'y':-0.3,
            'x':0.5,
            'xanchor':'center', 
            'yanchor':'bottom', 
            }
        }

fig.update_layout(LegendDict)

# Set the plot titles and labels
fig.update_layout(
    # title='Time vs Bit Depth with Activity Intervals',
    height=600,
    width=1200,
    margin=dict(l=0, r=50, t=50, b=50),
    xaxis_title='Datetime',
    yaxis_title='Avg. Bit Depth (m)',
    yaxis_autorange='reversed',
    legend_title='Activity'
)

# Show the plot
fig.show()

In [20]:
import pandas as pd
import plotly.graph_objects as go

# Create a DataFrame and rename columns for clarity
df = pd.DataFrame(ActSum_df)
df['Activity'] = df['LABEL_Activity']
df['BitDepth'] = df['Bit_Depth_avg']

# Convert the 'StartDateTime' and 'EndDateTime' columns to datetime type
df['StartDateTime'] = pd.to_datetime(df['StartDateTime'])
df['EndDateTime'] = pd.to_datetime(df['EndDateTime'])

# Sort the DataFrame by 'StartDateTime' for chronological plotting
df = df.sort_values('StartDateTime').reset_index(drop=True)

# Create a new Plotly figure
fig = go.Figure()

# Define custom colors for each activity type
activity_colors = {'TRIP IN': 'red',
 'TRIP OUT': 'orange',
 'WIPER TRIP': '#00CC96',
 'DRILLING FORMATION': '#AB63FA',
 'CIRCULATE HOLE CLEANING': '#FFA15A',
 'CONNECTION': '#19D3F3',
 'DRILL OUT CEMENT': '#FF6692',
 'CEMENTING JOB': '#B6E880',
 'LAY DOWN BHA': '#FF97FF',
 'MAKE UP BHA': '#FECB52',
 'NPT': '#4D8BFA',
 'N/D BOP': '#F5663B',
 'N/U BOP': '#00D596',
 'RUNNING CASING IN': '#9B63FA',
 'STATIONARY': '#FFB85A',
 'STUCK PIPE': '#39D4F3',
 'WAIT ON CEMENT': '#FF3388',
 'RIG REPAIR': '#C6F980',
 'N/A': '#FFC0FF',
 'OTHER': '#FED752'}

# Temporary list to track activities for legend display
temp_activity_list = []

# Iterate over each row in the DataFrame to plot the activities
for idx, row in df.iterrows():
    # Show legend only for the first instance of each activity
    legend_show = row['Activity'] not in temp_activity_list
    if legend_show:
        temp_activity_list.append(row['Activity'])

    # Create a date range with 15-minute intervals, ensuring to include the end time
    time_range = pd.date_range(start=row['StartDateTime'], end=row['EndDateTime'], freq='15T')
    if time_range[-1] != row['EndDateTime']:
        time_range = time_range.union(pd.DatetimeIndex([row['EndDateTime']]))

    # Assume BitDepth is constant for simplicity
    bit_depth_values = [row['BitDepth']] * len(time_range)

    # Create and add a trace to the figure for each activity
    if idx == 0:
        df_plot = pd.DataFrame({'Datetime': time_range.values.tolist(), 'bit_depth': bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]
    else:
        df_plot = pd.DataFrame({'Datetime': [time_range.values.tolist()[0]] + time_range.values.tolist(), 'bit_depth': before_bit_depth + bit_depth_values})
        df_plot['Datetime'] = pd.to_datetime(df_plot['Datetime'])
        fig.add_trace(
            go.Scatter(
                x=df_plot['Datetime'],
                y=df_plot['bit_depth'],
                mode='lines',
                name=row['Activity'],
                line=dict(color=activity_colors[row['Activity']], width=4),
                legendgroup=row['Activity'],
                showlegend=legend_show  # Show legend only for the first instance of each activity
            )
        )
        before_bit_depth = [bit_depth_values[-1]]

# Update layout for the legend
legend_layout = {
    'orientation': 'h',
    'xref': "paper",
    'yref': "container",
    'y': -0.3,
    'x': 0.5,
    'xanchor': 'center',
    'yanchor': 'bottom'
}
fig.update_layout(legend=legend_layout)

# Set the plot titles and labels
fig.update_layout(
    height=600,
    width=1200,
    margin=dict(l=0, r=50, t=50, b=50),
    xaxis_title='Datetime',
    yaxis_title='Avg. Bit Depth (m)',
    yaxis_autorange='reversed',  # Reverse the y-axis to show deeper depths at the top
    legend_title='Activity'
)

# Show the plot
fig.show()

# ROP Stand vs On Bottom

In [21]:
import plotly.graph_objects as go
ROP_df = ActSum_df.copy()
ROP_df['StartDateTime'] = pd.to_datetime(ROP_df['StartDateTime'])
ROP_df['EndDateTime'] = pd.to_datetime(ROP_df['EndDateTime'])

# Calculate MidDateTime as the average of StartDateTime and EndDateTime
ROP_df['MidDateTime'] = ROP_df['StartDateTime'] + (ROP_df['EndDateTime'] - ROP_df['StartDateTime']) / 2

idx_logic = (ROP_df['LABEL_Activity'].isin(["DRILLING FORMATION", 'CIRCULATE HOLE CLEANING','DRILL OUT CEMENT',])) & (ROP_df['LABEL_SubActivity'] == 'Connection')


ROP_df = ROP_df[idx_logic]

ROP_df['ROP_OnBottom'] = ROP_df['DrillingMeteragePerStand'] / (ROP_df['OnBottomDurationPerStand']/60) 
ROP_df['ROP_Stand'] = ROP_df['DrillingMeteragePerStand'] / (ROP_df['StandDuration']/60)
display(ROP_df[['MidDateTime', 'LABEL_SubActivity', 'LABEL_Activity', 'DrillingMeteragePerStand', 'OnBottomDurationPerStand', 'StandDuration', 'ROP_OnBottom', 'ROP_Stand']])
# ROP stand m/hr 



# Assuming your DataFrame is named df and contains columns 'ROP_OnBottom', 'ROP_Stand', and 'DateTime'
# First, convert your 'DateTime' column to a datetime type if it's not already
df = pd.DataFrame(ROP_df)
# df['DateTime'] = pd.to_datetime(df['DateTime'])

# Create a new Plotly figure
fig = go.Figure()
bar_width = 60*60*60*10
# Add ROP_OnBottom as one set of bars
fig.add_trace(go.Bar(
    x=df['MidDateTime'],
    y=df['ROP_OnBottom'],
    name='ROP On Bottom',
    marker_color='blue',  # You can choose a color
    #  width=bar_width 
))

# Add ROP_Stand as another set of bars
fig.add_trace(go.Bar(
    x=df['MidDateTime'],
    y=df['ROP_Stand'],
    name='ROP Stand',
    marker_color='red',  # You can choose a different color
    #  width=bar_width 
))

# Update the layout
fig.update_layout(
    barmode='group',  # This will group the bars side by side at each x-value (datetime)
        bargap=0, # gap between bars of adjacent location coordinates.
    bargroupgap=0, # gap between bars of the same location coordinate.
    # title='ROP On Bottom vs ROP Stand Over Time',
    xaxis_title='Datetime',
    yaxis_title='ROP(m/hr)',
    xaxis=dict(type='date')  # Ensuring x-axis is treated as date
)
fig.show()

,MidDateTime,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,OnBottomDurationPerStand,StandDuration,ROP_OnBottom,ROP_Stand
314,2023-04-09 23:53:02.500,Connection,DRILLING FORMATION,2.09,20.99,63.41,5.974273,1.977606
340,2023-04-10 03:05:10.000,Connection,DRILLING FORMATION,17.58,143.88,185.09,7.331109,5.698849
425,2023-04-10 05:51:12.500,Connection,DRILLING FORMATION,0.00,0.00,0.00,NaN,NaN
431,2023-04-10 07:10:22.500,Connection,DRILLING FORMATION,8.20,49.50,85.09,9.939394,5.782113
451,2023-04-10 08:40:32.500,Connection,DRILLING FORMATION,16.58,6.18,97.75,160.970874,10.176982
463,2023-04-10 10:38:50.000,Connection,DRILLING FORMATION,18.08,0.34,103.90,3190.588235,10.440808
507,2023-04-10 13:34:27.500,Connection,DRILLING FORMATION,15.10,44.33,102.92,20.437627,8.802954
538,2023-04-10 15:05:05.000,Connection,DRILLING FORMATION,17.09,8.86,85.68,115.733634,11.967787
545,2023-04-10 16:42:05.000,Connection,DRILLING FORMATION,18.07,47.83,101.64,22.667782,10.667060
554,2023-04-10 17:45:40.000,Connection,DRILLING FORMATION,18.45,49.33,51.58,22.440705,21.461807
558,2023-04-10 18:30:30.000,Connection,DRILLING FORMATION,0.00,2.00,56.92,0.000000,0.000000
576,2023-04-10 19:01:15.000,Connection,DRILLING FORMATION,6.18,6.60,18.85,56.181818,19.671088
605,2023-04-10 19:57:35.000,Connection,DRILLING FORMATION,10.90,7.27,65.12,89.958735,10.042998
639,2023-04-10 21:29:10.000,Connection,DRILLING FORMATION,8.68,47.26,85.84,11.019890,6.067102
662,2023-04-10 22:50:05.000,Connection,DRILLING FORMATION,8.82,53.65,88.32,9.863933,5.991848
689,2023-04-11 02:13:22.500,Connection,DRILLING FORMATION,19.09,122.59,203.03,9.343340,5.641531
727,2023-04-11 04:26:00.000,Connection,DRILLING FORMATION,17.84,105.59,122.57,10.137324,8.732969
728,2023-04-11 04:35:05.000,Connection,DRILLING FORMATION,0.00,0.00,0.00,NaN,NaN
760,2023-04-11 08:52:10.000,Connection,DRILLING FORMATION,18.57,108.25,275.92,10.292841,4.038127
1024,2023-04-11 15:15:30.000,Connection,DRILLING FORMATION,3.09,0.00,49.25,inf,3.764467
1048,2023-04-11 18:52:25.000,Connection,DRILLING FORMATION,19.35,133.75,212.66,8.680374,5.459419
1054,2023-04-11 22:49:20.000,Connection,DRILLING FORMATION,19.18,130.00,294.84,8.852308,3.903134

# Stand Time Break down

In [23]:
StandTime_df = ActSum_df.copy()
display(StandTime_df.columns)
display(StandTime_df)

Index(['Date', 'StartDateTime', 'EndDateTime', 'Duration', 'Hole_Depth_max',
       'Bit_Depth_avg', 'DrillingMeterage', 'RotateDrillingDuration',
       'SlideDrillingDuration', 'ReamingDuration', 'ConnectionDuration',
       'LABEL_ConnectionActivity', 'OnBottomDurationPerStand', 'StandDuration',
       'LABEL_SubActivity', 'LABEL_Activity', 'DrillingMeteragePerStand',
       'InSlip_Treshold', 'stand_on_bottom', 'PIC', 'Section', 'Remarks',
       'Stand Group_Pred'],
      dtype='object')

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,2023-04-09,2023-04-09 00:00:05,2023-04-09 00:11:50,11.83,110.00,14.840,0.0,0.00,0.0,0.00,...,0.00,Connection,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
1,2023-04-09,2023-04-09 00:11:55,2023-04-09 00:13:35,1.75,110.00,14.840,0.0,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
2,2023-04-09,2023-04-09 00:13:40,2023-04-09 00:14:30,0.92,110.00,19.260,0.0,0.00,0.0,0.00,...,0.00,Moving,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
3,2023-04-09,2023-04-09 00:14:35,2023-04-09 00:16:20,1.83,110.00,24.070,0.0,0.00,0.0,0.00,...,0.00,Stationary,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
4,2023-04-09,2023-04-09 00:16:25,2023-04-09 00:16:55,0.58,110.00,24.950,0.0,0.00,0.0,0.00,...,0.00,Moving,TRIP OUT,0.00,54,0,NaN,"26""",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,2023-04-11,2023-04-11 19:37:50,2023-04-11 19:42:15,4.50,403.62,401.270,0.0,0.00,0.0,4.50,...,0.00,Reaming,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1051,2023-04-11,2023-04-11 19:42:20,2023-04-11 21:18:40,96.42,417.92,410.800,14.3,96.42,0.0,0.00,...,0.00,Rotary Drilling,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1052,2023-04-11,2023-04-11 21:18:45,2023-04-11 21:31:55,13.25,417.92,409.685,0.0,0.00,0.0,13.17,...,0.00,Reaming,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1053,2023-04-11,2023-04-11 21:32:00,2023-04-11 21:39:35,7.67,417.92,414.910,0.0,0.00,0.0,0.00,...,0.00,Wash Up/Down,DRILLING FORMATION,0.00,54,0,NaN,"26""",NaN,Drilling Stand-20
1054,2023-04-11,2023-04-11 21:39:40,2023-04-11 23:59:00,139.42,417.92,386.380,0.0,0.00,0.0,0.00,...,294.84,Connection,DRILLING FORMATION,19.18,54,0,NaN,"26""",NaN,NaN

In [25]:
grouped_df = StandTime_df.groupby('Stand Group_Pred').agg({
    'RotateDrillingDuration': 'sum',
    'SlideDrillingDuration': 'sum',
    'ReamingDuration': 'sum',
    'ConnectionDuration': 'sum',
    'EndDateTime': 'max'
})

# Resetting index to make 'Stand Group_Pred' a column again
grouped_df = grouped_df.reset_index()
# grouped_df = StandTime_df.groupby('Stand Group_Pred')[[ 'RotateDrillingDuration', 'SlideDrillingDuration', 'ReamingDuration', 'ConnectionDuration']].sum()

# Resetting index to make 'Stand Group_Pred' a column again
# grouped_df = grouped_df.reset_index()
grouped_df

,Stand Group_Pred,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,ConnectionDuration,EndDateTime
0,Drilling Stand-1,20.91,0.08,18.25,0.0,2023-04-09 23:42:10
1,Drilling Stand-10,2.00,0.00,23.83,0.0,2023-04-10 18:18:20
2,Drilling Stand-11,6.60,0.00,11.83,0.0,2023-04-10 19:01:00
3,Drilling Stand-12,7.27,0.00,39.18,0.0,2023-04-10 19:48:35
4,Drilling Stand-13,25.76,21.50,12.07,0.0,2023-04-10 21:25:55
5,Drilling Stand-14,53.57,0.08,12.83,0.0,2023-04-10 22:39:25
6,Drilling Stand-15,34.00,88.59,26.59,0.0,2023-04-11 02:03:00
7,Drilling Stand-16,105.59,0.00,11.99,0.0,2023-04-11 04:25:40
8,Drilling Stand-17,24.75,83.50,96.91,0.0,2023-04-11 08:24:30
9,Drilling Stand-18,0.00,0.00,17.17,0.0,2023-04-11 14:59:25
10,Drilling Stand-19,133.67,0.08,50.25,0.0,2023-04-11 18:40:35
11,Drilling Stand-2,143.88,0.00,14.75,0.0,2023-04-10 03:01:15
12,Drilling Stand-20,130.00,0.00,17.67,0.0,2023-04-11 21:39:35
13,Drilling Stand-3,49.50,0.00,14.25,0.0,2023-04-10 07:01:00
14,Drilling Stand-4,6.18,0.00,54.75,0.0,2023-04-10 08:23:35
15,Drilling Stand-5,0.34,0.00,90.08,0.0,2023-04-10 10:36:15
16,Drilling Stand-6,44.33,0.00,25.25,0.0,2023-04-10 13:22:05
17,Drilling Stand-7,5.25,3.61,36.25,0.0,2023-04-10 14:57:40
18,Drilling Stand-8,47.83,0.00,22.41,0.0,2023-04-10 16:30:00
19,Drilling Stand-9,49.33,0.00,2.17,0.0,2023-04-10 17:45:35

In [29]:
# Create a new Plotly figure
fig = go.Figure()
bar_width = 60*60*60*10
for DurationCols in [ 'Rotate Drilling', 'Slide Drilling', 'Reaming', 'Connection']:
    # DurationCols = DurationCols.replace(' ', '').replace('Duration', '')
    
    fig.add_trace(go.Bar(
        x=grouped_df['EndDateTime'],
        y=grouped_df[DurationCols.replace(' ', '') + "Duration"],
        name=DurationCols,
        # marker_color='blue',  # You can choose a color
        #  width=bar_width 
    ))


# Update the layout
fig.update_layout(
    barmode='stack',  # This will group the bars side by side at each x-value (datetime)
    xaxis_title='Datetime',
    yaxis_title='Duration',
    xaxis=dict(type='date')  # Ensuring x-axis is treated as date
)
fig.show()