In [1]:
import os
import sys
# Get the current working directory
current_directory = os.getcwd()

# Get the current working directory
current_directory = os.getcwd()

# Get the parent directory
parent_directory = os.path.abspath(os.path.join(current_directory, os.pardir))

# Add the parent directory to sys.path
sys.path.append(parent_directory)


# Change the current working directory
os.chdir(parent_directory)

# Verify the change
print("Current Directory:", os.getcwd())

Current Directory: c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App_v3

In [16]:
import pandas as pd 
import numpy as np 
import requests
import json
import sys

from PDU_Func import IO_Data, Activity
from Page import Override
import datetime
from importlib import reload

reload(IO_Data)

2024-08-11 19:16:31.247 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [17]:
# IO_Data.getAvailableCompanyDF(UserAuthDict)
UserAuthDict = {'data':{'user_cid':'1'}}
# IO_Data.getAvailableWellDF('PETROCHINA INTERNATIONAL JABUNG LTD', UserAuthDict)
WellInfoDict = IO_Data.getWellInfoDict(UserAuthDict, 'PETROCHINA INTERNATIONAL JABUNG LTD', 'SBD-24', )
WellInfoDict

{'cid': 5,
 'wid': 316,
 'WellName': 'SBD-24',
 'RigName': 31    Rig#26
 Name: rig_name, dtype: string,
 'ActiveDate': '2024-07-26',
 'EndDate': '2024-08-31'}

In [18]:
import datetime as datetime_module
reload(Override)
UserDateRange = {
      "StartDate":  datetime_module.date(2024, 7, 28),
      "StartTime":  datetime_module.time(12, 00),
      "EndDate": datetime_module.date(2024, 7, 28),
      "EndTime": datetime_module.time(23, 00)
    }
# 2024-07-28 12:00:00	
# 2024-07-28 23:00:00
UserDateRange_new = Override.RedefinedUserDateRange(WellInfoDict, UserDateRange)

2024-08-11 19:16:35.123 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-10 10:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-10 09:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-10 07:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-10 04:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-10 00:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-09 19:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-09 13:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-09 06:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-08 22:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-08 13:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-08 03:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-07 16:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-07 04:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-06 15:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-06 01:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-05 10:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-04 18:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-04 01:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-03 07:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-02 12:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-04-01 16:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-03-31 19:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2003-03-30 21:51:00",
    "end": "2024-07-28 12:00:00"
}
http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2024-07-28 23:00:00",
    "end": "2300-04-10 11:09:00"
}

In [20]:
IO_Data.DomeGetActivitySummaryData(WellInfoDict, UserDateRange_new).head(10)

http://khansadev.xyz/dome_api/rtdc/ActivitySummary/get_data
{
    "wid": 316,
    "start": "2024-07-28 12:00:00",
    "end": "2024-07-28 23:02:00"
}

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,StandDuration,LABEL_SubActivity,LABEL_Activity,DrillingMeteragePerStand,InSlip_Treshold,stand_on_bottom,PIC,Section,Remarks,Stand Group_Pred
0,2024-07-28,2024-07-28 13:00:05,2024-07-28 21:12:55,492.92,188.15,51.32,0.00,0.00,0.00,0.00,...,0.00,OTHER,OTHER,0.0,19.00,0.00,,"26""",,
1,2024-07-28,2024-07-28 21:13:00,2024-07-28 21:20:20,7.42,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Stationary,TRIP IN,0.0,19.00,0.00,,"26""",,
2,2024-07-28,2024-07-28 21:20:25,2024-07-28 21:20:25,0.08,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Moving,TRIP IN,0.0,19.00,0.00,,"26""",,
3,2024-07-28,2024-07-28 21:20:35,2024-07-28 21:20:35,0.08,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Moving,TRIP IN,0.0,19.00,0.00,,"26""",,
4,2024-07-28,2024-07-28 21:20:45,2024-07-28 21:20:45,0.08,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Moving,TRIP IN,0.0,19.00,0.00,,"26""",,
5,2024-07-28,2024-07-28 21:20:55,2024-07-28 21:20:55,0.08,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Moving,TRIP IN,0.0,19.00,0.00,,"26""",,
6,2024-07-28,2024-07-28 21:21:05,2024-07-28 21:21:05,0.08,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Moving,TRIP IN,0.0,19.00,0.00,,"26""",,
7,2024-07-28,2024-07-28 21:21:15,2024-07-28 21:21:15,0.08,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Connection,TRIP IN,0.0,19.00,0.00,,"26""",,
8,2024-07-28,2024-07-28 21:21:20,2024-07-28 21:22:50,1.58,188.15,0.00,0.00,0.00,0.00,0.00,...,0.00,Stationary,TRIP IN,0.0,19.00,0.00,,"26""",,
9,2024-07-28,2024-07-28 21:22:55,2024-07-28 21:23:15,0.42,188.15,2.47,0.00,0.00,0.00,0.00,...,0.00,Moving,TRIP IN,0.0,19.00,0.00,,"26""",,

In [21]:
SectionParams_DF = IO_Data.DomeSectionParamsTable_Get(WellInfoDict)
RTSensor_DF = IO_Data.DomeGetRealtimeSensorData(WellInfoDict,
                                                    UserDateRange_new, 
                                                    hours=0.5, 
                                                    show_progress=False, 
                                                    runOnStreamlit=False,
                                                    )


RigActivity_DF = (IO_Data.getRigActivity(WellInfoDict, 
                start_date="2000-01-01 00:00:01", 
                end_date="2100-01-01 00:00:01"))
RTSensor_DF = Activity.addRigActivityLabel (
                    RTSensor_DF, 
                    Activity.translateRigActivity2Activity(RigActivity_DF)
                    )
RTSensor_DF = Activity.addSectionParams (
                    RTSensor_DF, 
                    SectionParams_DF
                    )
RTSensor_DF = Activity.predictSubActivityLabel(
                    RTSensor_DF, 
                    TripActivityList='default', 
                    DrillActivityList='default', 
                    OverrideActivityList='default')
Override_df = IO_Data.DomeOverrideActivity_Get(WellInfoDict)
RTSensor_DF = Activity.Override(RTSensor_DF, Override_df)
ActivitySummary_DF= Activity.groupActivity(RTSensor_DF , DrillActivityList='default')
ActivitySummary_DF = Activity.cleanFalseSensor(ActivitySummary_DF)
ActivitySummary_DF = Activity.getStandLabel(ActivitySummary_DF)

test==========================================================
http://pdumitradome.id:8000/section-params-table/get/
{
    "wid": 316,
    "cid": 5
}
test==========================================================
<Response [200]>
{'cid': 5, 'wid': 316, 'WellName': 'SBD-24', 'RigName': 31    Rig#26
Name: rig_name, dtype: string, 'ActiveDate': '2024-07-26', 'EndDate': '2024-08-31'}
 Download Realtime Sensor Data, 0.0 % Complete
(Timestamp('2024-07-28 12:00:00'), Timestamp('2024-07-28 12:30:00'))
200
 Download Realtime Sensor Data, 4.0 % Complete
(Timestamp('2024-07-28 12:30:00'), Timestamp('2024-07-28 13:00:00'))
200
 Download Realtime Sensor Data, 8.0 % Complete
(Timestamp('2024-07-28 13:00:00'), Timestamp('2024-07-28 13:30:00'))
200
 Download Realtime Sensor Data, 12.0 % Complete
(Timestamp('2024-07-28 13:30:00'), Timestamp('2024-07-28 14:00:00'))
200
 Download Realtime Sensor Data, 17.0 % Complete
(Timestamp('2024-07-28 14:00:00'), Timestamp('2024-07-28 14:30:00'))
200
 Download Realtime Sensor Data, 21.0 % Complete
(Timestamp('2024-07-28 14:30:00'), Timestamp('2024-07-28 15:00:00'))
200
 Download Realtime Sensor Data, 25.0 % Complete
(Timestamp('2024-07-28 15:00:00'), Timestamp('2024-07-28 15:30:00'))
200
 Download Realtime Sensor Data, 28.999999999999996 % Complete
(Timestamp('2024-07-28 15:30:00'), Timestamp('2024-07-28 16:00:00'))
200
 Download Realtime Sensor Data, 33.0 % Complete
(Timestamp('2024-07-28 16:00:00'), Timestamp('2024-07-28 16:30:00'))
200
 Download Realtime Sensor Data, 38.0 % Complete
(Timestamp('2024-07-28 16:30:00'), Timestamp('2024-07-28 17:00:00'))
200
 Download Realtime Sensor Data, 42.0 % Complete
(Timestamp('2024-07-28 17:00:00'), Timestamp('2024-07-28 17:30:00'))
200
 Download Realtime Sensor Data, 46.0 % Complete
(Timestamp('2024-07-28 17:30:00'), Timestamp('2024-07-28 18:00:00'))
200
 Download Realtime Sensor Data, 50.0 % Complete
(Timestamp('2024-07-28 18:00:00'), Timestamp('2024-07-28 18:30:00'))
200
 Download Realtime Sensor Data, 54.0 % Complete
(Timestamp('2024-07-28 18:30:00'), Timestamp('2024-07-28 19:00:00'))
200
 Download Realtime Sensor Data, 57.99999999999999 % Complete
(Timestamp('2024-07-28 19:00:00'), Timestamp('2024-07-28 19:30:00'))
200
 Download Realtime Sensor Data, 62.0 % Complete
(Timestamp('2024-07-28 19:30:00'), Timestamp('2024-07-28 20:00:00'))
200
 Download Realtime Sensor Data, 67.0 % Complete
(Timestamp('2024-07-28 20:00:00'), Timestamp('2024-07-28 20:30:00'))
200
 Download Realtime Sensor Data, 71.0 % Complete
(Timestamp('2024-07-28 20:30:00'), Timestamp('2024-07-28 21:00:00'))
200
 Download Realtime Sensor Data, 75.0 % Complete
(Timestamp('2024-07-28 21:00:00'), Timestamp('2024-07-28 21:30:00'))
200
 Download Realtime Sensor Data, 79.0 % Complete
(Timestamp('2024-07-28 21:30:00'), Timestamp('2024-07-28 22:00:00'))
200
 Download Realtime Sensor Data, 83.0 % Complete
(Timestamp('2024-07-28 22:00:00'), Timestamp('2024-07-28 22:30:00'))
200
 Download Realtime Sensor Data, 88.0 % Complete
(Timestamp('2024-07-28 22:30:00'), Timestamp('2024-07-28 23:00:00'))
200
 Download Realtime Sensor Data, 92.0 % Complete
(Timestamp('2024-07-28 23:00:00'), Timestamp('2024-07-28 23:30:00'))
200
 Download Realtime Sensor Data, 96.0 % Complete
(Timestamp('2024-07-28 23:30:00'), Timestamp('2024-07-29 00:00:00'))
200

c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App_v3\PDU_Func\IO_Data.py:270: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw.loc[:, 'dt_relative'] = (realtimeraw['dt'] - realtimeraw['dt'].min()).dt.total_seconds()
c:\Users\irsya\Documents\Jiunx_Files\PROJECT\2021-PDU\01_PDU_python\Streamlit_App_v3\PDU_Func\IO_Data.py:293: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  realtimeraw[list_cols] = realtimeraw[list_cols].astype(float)

http://pdumitradome.id:8000/override-activity-table/get/
{
    "wid": 316,
    "cid": 5
}
   index  wid       StartDateTime         EndDateTime LABEL_ACTIVITY  \
0      0  316 2024-07-28 12:00:00 2024-07-28 23:00:00          OTHER

  LABEL_SUBACTIVITY  PIC
0             OTHER  MIH

In [22]:
ActivitySummary_DF

,Date,StartDateTime,EndDateTime,Duration,Hole_Depth_max,Bit_Depth_avg,DrillingMeterage,RotateDrillingDuration,SlideDrillingDuration,ReamingDuration,...,LABEL_SubActivity,LABEL_Activity,LABEL_All,LABEL_ConnectionActivity,InSlip_Treshold,Section,DrillingMeteragePerStand,StandDuration,OnBottomDurationPerStand,Stand Group_Pred
0,2024-07-28,2024-07-28 12:20:15,2024-07-28 22:59:55,639.75,188.15,60.52,0.0,0.0,0.0,0.0,...,OTHER,OTHER,"26""--OTHER--OTHER",,19.0,"26""",0.0,0.0,0.0,
1,2024-07-28,2024-07-28 23:00:00,2024-07-28 23:01:50,1.92,188.15,67.90,0.0,0.0,0.0,0.0,...,Stationary,TRIP IN,"26""--Stationary--TRIP IN",,19.0,"26""",0.0,0.0,0.0,
2,2024-07-28,2024-07-28 23:01:55,2024-07-28 23:02:00,0.17,188.15,68.68,0.0,0.0,0.0,0.0,...,Moving,TRIP IN,"26""--Moving--TRIP IN",,19.0,"26""",0.0,0.0,0.0,