In [1]:
import sys
from pathlib import Path
import pandas as pd 
import numpy as np 

# Get current working directory in Jupyter
notebook_dir = Path().resolve()
parent_dir = notebook_dir.parent

# Add parent directory to sys.path
sys.path.append(str(parent_dir))

In [2]:
from PDU_Func import Activity, Authentification, IO_Data
from importlib import reload
reload(Activity)
reload(Authentification)
reload(IO_Data)

2025-05-12 17:09:39.836 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-05-12 17:09:39.840 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-05-12 17:09:39.844 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-05-12 17:09:39.844 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [3]:
# DataParams_dict = {
#     "wid": 420,
#     "cid": 99
# }


StartDateTime = "2025-04-14 00:00:00"
EndDateTime = "2025-04-14 11:30:00"


# RTSensor_DF = IO_Data.DomeGetRealtimeSensorData(WellInfoDict,
#                                                 UserDateRange, 
#                                                 hours=0.5, 
#                                                 show_progress=False, 
#                                                 runOnStreamlit=True,
#                                                 )

Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 00:00:00', 'end': '2025-04-14 00:30:00'}
200

,dt,wid,sid,recid,seqid,date,time,actcode,blockpos,bitdepth,...,spare_5,spare_6,spare_7,spare_8,spare_9,spare_10,label,posisiy,tipenote,idnote
0,2025-04-14 00:00:01,420,0,1,3937,2025-04-14,00:00:01,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
1,2025-04-14 00:00:06,420,0,1,3938,2025-04-14,00:00:06,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
2,2025-04-14 00:00:11,420,0,1,3939,2025-04-14,00:00:11,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
3,2025-04-14 00:00:16,420,0,1,3940,2025-04-14,00:00:16,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
4,2025-04-14 00:00:21,420,0,1,3941,2025-04-14,00:00:21,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2025-04-14 00:29:36,420,0,1,4292,2025-04-14,00:29:36,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
356,2025-04-14 00:29:41,420,0,1,4293,2025-04-14,00:29:41,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
357,2025-04-14 00:29:46,420,0,1,4294,2025-04-14,00:29:46,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
358,2025-04-14 00:29:51,420,0,1,4295,2025-04-14,00:29:51,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None
359,2025-04-14 00:29:56,420,0,1,4296,2025-04-14,00:29:56,21,33.22,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,None,None,None,None

In [4]:
StartDateTime_list = [
 '2025-04-14 00:00:00',
 '2025-04-14 00:30:00',
 '2025-04-14 01:00:00',
 '2025-04-14 01:30:00',
 '2025-04-14 02:00:00',
 '2025-04-14 02:30:00',
 '2025-04-14 03:00:00',
 '2025-04-14 03:30:00',
 '2025-04-14 04:00:00',
 '2025-04-14 04:30:00',
 '2025-04-14 05:00:00',
 '2025-04-14 05:30:00',
 '2025-04-14 06:00:00',
 '2025-04-14 06:30:00',
 '2025-04-14 07:00:00',
 '2025-04-14 07:30:00',
 '2025-04-14 08:00:00',
 '2025-04-14 08:30:00',
 '2025-04-14 09:00:00',
 '2025-04-14 09:30:00',
 '2025-04-14 10:00:00',
 '2025-04-14 10:30:00',
 '2025-04-14 11:00:00'
]
EndDateTime_list = [
 '2025-04-14 00:30:00',
 '2025-04-14 01:00:00',
 '2025-04-14 01:30:00',
 '2025-04-14 02:00:00',
 '2025-04-14 02:30:00',
 '2025-04-14 03:00:00',
 '2025-04-14 03:30:00',
 '2025-04-14 04:00:00',
 '2025-04-14 04:30:00',
 '2025-04-14 05:00:00',
 '2025-04-14 05:30:00',
 '2025-04-14 06:00:00',
 '2025-04-14 06:30:00',
 '2025-04-14 07:00:00',
 '2025-04-14 07:30:00',
 '2025-04-14 08:00:00',
 '2025-04-14 08:30:00',
 '2025-04-14 09:00:00',
 '2025-04-14 09:30:00',
 '2025-04-14 10:00:00',
 '2025-04-14 10:30:00',
 '2025-04-14 11:00:00',
 '2025-04-14 11:30:00',
]
Output_list = []
for StartDateTime,EndDateTime in zip(StartDateTime_list, EndDateTime_list):
    DataParams_dict ={
    "wid" : 420,
    "start" : str(StartDateTime),
    "end" : str(EndDateTime),
    }
    Output = IO_Data.DomeGetRealtimeSensorDataChunk(DataParams_dict)
    Output_list.append(Output)

Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 00:00:00', 'end': '2025-04-14 00:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 00:30:00', 'end': '2025-04-14 01:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 01:00:00', 'end': '2025-04-14 01:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 01:30:00', 'end': '2025-04-14 02:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 02:00:00', 'end': '2025-04-14 02:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 02:30:00', 'end': '2025-04-14 03:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 03:00:00', 'end': '2025-04-14 03:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 03:30:00', 'end': '2025-04-14 04:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 04:00:00', 'end': '2025-04-14 04:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 04:30:00', 'end': '2025-04-14 05:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 05:00:00', 'end': '2025-04-14 05:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 05:30:00', 'end': '2025-04-14 06:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 06:00:00', 'end': '2025-04-14 06:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 06:30:00', 'end': '2025-04-14 07:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 07:00:00', 'end': '2025-04-14 07:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 07:30:00', 'end': '2025-04-14 08:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 08:00:00', 'end': '2025-04-14 08:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 08:30:00', 'end': '2025-04-14 09:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 09:00:00', 'end': '2025-04-14 09:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 09:30:00', 'end': '2025-04-14 10:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 10:00:00', 'end': '2025-04-14 10:30:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 10:30:00', 'end': '2025-04-14 11:00:00'}
200
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 11:00:00', 'end': '2025-04-14 11:30:00'}
200

In [5]:
StartDateTime ='2025-04-14 00:00:00'
EndDateTime = '2025-04-14 12:00:00'
DataParams_dict ={
"wid" : 420,
"start" : str(StartDateTime),
"end" : str(EndDateTime),
}


Output = IO_Data.DomeGetRealtimeSensorDataChunk(DataParams_dict)

Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-14 00:30:00', 'end': '2025-04-14 11:30:00'}
200

### Caching Test

In [3]:
SelectComp = 'EMP-GANDEWA'
SelectWell = 'BTG-INF.01'
UserAuthDict = {'data':{'user_cid':'1'}}
WellInfoDict = IO_Data.getWellInfoDict(UserAuthDict, SelectComp, SelectWell)
WellInfoDict

{'cid': 99,
 'wid': 420,
 'WellName': 'BTG-INF.01',
 'RigName': 0    -
 Name: rig_name, dtype: string,
 'ActiveDate': '2025-03-17',
 'EndDate': '2025-04-26'}

In [4]:
from datetime import datetime
UserDateRange = {
    "StartDate": datetime(2025, 4, 7).date(),
    "StartTime": datetime(2025, 4, 7, 0, 0).time(),
    "EndDate": datetime(2025, 4, 10).date(),
    "EndTime": datetime(2025, 4, 10, 23, 59, 59).time(),
}
# UserDateRange = {
#     "StartDate": UserDateRange['StartDate'].strftime('%Y-%m-%d'),
#     "StartTime": UserDateRange['StartTime'].strftime('%H:%M:%S'),
#     "EndDate": UserDateRange['EndDate'].strftime('%Y-%m-%d'),
#     "EndTime": UserDateRange['EndTime'].strftime('%H:%M:%S'),
# }
# UserDateRange

OutputRealtime = IO_Data.DomeGetRealtimeSensorData(WellInfoDict,
                                                      UserDateRange, 
                                                      hours=0.5, 
                                                      show_progress=False, 
                                                      runOnStreamlit=False,
                                                    #   _container=RealtimeLoadingContainer
                                                      )
OutputRealtime

{'cid': 99, 'wid': 420, 'WellName': 'BTG-INF.01', 'RigName': 0    -
Name: rig_name, dtype: string, 'ActiveDate': '2025-03-17', 'EndDate': '2025-04-26'}
 Download Realtime Sensor Data, 0.0 % Complete
(Timestamp('2025-04-07 00:00:00'), Timestamp('2025-04-07 00:30:00'))
Request Realtime on :http://pdumitradome.id/dome_api/rtdc/get_data
{'wid': 420, 'start': '2025-04-07 00:00:00', 'end': '2025-04-07 00:30:00'}

:

In [4]:
WellInfoDict

{'cid': 99,
 'wid': 420,
 'WellName': 'BTG-INF.01',
 'RigName': 0    -
 Name: rig_name, dtype: string,
 'ActiveDate': '2025-03-17',
 'EndDate': '2025-04-26'}

In [5]:
import os
dir_path = f"../Data/RealtimeCache/wid_{WellInfoDict['wid']}"

if not os.path.exists(dir_path):
    os.makedirs(dir_path)

In [ ]:
Date_list = OutputRealtime['date'].astype(str).unique()


for date in Date_list:
    # OutputRealtime[OutputRealtime['date'].astype(str) == date].to_feather(dir_path + f"/{WellInfoDict['wid']}_{date}.feather")
    OutputRealtime[OutputRealtime['date'].astype(str) == date].to_parquet(dir_path + f"/{WellInfoDict['wid']}_{date}.parquet", compression='gzip')

In [17]:
Date_list = [
    '2025-04-07',
    '2025-04-08',
    '2025-04-09',
    '2025-04-10',
]

In [7]:
import psutil
import os
import time

# Function to get memory usage in MB
def get_memory_usage():
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024  # in MB

In [15]:
for i in range(8):
    Date_list = Date_list+Date_list

In [42]:
# Before
mem_before = get_memory_usage()
data_list = []
for date in Date_list:    # data = pd.read_feather(dir_path + f"/{WellInfoDict['wid']}_{date}.feather")
    data = pd.read_parquet(dir_path + f"/{WellInfoDict['wid']}_{date}.parquet")
    data_list.append(data)

OutputRealtime = pd.concat(data_list, ignore_index=True)

OutputRealtime

,dt,date,time,bitdepth,md,blockpos,rop,hklda,woba,torqa,rpm,stppress,mudflowin
0,2025-04-07 00:00:00,2025-04-07,00:00:00,98.2,220.00,1.02,0.0,8.85,0.0,0.0,0.0,0.0,0.0
1,2025-04-07 00:00:05,2025-04-07,00:00:05,98.2,220.00,1.02,0.0,8.75,0.0,0.0,0.0,0.0,0.0
2,2025-04-07 00:00:10,2025-04-07,00:00:10,98.2,220.00,1.02,0.0,8.73,0.0,0.0,0.0,0.0,0.0
3,2025-04-07 00:00:15,2025-04-07,00:00:15,98.2,220.00,1.02,0.0,8.73,0.0,0.0,0.0,0.0,0.0
4,2025-04-07 00:00:20,2025-04-07,00:00:20,98.2,220.00,1.02,0.0,8.73,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69115,2025-04-10 23:59:35,2025-04-10,23:59:35,0.0,640.05,77.62,0.0,5.22,0.0,0.0,0.0,0.0,0.0
69116,2025-04-10 23:59:40,2025-04-10,23:59:40,0.0,640.05,77.62,0.0,5.22,0.0,0.0,0.0,0.0,0.0
69117,2025-04-10 23:59:45,2025-04-10,23:59:45,0.0,640.05,77.62,0.0,5.22,0.0,0.0,0.0,0.0,0.0
69118,2025-04-10 23:59:50,2025-04-10,23:59:50,0.0,640.05,77.62,0.0,5.22,0.0,0.0,0.0,0.0,0.0
69119,2025-04-10 23:59:55,2025-04-10,23:59:55,0.0,640.05,77.62,0.0,5.22,0.0,0.0,0.0,0.0,0.0

In [43]:
# Assume your DataFrame is named df and `dt` is already in datetime format
OutputRealtime['dt'] = pd.to_datetime(OutputRealtime['dt'])

# Set dt as index (needed for resampling)
OutputRealtime = OutputRealtime.set_index('dt')

# Group by 30-minute intervals
# groups = [group for _, group in OutputRealtime.groupby(pd.Grouper(freq='30T'))]
group_dict = {
    str(group.index.min()): group
    for _, group in OutputRealtime.groupby(pd.Grouper(freq='60T'))
}

In [44]:
for key,value in group_dict.items():
    # group_dict[key] = value.reset_index()
    value.to_parquet(dir_path + f"/{WellInfoDict['wid']}_{key.replace(' ', '_').replace(':', '')}.parquet", compression='gzip')

In [38]:
"2025-04-07 00:00:00".replace(' ', '_').replace(':', '')

'2025-04-07_000000'